read(ifile) this % r__calcoxide
read(ifile) this % r__updated_restart
read(ifile) this % r__gasflg
read(ifile) this % r__nconvg
read(ifile) this % r__ncont
read(ifile) this % r__IsModelingSpentFuel
read(ifile) this % r__title
read(ifile) this % r__PrintType
read(ifile) this % r__RelocModel
read(ifile) this % r__hgapt_flag  ! YU JIANKAI
read(ifile) this % r__flag_iapws  ! YU JIANKAI
read(ifile) this % r__irefab
read(ifile) this % r__nrefab1
read(ifile) this % r__nrefab2
read(ifile) this % r__idatingcreep
read(ifile) this % r__ncreephist
read(ifile) this % r__ncreepstep
read(ifile) this % r__ncreeptab
read(ifile) this % r__DecayModel
read(ifile) this % r__lschni
read(ifile) this % r__iquit
read(ifile) this % r__ir1
read(ifile) this % r__it
read(ifile) this % r__itt
read(ifile) this % r__iter
read(ifile) this % r__jmin
read(ifile) this % r__jmax
read(ifile) this % r__j
read(ifile) this % r__jjc
read(ifile) this % r__jfix
read(ifile) this % r__k
read(ifile) this % r__m
read(ifile) this % r__nab
read(ifile) this % r__nplast
read(ifile) this % r__nrm1
read(ifile) this % r__icor
read(ifile) this % r__idxgas
read(ifile) this % r__ivardm
read(ifile) this % r__ncreep
read(ifile) this % r__newprb
read(ifile) this % r__nheal
read(ifile) this % r__nt
read(ifile) this % r__nvoid
read(ifile) this % r__nplot
read(ifile) this % r__coupled
read(ifile) this % r__nfrttr
read(ifile) this % r__nrestr
read(ifile) this % r__jdlpr
read(ifile) this % r__nopt
read(ifile) this % r__nread
read(ifile) this % r__ntape
read(ifile) this % r__ounit
read(ifile) this % r__iunit
read(ifile) this % r__scrunit
read(ifile) this % r__funit
read(ifile) this % r__punit
read(ifile) this % r__ntaps
read(ifile) this % r__ntapi
read(ifile) this % r__ftunit
read(ifile) this % r__ddunit
read(ifile) this % r__nunits
read(ifile) this % r__graphna
read(ifile) this % r__graphnr
read(ifile) this % r__icm
read(ifile) this % r__imox
read(ifile) this % r__iplant
read(ifile) this % r__zr2vintage
read(ifile) this % r__iq
read(ifile) this % r__igas
read(ifile) this % r__igascal
read(ifile) this % r__ifixedtsurf
read(ifile) this % r__nsp
read(ifile) this % r__ifixedcoolt
read(ifile) this % r__ifixedcoolp
read(ifile) this % r__TimeIntegration
read(ifile) this % r__moxtype
read(ifile) this % r__cooltype
read(ifile) this % r__geom
read(ifile) this % r__im_old
read(ifile) this % r__mechan
read(ifile) this % r__ngasmod
read(ifile) this % r__gapmin
read(ifile) this % r__gaph
read(ifile) this % r__gapt
read(ifile) this % r__airin
read(ifile) this % r__angi
read(ifile) this % r__an2in
read(ifile) this % r__argin
read(ifile) this % r__avflux
read(ifile) this % r__bu
read(ifile) this % r__buold
read(ifile) this % r__cfv
read(ifile) this % r__cfva
read(ifile) this % r__convc
read(ifile) this % r__cpv
read(ifile) this % r__ctemp
read(ifile) this % r__dcobol
read(ifile) this % r__delbp
read(ifile) this % r__delbu
read(ifile) this % r__delh
read(ifile) this % r__deltcr
read(ifile) this % r__deltdb
read(ifile) this % r__deltfc
read(ifile) this % r__deltjl
read(ifile) this % r__delhs
read(ifile) this % r__dlrel
read(ifile) this % r__dlrod
read(ifile) this % r__dphf
read(ifile) this % r__dphfrl
read(ifile) this % r__dhfll
read(ifile) this % r__fgin
read(ifile) this % r__fpor1
read(ifile) this % r__hcrv
read(ifile) this % r__hcv
read(ifile) this % r__hdshv
read(ifile) this % r__hein
read(ifile) this % r__h2oin
read(ifile) this % r__h2in
read(ifile) this % r__hfll
read(ifile) this % r__hflmdb
read(ifile) this % r__hflmp
read(ifile) this % r__hfper
read(ifile) this % r__hfv
read(ifile) this % r__hgapt
read(ifile) this % r__hgv
read(ifile) this % r__hgap
read(ifile) this % r__hsolid
read(ifile) this % r__hgapr
read(ifile) this % r__hpl
read(ifile) this % r__hporv
read(ifile) this % r__hpv
read(ifile) this % r__hva
read(ifile) this % r__h2omi
read(ifile) this % r__kryin
read(ifile) this % r__nu
read(ifile) this % r__pecdh
read(ifile) this % r__rprm1
read(ifile) this % r__press
read(ifile) this % r__prty
read(ifile) this % r__rci
read(ifile) this % r__rco
read(ifile) this % r__rtemp
read(ifile) this % r__qav
read(ifile) this % r__qpeak
read(ifile) this % r__pkZrO2WtGain
read(ifile) this % r__rfnvff
read(ifile) this % r__rhofuel
read(ifile) this % r__rp
read(ifile) this % r__rstran
read(ifile) this % r__rtran
read(ifile) this % r__sumck
read(ifile) this % r__sumdh
read(ifile) this % r__sumexp
read(ifile) this % r__sumgp
read(ifile) this % r__sumpor
read(ifile) this % r__sumrg
read(ifile) this % r__t
read(ifile) this % r__thvv
read(ifile) this % r__tci
read(ifile) this % r__tco
read(ifile) this % r__tfgfr
read(ifile) this % r__thefr
read(ifile) this % r__th2ofr
read(ifile) this % r__tn2fr
read(ifile) this % r__tpa
read(ifile) this % r__tplen
read(ifile) this % r__transt
read(ifile) this % r__tsat
read(ifile) this % r__txa
read(ifile) this % r__txal
read(ifile) this % r__txc
read(ifile) this % r__visc
read(ifile) this % r__vplt
read(ifile) this % r__wt
read(ifile) this % r__xein
read(ifile) this % r__zro2wg
read(ifile) this % r__cladavgtemp
read(ifile) this % r__tpca
read(ifile) this % r__tntera
read(ifile) this % r__fnck
read(ifile) this % r__fncn
read(ifile) this % r__cwkf
read(ifile) this % r__cwnf
read(ifile) this % r__coldwk
read(ifile) this % r__frcoef
read(ifile) this % r__afal
read(ifile) this % r__afdn
read(ifile) this % r__afgr
read(ifile) this % r__amfair
read(ifile) this % r__amffg
read(ifile) this % r__catexf
read(ifile) this % r__chorg
read(ifile) this % r__cldwks
read(ifile) this % r__cpl
read(ifile) this % r__crephr
read(ifile) this % r__crdt
read(ifile) this % r__crdtr
read(ifile) this % r__dishsd
read(ifile) this % r__fa
read(ifile) this % r__fgpav
read(ifile) this % r__fotmtl
read(ifile) this % r__chmfrh
read(ifile) this % r__chmfrw
read(ifile) this % r__hdish
read(ifile) this % r__hplt
read(ifile) this % r__pitch
read(ifile) this % r__ppmh2o
read(ifile) this % r__ppmn2
read(ifile) this % r__rdish
read(ifile) this % r__roughc
read(ifile) this % r__roughf
read(ifile) this % r__sgapf
read(ifile) this % r__tcc
read(ifile) this % r__tref
read(ifile) this % r__TGasFab
read(ifile) this % r__rsntr
read(ifile) this % r__tsint
read(ifile) this % r__grnsize
read(ifile) this % r__b10
read(ifile) this % r__zrb2thick
read(ifile) this % r__zrb2den
read(ifile) this % r__prvden
read(ifile) this % r__ifba
read(ifile) this % r__ftmelt
read(ifile) this % r__fhefus
read(ifile) this % r__ctmelt
read(ifile) this % r__chefus
read(ifile) this % r__ctranb
read(ifile) this % r__ctrane
read(ifile) this % r__ctranz
read(ifile) this % r__fdelta
read(ifile) this % r__bup
read(ifile) this % r__deloxy
read(ifile) this % r__zro2i
read(ifile) this % r__zro2o
read(ifile) this % r__zoxk
read(ifile) this % r__excesh2
read(ifile) this % r__frden
read(ifile) this % r__totl
read(ifile) this % r__rdot
read(ifile) this % r__cvv
read(ifile) this % r__gmlesAsFab
read(ifile) this % r__gmlesReleased
read(ifile) this % r__vfrcpl
read(ifile) this % r__tplens
read(ifile) this % r__slim
read(ifile) this % r__gaphtcmult
read(ifile) this % r__RestartTime
read(ifile) this % r__sigftc
read(ifile) this % r__sigftex
read(ifile) this % r__sigfgr
read(ifile) this % r__sigswell
read(ifile) this % r__sigcreep
read(ifile) this % r__siggro
read(ifile) this % r__sigcor
read(ifile) this % r__sigh2
read(ifile) this % r__newtimestep
read(ifile) this % r__stopox
read(ifile) this % r__deng
read(ifile) this % r__den
read(ifile) this % r__amfhe
read(ifile) this % r__amfh2
read(ifile) this % r__amfn2
read(ifile) this % r__amfarg
read(ifile) this % r__amfkry
read(ifile) this % r__amfxe
read(ifile) this % r__amfh2o
read(ifile) this % r__enrpu39
read(ifile) this % r__enrpu40
read(ifile) this % r__enrpu41
read(ifile) this % r__enrpu42
read(ifile) this % r__facmot
read(ifile) this % r__DebugTime
read(ifile) this % r__modheat
read(ifile) this % r__cladelmod
read(ifile) this % r__fuelreloc
read(ifile) this % r__gaprecov
read(ifile) this % r__relocm_true
read(ifile) this % r__relocm_mod
read(ifile) this % r__cplrefab
read(ifile) this % r__vsrefab
read(ifile) this % r__dspgrefab
read(ifile) this % r__dspgwrefab
read(ifile) this % r__fgpavrefab
read(ifile) this % r__airrefab
read(ifile) this % r__n2refab
read(ifile) this % r__arrefab
read(ifile) this % r__fgrefab
read(ifile) this % r__herefab
read(ifile) this % r__krrefab
read(ifile) this % r__xerefab
read(ifile) this % r__creeppooltime
read(ifile) this % r__creeptime
read(ifile) this % r__datingtstep
read(ifile) this % r__pfave
read(ifile) this % r__por000
read(ifile) this % r__ntot
read(ifile) this % r__fpdcay
read(ifile) this % r__vs
read(ifile) this % r__dspg
read(ifile) this % r__dspgw
read(ifile) this % r__vcold
read(ifile) this % r__openp
read(ifile) this % r__IgapGapIndex
read(ifile) this % r__IgapIndexOld
read(ifile) this % r__IgapIndexPrevOld
read(ifile) this % r__jn
read(ifile) this % r__jnsurftemp
read(ifile) this % r__jpeak
read(ifile) this % r__jst
read(ifile) this % r__jstsurftemp
read(ifile) this % r__CycleSteps
read(ifile) this % r__gases
read(ifile) this % r__totinner
read(ifile) this % r__totcrl
read(ifile) this % r__FastFluxd
read(ifile) this % r__FastFluenced
read(ifile) this % r__BulkCoolantTemp
read(ifile) this % r__rhof
read(ifile) this % r__dpwxrate
read(ifile) this % r__axialnode
read(ifile) this % r__PelletRad
read(ifile) this % r__CladAveTemp
read(ifile) this % r__PelAveTemp
read(ifile) this % r__GapAveTemp
read(ifile) this % r__PelSurfTemp
read(ifile) this % r__PelCentTemp
read(ifile) this % r__sigeff
read(ifile) this % r__FuelSurfDispl
read(ifile) this % r__CladInSurDisp
read(ifile) this % r__CladInPermDef
read(ifile) this % r__sigy
read(ifile) this % r__AxialNodLength
read(ifile) this % r__CladEffPlasStrain
read(ifile) this % r__RinterfacPress
read(ifile) this % r__FuelCladGap
read(ifile) this % r__GapPress
read(ifile) this % r__CoolantPress
read(ifile) this % r__PlastStrnep1
read(ifile) this % r__OldCladStrn
read(ifile) this % r__OldFuelStrn
read(ifile) this % r__OldGapPress
read(ifile) this % r__OldCoolPress
read(ifile) this % r__OldFuelDispl
read(ifile) this % r__OldCladAvTemp
read(ifile) this % r__CreepStrain
read(ifile) this % r__CreepStrain1
read(ifile) this % r__CladDiamHot
read(ifile) this % r__PrevCladEffPlasStrn
read(ifile) this % r__PrevFuelStrain
read(ifile) this % r__HotNodLength
read(ifile) this % r__PermFuelDispl
read(ifile) this % r__BOSNodeburnup
read(ifile) this % r__EOSNodeburnup
read(ifile) this % r__StepNodeburnup
read(ifile) this % r__TotalHgap
read(ifile) this % r__SolidHgap
read(ifile) this % r__GasHgap
read(ifile) this % r__RadHgap
read(ifile) this % r__FastFlux
read(ifile) this % r__FastFluence
read(ifile) this % r__FuelPorosity
read(ifile) this % r__FilmCoefficient
read(ifile) this % r__EstGapDeltaT
read(ifile) this % r__BOSZrO2Thk
read(ifile) this % r__EOSZrO2Thk
read(ifile) this % r__ZrO2ThkNoAd
read(ifile) this % r__FuelCondFactor
read(ifile) this % r__Relocation
read(ifile) this % r__RinternalVolume
read(ifile) this % r__CladVolume
read(ifile) this % r__CrackVolume
read(ifile) this % r__RinterfacVolume
read(ifile) this % r__FuelVolume
read(ifile) this % r__fden
read(ifile) this % r__GapVolume
read(ifile) this % r__PorosityVolume
read(ifile) this % r__SurfTempOxide
read(ifile) this % r__AnnulusVolume
read(ifile) this % r__gapplot
read(ifile) this % r__PrevOldCoolPress
read(ifile) this % r__PrevOldGapPress
read(ifile) this % r__PrevOldCladAvTemp
read(ifile) this % r__PrevOldFuelDispl
read(ifile) this % r__PrevCreepStrain
read(ifile) this % r__CladIrradGrowStrn
read(ifile) this % r__UniformAxNodStrn
read(ifile) this % r__CladH2Concen
read(ifile) this % r__ExcessH2Concen
read(ifile) this % r__PrevCladStrain
read(ifile) this % r__StartofStepH2Con
read(ifile) this % r__StartofStepPickupH2Con
read(ifile) this % r__EndofStepPickupH2Con
read(ifile) this % r__FuelTempRestruRad
read(ifile) this % r__OldHealedCrackRadius
read(ifile) this % r__StoredEnergy
read(ifile) this % r__HealedCrackRadius
read(ifile) this % r__HotThermalGap
read(ifile) this % r__WorkArray1
read(ifile) this % r__WorkArray2
read(ifile) this % r__WorkArray3
read(ifile) this % r__CladInSurfTemp
read(ifile) this % r__CladOutSurfTemp
read(ifile) this % r__Power
read(ifile) this % r__gpthe
read(ifile) this % r__gpth
read(ifile) this % r__gpthpg
read(ifile) this % r__qc
read(ifile) this % r__totdef
read(ifile) this % r__buin
read(ifile) this % r__dci
read(ifile) this % r__dco
read(ifile) this % r__thkcld
read(ifile) this % r__cdg
read(ifile) this % r__thkgap
read(ifile) this % r__de
read(ifile) this % r__deltaz
read(ifile) this % r__comp
read(ifile) this % r__ctmax
read(ifile) this % r__dp
read(ifile) this % r__flux
read(ifile) this % r__qend
read(ifile) this % r__crudmult
read(ifile) this % r__crdtt
read(ifile) this % r__rdotwrt
read(ifile) this % r__FDItave
read(ifile) this % r__creapratearray
read(ifile) this % r__GapCond
read(ifile) this % r__fuelexptot
read(ifile) this % r__fuelswltot
read(ifile) this % r__fuelcreeptot
read(ifile) this % r__fueldentot
read(ifile) this % r__fuelburntot
read(ifile) this % r__cladcrptot
read(ifile) this % r__gapHTC
read(ifile) this % r__oxidelayer
read(ifile) this % r__gapmech
read(ifile) this % r__gapthrm
read(ifile) this % r__fuelrelmod
read(ifile) this % r__ifbarel
read(ifile) this % r__NodalMoles
read(ifile) this % r__NodalGMLES
read(ifile) this % r__rlcstrn
read(ifile) this % r__rlcstrnold
read(ifile) this % r__rc
read(ifile) this % r__gadoln
read(ifile) this % r__colddef
read(ifile) this % r__colddec
read(ifile) this % r__qnode
read(ifile) this % r__heprod
read(ifile) this % r__he
read(ifile) this % r__heold
read(ifile) this % r__boron10
read(ifile) this % r__enrch
read(ifile) this % r__epsav
read(ifile) this % r__wimsburnup
read(ifile) this % r__oldwimsburnup
read(ifile) this % r__stold
read(ifile) this % r__stnew
read(ifile) this % r__deltimeold
read(ifile) this % r__deltimenew
read(ifile) this % r__sagold
read(ifile) this % r__sagnew
read(ifile) this % r__delsagold
read(ifile) this % r__delsagnew
read(ifile) this % r__delst
read(ifile) this % r__angr
read(ifile) this % r__ah2ogr
read(ifile) this % r__fgmgp
read(ifile) this % r__fmgr
read(ifile) this % r__hemgp
read(ifile) this % r__hmgr
read(ifile) this % r__ang
read(ifile) this % r__ah2og
read(ifile) this % r__epp
read(ifile) this % r__eppp
read(ifile) this % r__eppsv
read(ifile) this % r__eps
read(ifile) this % r__feps
read(ifile) this % r__reps
read(ifile) this % r__repsv
read(ifile) this % r__repsp
read(ifile) this % r__rfeps
read(ifile) this % r__rfepp
read(ifile) this % r__rfpsv
read(ifile) this % r__sig
read(ifile) this % r__epp1
read(ifile) this % r__sig1
read(ifile) this % r__eps1
read(ifile) this % r__ThermalStrain
read(ifile) this % r__RB_axial
read(ifile) this % r__RB_rod
read(ifile) this % r__avgqi
read(ifile) this % r__go
read(ifile) this % r__p2
read(ifile) this % r__ProblemTime
read(ifile) this % r__ProblemTime_Prev
read(ifile) this % r__qmpy
read(ifile) this % r__tw
read(ifile) this % r__p1
read(ifile) this % r__acmfg
read(ifile) this % r__acmhe
read(ifile) this % r__acmH2
read(ifile) this % r__acmH2O
read(ifile) this % r__acmn2
read(ifile) this % r__amgpt
read(ifile) this % r__gasmo
read(ifile) this % r__hmgpt
read(ifile) this % r__tafa
read(ifile) this % r__taga
read(ifile) this % r__tsfa
read(ifile) this % r__taca
read(ifile) this % r__pkPelAveTemp
read(ifile) this % r__pkPower
read(ifile) this % r__pkAveCladTemp
read(ifile) this % r__pkGap
read(ifile) this % r__pkFisGasRelFrac
read(ifile) this % r__pkPelSurfTemp
read(ifile) this % r__pkPelCentTemp
read(ifile) this % r__pkH2up
read(ifile) this % r__pkIntefacePres
read(ifile) this % r__pkIDCladTemp
read(ifile) this % r__pkODCladTemp
read(ifile) this % r__pit
read(ifile) this % r__pkHoopStres
read(ifile) this % r__pkAxlStres
read(ifile) this % r__pkBurnup
read(ifile) this % r__pkHoopStrain
read(ifile) this % r__pkFuelPelOD
read(ifile) this % r__pkGapCond
read(ifile) this % r__pkZrO2
read(ifile) this % r__zcool
read(ifile) this % r__tcoolant
read(ifile) this % r__pcoolant
read(ifile) this % r__x
read(ifile) this % r__qf
read(ifile) this % r__xt
read(ifile) this % r__cladt
read(ifile) this % r__addgmles
read(ifile) this % r__addswell
read(ifile) this % r__HeatFlux
read(ifile) this % r__dt
read(ifile) this % r__buavearray
read(ifile) this % r__voidvolarray
read(ifile) this % r__he_ifba
read(ifile) this % r__tfuelr
read(ifile) this % r__tfuelr2
read(ifile) this % r__tfring
read(ifile) this % r__rrapow
read(ifile) this % r__coolanttemp
read(ifile) this % r__coolantpressure
read(ifile) this % r__cladtarray
read(ifile) this % r__storedearray
read(ifile) this % r__cltemparray
read(ifile) this % r__buarray
read(ifile) this % r__strainarray
read(ifile) this % r__straindiffarray
read(ifile) this % r__dpwxarray
read(ifile) this % r__creaparray
read(ifile) this % r__dumarray3
read(ifile) this % r__formf
read(ifile) this % r__ringvol
read(ifile) this % r__coldringl
read(ifile) this % r__porosold
read(ifile) this % r__porosnew
read(ifile) this % r__rrev
read(ifile) this % r__qaxnorm
read(ifile) this % r__crad
read(ifile) this % r__hrad
read(ifile) this % r__rapow
read(ifile) this % r__uo2exp
read(ifile) this % r__dpw
read(ifile) this % r__dpwpp
read(ifile) this % r__dpw2
read(ifile) this % r__dpwpp2
read(ifile) this % r__densf
read(ifile) this % r__densp
read(ifile) this % r__hotringl
read(ifile) this % r__tmpfuel
read(ifile) this % r__gasavail1
read(ifile) this % r__gasavail2
read(ifile) this % r__prdct
read(ifile) this % r__brnup3
read(ifile) this % r__ansd
read(ifile) this % r__creeptabtime
read(ifile) this % r__creeptabtemp
read(ifile) this % r__creeptabstress
read(ifile) this % r__conU235
read(ifile) this % r__conU238
read(ifile) this % r__conPu239
read(ifile) this % r__conPu240
read(ifile) this % r__conPu241
read(ifile) this % r__conPu242
read(ifile) this % r__coU235av
read(ifile) this % r__coU238av
read(ifile) this % r__coPu239av
read(ifile) this % r__coPu240av
read(ifile) this % r__coPu241av
read(ifile) this % r__coPu242av
read(ifile) this % r__enriU235
read(ifile) this % r__enriU238
read(ifile) this % r__enriPu239
read(ifile) this % r__enriPu240
read(ifile) this % r__enriPu241
read(ifile) this % r__enriPu242
read(ifile) this % r__pfU235
read(ifile) this % r__pfU238
read(ifile) this % r__pfPu239
read(ifile) this % r__pfPu240
read(ifile) this % r__pfPu241
read(ifile) this % r__pfPu242
read(ifile) this % r__pf
read(ifile) this % r__decay
read(ifile) this % r__half
read(ifile) this % r__brnup1
read(ifile) this % r__ansr
read(ifile) this % r__gp
read(ifile) this % r__gpold
read(ifile) this % r__rls
read(ifile) this % r__rlsold
read(ifile) this % r__brn
read(ifile) this % r__brnrefab
read(ifile) this % r__EOSNodeburnuprefab
read(ifile) this % r__brnold
read(ifile) this % r__grnold
read(ifile) this % r__frdenold
read(ifile) this % r__gbtot
read(ifile) this % r__tempkold
read(ifile) this % r__gb
read(ifile) this % r__grs
read(ifile) this % r__gg
read(ifile) this % r__gbold
read(ifile) this % r__ggold
read(ifile) this % r__grsold
read(ifile) this % r__g1
read(ifile) this % r__g2
read(ifile) this % r__g3
read(ifile) this % r__g4
read(ifile) this % r__g1old
read(ifile) this % r__g2old
read(ifile) this % r__g3old
read(ifile) this % r__g4old
read(ifile) this % r__namerf