write(ifile) this % r__calcoxide
write(ifile) this % r__updated_restart
write(ifile) this % r__gasflg
write(ifile) this % r__nconvg
write(ifile) this % r__ncont
write(ifile) this % r__IsModelingSpentFuel
write(ifile) this % r__title
write(ifile) this % r__PrintType
write(ifile) this % r__RelocModel
write(ifile) this % r__hgapt_flag  ! YU JIANKAI
write(ifile) this % r__flag_iapws  ! YU JIANKAI
write(ifile) this % r__irefab
write(ifile) this % r__nrefab1
write(ifile) this % r__nrefab2
write(ifile) this % r__idatingcreep
write(ifile) this % r__ncreephist
write(ifile) this % r__ncreepstep
write(ifile) this % r__ncreeptab
write(ifile) this % r__DecayModel
write(ifile) this % r__lschni
write(ifile) this % r__iquit
write(ifile) this % r__ir1
write(ifile) this % r__it
write(ifile) this % r__itt
write(ifile) this % r__iter
write(ifile) this % r__jmin
write(ifile) this % r__jmax
write(ifile) this % r__j
write(ifile) this % r__jjc
write(ifile) this % r__jfix
write(ifile) this % r__k
write(ifile) this % r__m
write(ifile) this % r__nab
write(ifile) this % r__nplast
write(ifile) this % r__nrm1
write(ifile) this % r__icor
write(ifile) this % r__idxgas
write(ifile) this % r__ivardm
write(ifile) this % r__ncreep
write(ifile) this % r__newprb
write(ifile) this % r__nheal
write(ifile) this % r__nt
write(ifile) this % r__nvoid
write(ifile) this % r__nplot
write(ifile) this % r__coupled
write(ifile) this % r__nfrttr
write(ifile) this % r__nrestr
write(ifile) this % r__jdlpr
write(ifile) this % r__nopt
write(ifile) this % r__nread
write(ifile) this % r__ntape
write(ifile) this % r__ounit
write(ifile) this % r__iunit
write(ifile) this % r__scrunit
write(ifile) this % r__funit
write(ifile) this % r__punit
write(ifile) this % r__ntaps
write(ifile) this % r__ntapi
write(ifile) this % r__ftunit
write(ifile) this % r__ddunit
write(ifile) this % r__nunits
write(ifile) this % r__graphna
write(ifile) this % r__graphnr
write(ifile) this % r__icm
write(ifile) this % r__imox
write(ifile) this % r__iplant
write(ifile) this % r__zr2vintage
write(ifile) this % r__iq
write(ifile) this % r__igas
write(ifile) this % r__igascal
write(ifile) this % r__ifixedtsurf
write(ifile) this % r__nsp
write(ifile) this % r__ifixedcoolt
write(ifile) this % r__ifixedcoolp
write(ifile) this % r__TimeIntegration
write(ifile) this % r__moxtype
write(ifile) this % r__cooltype
write(ifile) this % r__geom
write(ifile) this % r__im_old
write(ifile) this % r__mechan
write(ifile) this % r__ngasmod
write(ifile) this % r__gapmin
write(ifile) this % r__gaph
write(ifile) this % r__gapt
write(ifile) this % r__airin
write(ifile) this % r__angi
write(ifile) this % r__an2in
write(ifile) this % r__argin
write(ifile) this % r__avflux
write(ifile) this % r__bu
write(ifile) this % r__buold
write(ifile) this % r__cfv
write(ifile) this % r__cfva
write(ifile) this % r__convc
write(ifile) this % r__cpv
write(ifile) this % r__ctemp
write(ifile) this % r__dcobol
write(ifile) this % r__delbp
write(ifile) this % r__delbu
write(ifile) this % r__delh
write(ifile) this % r__deltcr
write(ifile) this % r__deltdb
write(ifile) this % r__deltfc
write(ifile) this % r__deltjl
write(ifile) this % r__delhs
write(ifile) this % r__dlrel
write(ifile) this % r__dlrod
write(ifile) this % r__dphf
write(ifile) this % r__dphfrl
write(ifile) this % r__dhfll
write(ifile) this % r__fgin
write(ifile) this % r__fpor1
write(ifile) this % r__hcrv
write(ifile) this % r__hcv
write(ifile) this % r__hdshv
write(ifile) this % r__hein
write(ifile) this % r__h2oin
write(ifile) this % r__h2in
write(ifile) this % r__hfll
write(ifile) this % r__hflmdb
write(ifile) this % r__hflmp
write(ifile) this % r__hfper
write(ifile) this % r__hfv
write(ifile) this % r__hgapt
write(ifile) this % r__hgv
write(ifile) this % r__hgap
write(ifile) this % r__hsolid
write(ifile) this % r__hgapr
write(ifile) this % r__hpl
write(ifile) this % r__hporv
write(ifile) this % r__hpv
write(ifile) this % r__hva
write(ifile) this % r__h2omi
write(ifile) this % r__kryin
write(ifile) this % r__nu
write(ifile) this % r__pecdh
write(ifile) this % r__rprm1
write(ifile) this % r__press
write(ifile) this % r__prty
write(ifile) this % r__rci
write(ifile) this % r__rco
write(ifile) this % r__rtemp
write(ifile) this % r__qav
write(ifile) this % r__qpeak
write(ifile) this % r__pkZrO2WtGain
write(ifile) this % r__rfnvff
write(ifile) this % r__rhofuel
write(ifile) this % r__rp
write(ifile) this % r__rstran
write(ifile) this % r__rtran
write(ifile) this % r__sumck
write(ifile) this % r__sumdh
write(ifile) this % r__sumexp
write(ifile) this % r__sumgp
write(ifile) this % r__sumpor
write(ifile) this % r__sumrg
write(ifile) this % r__t
write(ifile) this % r__thvv
write(ifile) this % r__tci
write(ifile) this % r__tco
write(ifile) this % r__tfgfr
write(ifile) this % r__thefr
write(ifile) this % r__th2ofr
write(ifile) this % r__tn2fr
write(ifile) this % r__tpa
write(ifile) this % r__tplen
write(ifile) this % r__transt
write(ifile) this % r__tsat
write(ifile) this % r__txa
write(ifile) this % r__txal
write(ifile) this % r__txc
write(ifile) this % r__visc
write(ifile) this % r__vplt
write(ifile) this % r__wt
write(ifile) this % r__xein
write(ifile) this % r__zro2wg
write(ifile) this % r__cladavgtemp
write(ifile) this % r__tpca
write(ifile) this % r__tntera
write(ifile) this % r__fnck
write(ifile) this % r__fncn
write(ifile) this % r__cwkf
write(ifile) this % r__cwnf
write(ifile) this % r__coldwk
write(ifile) this % r__frcoef
write(ifile) this % r__afal
write(ifile) this % r__afdn
write(ifile) this % r__afgr
write(ifile) this % r__amfair
write(ifile) this % r__amffg
write(ifile) this % r__catexf
write(ifile) this % r__chorg
write(ifile) this % r__cldwks
write(ifile) this % r__cpl
write(ifile) this % r__crephr
write(ifile) this % r__crdt
write(ifile) this % r__crdtr
write(ifile) this % r__dishsd
write(ifile) this % r__fa
write(ifile) this % r__fgpav
write(ifile) this % r__fotmtl
write(ifile) this % r__chmfrh
write(ifile) this % r__chmfrw
write(ifile) this % r__hdish
write(ifile) this % r__hplt
write(ifile) this % r__pitch
write(ifile) this % r__ppmh2o
write(ifile) this % r__ppmn2
write(ifile) this % r__rdish
write(ifile) this % r__roughc
write(ifile) this % r__roughf
write(ifile) this % r__sgapf
write(ifile) this % r__tcc
write(ifile) this % r__tref
write(ifile) this % r__TGasFab
write(ifile) this % r__rsntr
write(ifile) this % r__tsint
write(ifile) this % r__grnsize
write(ifile) this % r__b10
write(ifile) this % r__zrb2thick
write(ifile) this % r__zrb2den
write(ifile) this % r__prvden
write(ifile) this % r__ifba
write(ifile) this % r__ftmelt
write(ifile) this % r__fhefus
write(ifile) this % r__ctmelt
write(ifile) this % r__chefus
write(ifile) this % r__ctranb
write(ifile) this % r__ctrane
write(ifile) this % r__ctranz
write(ifile) this % r__fdelta
write(ifile) this % r__bup
write(ifile) this % r__deloxy
write(ifile) this % r__zro2i
write(ifile) this % r__zro2o
write(ifile) this % r__zoxk
write(ifile) this % r__excesh2
write(ifile) this % r__frden
write(ifile) this % r__totl
write(ifile) this % r__rdot
write(ifile) this % r__cvv
write(ifile) this % r__gmlesAsFab
write(ifile) this % r__gmlesReleased
write(ifile) this % r__vfrcpl
write(ifile) this % r__tplens
write(ifile) this % r__slim
write(ifile) this % r__gaphtcmult
write(ifile) this % r__RestartTime
write(ifile) this % r__sigftc
write(ifile) this % r__sigftex
write(ifile) this % r__sigfgr
write(ifile) this % r__sigswell
write(ifile) this % r__sigcreep
write(ifile) this % r__siggro
write(ifile) this % r__sigcor
write(ifile) this % r__sigh2
write(ifile) this % r__newtimestep
write(ifile) this % r__stopox
write(ifile) this % r__deng
write(ifile) this % r__den
write(ifile) this % r__amfhe
write(ifile) this % r__amfh2
write(ifile) this % r__amfn2
write(ifile) this % r__amfarg
write(ifile) this % r__amfkry
write(ifile) this % r__amfxe
write(ifile) this % r__amfh2o
write(ifile) this % r__enrpu39
write(ifile) this % r__enrpu40
write(ifile) this % r__enrpu41
write(ifile) this % r__enrpu42
write(ifile) this % r__facmot
write(ifile) this % r__DebugTime
write(ifile) this % r__modheat
write(ifile) this % r__cladelmod
write(ifile) this % r__fuelreloc
write(ifile) this % r__gaprecov
write(ifile) this % r__relocm_true
write(ifile) this % r__relocm_mod
write(ifile) this % r__cplrefab
write(ifile) this % r__vsrefab
write(ifile) this % r__dspgrefab
write(ifile) this % r__dspgwrefab
write(ifile) this % r__fgpavrefab
write(ifile) this % r__airrefab
write(ifile) this % r__n2refab
write(ifile) this % r__arrefab
write(ifile) this % r__fgrefab
write(ifile) this % r__herefab
write(ifile) this % r__krrefab
write(ifile) this % r__xerefab
write(ifile) this % r__creeppooltime
write(ifile) this % r__creeptime
write(ifile) this % r__datingtstep
write(ifile) this % r__pfave
write(ifile) this % r__por000
write(ifile) this % r__ntot
write(ifile) this % r__fpdcay
write(ifile) this % r__vs
write(ifile) this % r__dspg
write(ifile) this % r__dspgw
write(ifile) this % r__vcold
write(ifile) this % r__openp
write(ifile) this % r__IgapGapIndex
write(ifile) this % r__IgapIndexOld
write(ifile) this % r__IgapIndexPrevOld
write(ifile) this % r__jn
write(ifile) this % r__jnsurftemp
write(ifile) this % r__jpeak
write(ifile) this % r__jst
write(ifile) this % r__jstsurftemp
write(ifile) this % r__CycleSteps
write(ifile) this % r__gases
write(ifile) this % r__totinner
write(ifile) this % r__totcrl
write(ifile) this % r__FastFluxd
write(ifile) this % r__FastFluenced
write(ifile) this % r__BulkCoolantTemp
write(ifile) this % r__rhof
write(ifile) this % r__dpwxrate
write(ifile) this % r__axialnode
write(ifile) this % r__PelletRad
write(ifile) this % r__CladAveTemp
write(ifile) this % r__PelAveTemp
write(ifile) this % r__GapAveTemp
write(ifile) this % r__PelSurfTemp
write(ifile) this % r__PelCentTemp
write(ifile) this % r__sigeff
write(ifile) this % r__FuelSurfDispl
write(ifile) this % r__CladInSurDisp
write(ifile) this % r__CladInPermDef
write(ifile) this % r__sigy
write(ifile) this % r__AxialNodLength
write(ifile) this % r__CladEffPlasStrain
write(ifile) this % r__RinterfacPress
write(ifile) this % r__FuelCladGap
write(ifile) this % r__GapPress
write(ifile) this % r__CoolantPress
write(ifile) this % r__PlastStrnep1
write(ifile) this % r__OldCladStrn
write(ifile) this % r__OldFuelStrn
write(ifile) this % r__OldGapPress
write(ifile) this % r__OldCoolPress
write(ifile) this % r__OldFuelDispl
write(ifile) this % r__OldCladAvTemp
write(ifile) this % r__CreepStrain
write(ifile) this % r__CreepStrain1
write(ifile) this % r__CladDiamHot
write(ifile) this % r__PrevCladEffPlasStrn
write(ifile) this % r__PrevFuelStrain
write(ifile) this % r__HotNodLength
write(ifile) this % r__PermFuelDispl
write(ifile) this % r__BOSNodeburnup
write(ifile) this % r__EOSNodeburnup
write(ifile) this % r__StepNodeburnup
write(ifile) this % r__TotalHgap
write(ifile) this % r__SolidHgap
write(ifile) this % r__GasHgap
write(ifile) this % r__RadHgap
write(ifile) this % r__FastFlux
write(ifile) this % r__FastFluence
write(ifile) this % r__FuelPorosity
write(ifile) this % r__FilmCoefficient
write(ifile) this % r__EstGapDeltaT
write(ifile) this % r__BOSZrO2Thk
write(ifile) this % r__EOSZrO2Thk
write(ifile) this % r__ZrO2ThkNoAd
write(ifile) this % r__FuelCondFactor
write(ifile) this % r__Relocation
write(ifile) this % r__RinternalVolume
write(ifile) this % r__CladVolume
write(ifile) this % r__CrackVolume
write(ifile) this % r__RinterfacVolume
write(ifile) this % r__FuelVolume
write(ifile) this % r__fden
write(ifile) this % r__GapVolume
write(ifile) this % r__PorosityVolume
write(ifile) this % r__SurfTempOxide
write(ifile) this % r__AnnulusVolume
write(ifile) this % r__gapplot
write(ifile) this % r__PrevOldCoolPress
write(ifile) this % r__PrevOldGapPress
write(ifile) this % r__PrevOldCladAvTemp
write(ifile) this % r__PrevOldFuelDispl
write(ifile) this % r__PrevCreepStrain
write(ifile) this % r__CladIrradGrowStrn
write(ifile) this % r__UniformAxNodStrn
write(ifile) this % r__CladH2Concen
write(ifile) this % r__ExcessH2Concen
write(ifile) this % r__PrevCladStrain
write(ifile) this % r__StartofStepH2Con
write(ifile) this % r__StartofStepPickupH2Con
write(ifile) this % r__EndofStepPickupH2Con
write(ifile) this % r__FuelTempRestruRad
write(ifile) this % r__OldHealedCrackRadius
write(ifile) this % r__StoredEnergy
write(ifile) this % r__HealedCrackRadius
write(ifile) this % r__HotThermalGap
write(ifile) this % r__WorkArray1
write(ifile) this % r__WorkArray2
write(ifile) this % r__WorkArray3
write(ifile) this % r__CladInSurfTemp
write(ifile) this % r__CladOutSurfTemp
write(ifile) this % r__Power
write(ifile) this % r__gpthe
write(ifile) this % r__gpth
write(ifile) this % r__gpthpg
write(ifile) this % r__qc
write(ifile) this % r__totdef
write(ifile) this % r__buin
write(ifile) this % r__dci
write(ifile) this % r__dco
write(ifile) this % r__thkcld
write(ifile) this % r__cdg
write(ifile) this % r__thkgap
write(ifile) this % r__de
write(ifile) this % r__deltaz
write(ifile) this % r__comp
write(ifile) this % r__ctmax
write(ifile) this % r__dp
write(ifile) this % r__flux
write(ifile) this % r__qend
write(ifile) this % r__crudmult
write(ifile) this % r__crdtt
write(ifile) this % r__rdotwrt
write(ifile) this % r__FDItave
write(ifile) this % r__creapratearray
write(ifile) this % r__GapCond
write(ifile) this % r__fuelexptot
write(ifile) this % r__fuelswltot
write(ifile) this % r__fuelcreeptot
write(ifile) this % r__fueldentot
write(ifile) this % r__fuelburntot
write(ifile) this % r__cladcrptot
write(ifile) this % r__gapHTC
write(ifile) this % r__oxidelayer
write(ifile) this % r__gapmech
write(ifile) this % r__gapthrm
write(ifile) this % r__fuelrelmod
write(ifile) this % r__ifbarel
write(ifile) this % r__NodalMoles
write(ifile) this % r__NodalGMLES
write(ifile) this % r__rlcstrn
write(ifile) this % r__rlcstrnold
write(ifile) this % r__rc
write(ifile) this % r__gadoln
write(ifile) this % r__colddef
write(ifile) this % r__colddec
write(ifile) this % r__qnode
write(ifile) this % r__heprod
write(ifile) this % r__he
write(ifile) this % r__heold
write(ifile) this % r__boron10
write(ifile) this % r__enrch
write(ifile) this % r__epsav
write(ifile) this % r__wimsburnup
write(ifile) this % r__oldwimsburnup
write(ifile) this % r__stold
write(ifile) this % r__stnew
write(ifile) this % r__deltimeold
write(ifile) this % r__deltimenew
write(ifile) this % r__sagold
write(ifile) this % r__sagnew
write(ifile) this % r__delsagold
write(ifile) this % r__delsagnew
write(ifile) this % r__delst
write(ifile) this % r__angr
write(ifile) this % r__ah2ogr
write(ifile) this % r__fgmgp
write(ifile) this % r__fmgr
write(ifile) this % r__hemgp
write(ifile) this % r__hmgr
write(ifile) this % r__ang
write(ifile) this % r__ah2og
write(ifile) this % r__epp
write(ifile) this % r__eppp
write(ifile) this % r__eppsv
write(ifile) this % r__eps
write(ifile) this % r__feps
write(ifile) this % r__reps
write(ifile) this % r__repsv
write(ifile) this % r__repsp
write(ifile) this % r__rfeps
write(ifile) this % r__rfepp
write(ifile) this % r__rfpsv
write(ifile) this % r__sig
write(ifile) this % r__epp1
write(ifile) this % r__sig1
write(ifile) this % r__eps1
write(ifile) this % r__ThermalStrain
write(ifile) this % r__RB_axial
write(ifile) this % r__RB_rod
write(ifile) this % r__avgqi
write(ifile) this % r__go
write(ifile) this % r__p2
write(ifile) this % r__ProblemTime
write(ifile) this % r__ProblemTime_Prev
write(ifile) this % r__qmpy
write(ifile) this % r__tw
write(ifile) this % r__p1
write(ifile) this % r__acmfg
write(ifile) this % r__acmhe
write(ifile) this % r__acmH2
write(ifile) this % r__acmH2O
write(ifile) this % r__acmn2
write(ifile) this % r__amgpt
write(ifile) this % r__gasmo
write(ifile) this % r__hmgpt
write(ifile) this % r__tafa
write(ifile) this % r__taga
write(ifile) this % r__tsfa
write(ifile) this % r__taca
write(ifile) this % r__pkPelAveTemp
write(ifile) this % r__pkPower
write(ifile) this % r__pkAveCladTemp
write(ifile) this % r__pkGap
write(ifile) this % r__pkFisGasRelFrac
write(ifile) this % r__pkPelSurfTemp
write(ifile) this % r__pkPelCentTemp
write(ifile) this % r__pkH2up
write(ifile) this % r__pkIntefacePres
write(ifile) this % r__pkIDCladTemp
write(ifile) this % r__pkODCladTemp
write(ifile) this % r__pit
write(ifile) this % r__pkHoopStres
write(ifile) this % r__pkAxlStres
write(ifile) this % r__pkBurnup
write(ifile) this % r__pkHoopStrain
write(ifile) this % r__pkFuelPelOD
write(ifile) this % r__pkGapCond
write(ifile) this % r__pkZrO2
write(ifile) this % r__zcool
write(ifile) this % r__tcoolant
write(ifile) this % r__pcoolant
write(ifile) this % r__x
write(ifile) this % r__qf
write(ifile) this % r__xt
write(ifile) this % r__cladt
write(ifile) this % r__addgmles
write(ifile) this % r__addswell
write(ifile) this % r__HeatFlux
write(ifile) this % r__dt
write(ifile) this % r__buavearray
write(ifile) this % r__voidvolarray
write(ifile) this % r__he_ifba
write(ifile) this % r__tfuelr
write(ifile) this % r__tfuelr2
write(ifile) this % r__tfring
write(ifile) this % r__rrapow
write(ifile) this % r__coolanttemp
write(ifile) this % r__coolantpressure
write(ifile) this % r__cladtarray
write(ifile) this % r__storedearray
write(ifile) this % r__cltemparray
write(ifile) this % r__buarray
write(ifile) this % r__strainarray
write(ifile) this % r__straindiffarray
write(ifile) this % r__dpwxarray
write(ifile) this % r__creaparray
write(ifile) this % r__dumarray3
write(ifile) this % r__formf
write(ifile) this % r__ringvol
write(ifile) this % r__coldringl
write(ifile) this % r__porosold
write(ifile) this % r__porosnew
write(ifile) this % r__rrev
write(ifile) this % r__qaxnorm
write(ifile) this % r__crad
write(ifile) this % r__hrad
write(ifile) this % r__rapow
write(ifile) this % r__uo2exp
write(ifile) this % r__dpw
write(ifile) this % r__dpwpp
write(ifile) this % r__dpw2
write(ifile) this % r__dpwpp2
write(ifile) this % r__densf
write(ifile) this % r__densp
write(ifile) this % r__hotringl
write(ifile) this % r__tmpfuel
write(ifile) this % r__gasavail1
write(ifile) this % r__gasavail2
write(ifile) this % r__prdct
write(ifile) this % r__brnup3
write(ifile) this % r__ansd
write(ifile) this % r__creeptabtime
write(ifile) this % r__creeptabtemp
write(ifile) this % r__creeptabstress
write(ifile) this % r__conU235
write(ifile) this % r__conU238
write(ifile) this % r__conPu239
write(ifile) this % r__conPu240
write(ifile) this % r__conPu241
write(ifile) this % r__conPu242
write(ifile) this % r__coU235av
write(ifile) this % r__coU238av
write(ifile) this % r__coPu239av
write(ifile) this % r__coPu240av
write(ifile) this % r__coPu241av
write(ifile) this % r__coPu242av
write(ifile) this % r__enriU235
write(ifile) this % r__enriU238
write(ifile) this % r__enriPu239
write(ifile) this % r__enriPu240
write(ifile) this % r__enriPu241
write(ifile) this % r__enriPu242
write(ifile) this % r__pfU235
write(ifile) this % r__pfU238
write(ifile) this % r__pfPu239
write(ifile) this % r__pfPu240
write(ifile) this % r__pfPu241
write(ifile) this % r__pfPu242
write(ifile) this % r__pf
write(ifile) this % r__decay
write(ifile) this % r__half
write(ifile) this % r__brnup1
write(ifile) this % r__ansr
write(ifile) this % r__gp
write(ifile) this % r__gpold
write(ifile) this % r__rls
write(ifile) this % r__rlsold
write(ifile) this % r__brn
write(ifile) this % r__brnrefab
write(ifile) this % r__EOSNodeburnuprefab
write(ifile) this % r__brnold
write(ifile) this % r__grnold
write(ifile) this % r__frdenold
write(ifile) this % r__gbtot
write(ifile) this % r__tempkold
write(ifile) this % r__gb
write(ifile) this % r__grs
write(ifile) this % r__gg
write(ifile) this % r__gbold
write(ifile) this % r__ggold
write(ifile) this % r__grsold
write(ifile) this % r__g1
write(ifile) this % r__g2
write(ifile) this % r__g3
write(ifile) this % r__g4
write(ifile) this % r__g1old
write(ifile) this % r__g2old
write(ifile) this % r__g3old
write(ifile) this % r__g4old

