a="""
    openp                                 
    IgapGapIndex                          
    IgapIndexOld                          
    IgapIndexPrevOld                      
    jn                                    
    jnsurftemp                            
    jpeak                                 
    jst                                   
    jstsurftemp                           
    CycleSteps                            
    gases                                 
    releas                                
    dltgc                                 
    totinner                              
    totcrl                                
    FastFluxd                             
    FastFluenced                          
    BulkCoolantTemp                       
    rhof                                  
    dpwxrate                              
    axialnode                             
    PelletRad                             
    CladAveTemp                           
    PelAveTemp                            
    GapAveTemp                            
    PelSurfTemp                           
    PelCentTemp                           
    sigeff                                
    FuelSurfDispl                         
    CladInSurDisp                         
    CladInPermDef                         
    sigy                                  
    AxialNodLength                        
    CladEffPlasStrain                     
    RinterfacPress                        
    FuelCladGap                           
    GapPress                              
    CoolantPress                          
    PlastStrnep1                          
    OldCladStrn                           
    OldFuelStrn                           
    OldGapPress                           
    OldCoolPress                          
    OldFuelDispl                          
    OldCladAvTemp                         
    CreepStrain                           
    CreepStrain1                          
    CladDiamHot                           
    PrevCladEffPlasStrn                   
    PrevFuelStrain                        
    HotNodLength                          
    PermFuelDispl                         
    BOSNodeburnup                         
    EOSNodeburnup                         
    StepNodeburnup                        
    TotalHgap                             
    SolidHgap                             
    GasHgap                               
    RadHgap                               
    FastFlux                              
    FastFluence                           
    FuelPorosity                          
    FilmCoefficient                       
    EstGapDeltaT                          
    BOSZrO2Thk                            
    EOSZrO2Thk                            
    ZrO2ThkNoAd                           
    FuelCondFactor                        
    Relocation                            
    RinternalVolume                       
    CladVolume                            
    CrackVolume                           
    RinterfacVolume                       
    FuelVolume                            
    fden                                  
    GapVolume                             
    PorosityVolume                        
    SurfTempOxide                         
    AnnulusVolume                         
    gapplot                               
    PrevOldCoolPress                      
    PrevOldGapPress                       
    PrevOldCladAvTemp                     
    PrevOldFuelDispl                      
    PrevCreepStrain                       
    CladIrradGrowStrn                     
    UniformAxNodStrn                      
    CladH2Concen                          
    ExcessH2Concen                        
    PrevCladStrain                        
    StartofStepH2Con                      
    StartofStepPickupH2Con                
    EndofStepPickupH2Con                  
    FuelTempRestruRad                     
    OldHealedCrackRadius                  
    StoredEnergy                          
    HealedCrackRadius                     
    HotThermalGap                         
    WorkArray1                            
    WorkArray2                            
    WorkArray3                            
    CladInSurfTemp                        
    CladOutSurfTemp                       
    Power                                 
    gpthe                                 
    gpth                                  
    gpthpg                                
    qc                                    
    totdef                                
    buin                                  
    dci                                   
    dco                                   
    thkcld                                
    cdg                                   
    thkgap                                
    de                                    
    deltaz                                
    comp                                  
    ctmax                                 
    dp                                    
    flux                                  
    qend                                  
    crudmult                              
    crdtt                                 
    rdotwrt                               
    FDItave                               
    creapratearray                        
    GapCond                               
    fuelexptot                            
    fuelswltot                            
    fuelcreeptot                          
    fueldentot                            
    fuelburntot                           
    cladcrptot                            
    gapHTC                                
    oxidelayer                            
    gapmech                               
    gapthrm                               
    fuelrelmod                            
    ifbarel                               
    NodalMoles                            
    NodalGMLES                            
    rlcstrn                               
    rlcstrnold                            
    rc                                    
    gadoln                                
    colddef                               
    colddec                               
    qnode                                 
    heprod                                
    he                                    
    heold                                 
    boron10                               
    enrch                                 
    epsav                                 
    wimsburnup                            
    oldwimsburnup                         
    stold                                 
    stnew                                 
    deltimeold                            
    deltimenew                            
    sagold                                
    sagnew                                
    delsagold                             
    delsagnew                             
    delst                                 
    angr                                  
    ah2ogr                                
    fgmgp                                 
    fmgr                                  
    hemgp                                 
    hmgr                                  
    ang                                   
    ah2og                                 
    epp                                   
    eppp                                  
    eppsv                                 
    eps                                   
    feps                                  
    reps                                  
    repsv                                 
    repsp                                 
    rfeps                                 
    rfepp                                 
    rfpsv                                 
    sig                                   
    epp1                                  
    sig1                                  
    eps1                                  
    ThermalStrain                         
    RB_axial                              
    RB_rod                                
    avgqi                                 
    go                                    
    p2                                    
    ProblemTime                           
    ProblemTime_Prev                      
    qmpy                                  
    tw                                    
    p1                                    
    acmfg                                 
    acmhe                                 
    acmH2                                 
    acmH2O                                
    acmn2                                 
    amgpt                                 
    gasmo                                 
    hmgpt                                 
    tafa                                  
    taga                                  
    tsfa                                  
    taca                                  
    pkPelAveTemp                          
    pkPower                               
    pkAveCladTemp                         
    pkGap                                 
    pkFisGasRelFrac                       
    pkPelSurfTemp                         
    pkPelCentTemp                         
    pkH2up                                
    pkIntefacePres                        
    pkIDCladTemp                          
    pkODCladTemp                          
    pit                                   
    pkHoopStres                           
    pkAxlStres                            
    pkBurnup                              
    pkHoopStrain                          
    pkFuelPelOD                           
    pkGapCond                             
    pkZrO2                                
    zcool                                 
    tcoolant                              
    pcoolant                              
    x                                     
    qf                                    
    xt                                    
    cladt                                 
    addgmles                              
    addswell                              
    HeatFlux                              
    dt                                    
    buavearray                            
    voidvolarray                          
    he_ifba                               
    tfuelr                                
    tfuelr2                               
    tfring                                
    rrapow                                
    coolanttemp                           
    coolantpressure                       
    cladtarray                            
    storedearray                          
    cltemparray                           
    buarray                               
    strainarray                           
    straindiffarray                       
    dpwxarray                             
    creaparray                            
    dumarray3                             
    formf                                 
    ringvol                               
    coldringl                             
    porosold                              
    porosnew                              
    rrev                                  
    qaxnorm                               
    crad                                  
    hrad                                  
    rapow                                 
    uo2exp                                
    dpw                                   
    dpwpp                                 
    dpw2                                  
    dpwpp2                                
    densf                                 
    densp                                 
    hotringl                              
    tmpfuel                               
    gasavail1                             
    gasavail2                             
    prdct                                 
    brnup3                                
    ansd                                  
    creeptabtime                          
    creeptabtemp                          
    creeptabstress                        
    conU235                               
    conU238                               
    conPu239                              
    conPu240                              
    conPu241                              
    conPu242                              
    coU235av                              
    coU238av                              
    coPu239av                             
    coPu240av                             
    coPu241av                             
    coPu242av                             
    enriU235                              
    enriU238                              
    enriPu239                             
    enriPu240                             
    enriPu241                             
    enriPu242                             
    pfU235                                
    pfU238                                
    pfPu239                               
    pfPu240                               
    pfPu241                               
    pfPu242                               
    pf                                    
    decay                                 
    half                                  
    brnup1                                
    ansr                                  
    gp                                    
    gpold                                 
    rls                                   
    rlsold                                
    brn                                   
    brnrefab                              
    EOSNodeburnuprefab                    
    brnold                                
    grnold                                
    frdenold                              
    gbtot                                 
    tempkold                              
    gb                                    
    grs                                   
    gg                                    
    gbold                                 
    ggold                                 
    grsold                                
    g1                                    
    g2                                    
    g3                                    
    g4                                    
    g1old                                 
    g2old                                 
    g3old                                 
    g4old                                 
    """

b = """
    qend                                                         
    avgqi                                                        
    go                                                           
    p2                                                           
    ProblemTime                                                  
    ProblemTime_Prev                                             
    qmpy                                                         
    tw                                                           
    p1                                                           
    jn                                                           
    jnsurftemp                                                   
    jpeak                                                        
    jst                                                          
    jstsurftemp                                                  
    acmfg                                                        
    acmhe                                                        
    acmH2                                                        
    acmH2O                                                       
    acmn2                                                        
    amgpt                                                        
    gasmo                                                        
    hmgpt                                                        
    tafa                                                         
    taga                                                         
    tsfa                                                         
    taca                                                         
    pkODCladTemp                                                 
    pkPelAveTemp                                                 
    pkPower                                                      
    pkAveCladTemp                                                
    pkIDCladTemp                                                 
    pkGap                                                        
    pkFisGasRelFrac                                              
    pkPelSurfTemp                                                
    pkH2up                                                       
    pkPelCentTemp                                                
    pkIntefacePres                                               
    pit                                                          
    pkHoopStres                                                  
    pkAxlStres                                                   
    pkBurnup                                                     
    pkHoopStrain                                                 
    pkFuelPelOD                                                  
    pkGapCond                                                    
    pkZrO2                                                       
    HeatFlux                                                     
    dt                                                           
    buavearray                                                   
    voidvolarray                                                 
    he_ifba                                                      
    addgmles                                                     
    addswell                                                     
    CycleSteps                                                   
    BulkCoolantTemp                                              
    rhof                                                         
    dpwxrate                                                     
    axialnode                                                    
    PelletRad                                                    
    FastFluxd                                                    
    FastFluenced                                                 
    totinner                                                     
    totcrl                                                       
    CladAveTemp                                                  
    PelAveTemp                                                   
    GapAveTemp                                                   
    PelSurfTemp                                                  
    PelCentTemp                                                  
    sigeff                                                       
    FuelSurfDispl                                                
    CladInSurDisp                                                
    CladInPermDef                                                
    sigy                                                         
    AxialNodLength                                               
    CladEffPlasStrain                                            
    RinterfacPress                                               
    FuelCladGap                                                  
    GapPress                                                     
    CoolantPress                                                 
    PlastStrnep1                                                 
    OldCladStrn                                                  
    OldFuelStrn                                                  
    OldGapPress                                                  
    OldCoolPress                                                 
    OldFuelDispl                                                 
    OldCladAvTemp                                                
    CreepStrain                                                  
    CreepStrain1                                                 
    CladDiamHot                                                  
    PrevCladEffPlasStrn                                          
    PrevFuelStrain                                               
    HotNodLength                                                 
    PermFuelDispl                                                
    BOSNodeburnup                                                
    EOSNodeburnup                                                
    StepNodeburnup                                               
    TotalHgap                                                    
    SolidHgap                                                    
    GasHgap                                                      
    RadHgap                                                      
    FastFlux                                                     
    FastFluence                                                  
    FuelPorosity                                                 
    FilmCoefficient                                              
    EstGapDeltaT                                                 
    BOSZrO2Thk                                                   
    EOSZrO2Thk                                                   
    ZrO2ThkNoAd                                                  
    FuelCondFactor                                               
    Relocation                                                   
    RinternalVolume                                              
    CladVolume                                                   
    CrackVolume                                                  
    RinterfacVolume                                              
    FuelVolume                                                   
    fden                                                         
    GapVolume                                                    
    PorosityVolume                                               
    SurfTempOxide                                                
    AnnulusVolume                                                
    gapplot                                                      
    PrevOldCoolPress                                             
    PrevOldGapPress                                              
    PrevOldCladAvTemp                                            
    PrevOldFuelDispl                                             
    PrevCreepStrain                                              
    CladIrradGrowStrn                                            
    UniformAxNodStrn                                             
    CladH2Concen                                                 
    ExcessH2Concen                                               
    PrevCladStrain                                               
    StartofStepH2Con                                             
    StartofStepPickupH2Con                                       
    EndofStepPickupH2Con                                         
    FuelTempRestruRad                                            
    OldHealedCrackRadius                                         
    StoredEnergy                                                 
    HealedCrackRadius                                            
    HotThermalGap                                                
    WorkArray1                                                   
    WorkArray2                                                   
    WorkArray3                                                   
    CladInSurfTemp                                               
    CladOutSurfTemp                                              
    Power                                                        
    gpthe                                                        
    gpth                                                         
    gpthpg                                                       
    qc                                                           
    totdef                                                       
    IgapGapIndex                                                 
    IgapIndexOld                                                 
    IgapIndexPrevOld                                             
    buin                                                         
    dci                                                          
    dco                                                          
    cdg                                                          
    thkcld                                                       
    thkgap                                                       
    de                                                           
    deltaz                                                       
    comp                                                         
    ctmax                                                        
    dp                                                           
    flux                                                         
    crudmult                                                     
    crdtt                                                        
    rdotwrt                                                      
    FDItave                                                      
    creapratearray                                               
    GapCond                                                      
    fuelexptot                                                   
    fuelswltot                                                   
    fuelcreeptot                                                 
    fueldentot                                                   
    fuelburntot                                                  
    cladcrptot                                                   
    gapHTC                                                       
    oxidelayer                                                   
    gapmech                                                      
    gapthrm                                                      
    fuelrelmod                                                   
    ifbarel                                                      
    zcool                                                        
    tcoolant                                                     
    pcoolant                                                     
    x                                                            
    qf                                                           
    xt                                                           
    cladt                                                        
    NodalMoles                                                   
    NodalGMLES                                                   
    rlcstrn                                                      
    rlcstrnold                                                   
    rc                                                           
    gadoln                                                       
    stold                                                        
    stnew                                                        
    deltimeold                                                   
    deltimenew                                                   
    sagold                                                       
    sagnew                                                       
    delsagold                                                    
    delsagnew                                                    
    delst                                                        
    colddef                                                      
    colddec                                                      
    qnode                                                        
    heprod                                                       
    he                                                           
    heold                                                        
    boron10                                                      
    enrch                                                        
    epsav                                                        
    wimsburnup                                                   
    oldwimsburnup                                                
    coolanttemp                                                  
    coolantpressure                                              
    storedearray                                                 
    cltemparray                                                  
    buarray                                                      
    strainarray                                                  
    straindiffarray                                              
    dpwxarray                                                    
    creaparray                                                   
    dumarray3                                                    
    formf                                                        
    ringvol                                                      
    coldringl                                                    
    porosold                                                     
    porosnew                                                     
    cladtarray                                                   
    rrev                                                         
    qaxnorm                                                      
    crad                                                         
    hrad                                                         
    rapow                                                        
    uo2exp                                                       
    dpw                                                          
    dpwpp                                                        
    dpw2                                                         
    dpwpp2                                                       
    densf                                                        
    densp                                                        
    hotringl                                                     
    tmpfuel                                                      
    gasavail1                                                    
    gasavail2                                                    
    angr                                                         
    ah2ogr                                                       
    fgmgp                                                        
    fmgr                                                         
    hemgp                                                        
    hmgr                                                         
    ang                                                          
    ah2og                                                        
    epp                                                          
    eppp                                                         
    eppsv                                                        
    eps                                                          
    feps                                                         
    reps                                                         
    repsv                                                        
    repsp                                                        
    rfeps                                                        
    rfepp                                                        
    rfpsv                                                        
    sig                                                          
    epp1                                                         
    sig1                                                         
    eps1                                                         
    ThermalStrain                                                
    RB_axial                                                     
    RB_rod                                                       
    prdct                                                        
    brnup3                                                       
    ansd                                                         
    ansr                                                         
    gp                                                           
    gpold                                                        
    rls                                                          
    rlsold                                                       
    brn                                                          
    brnrefab                                                     
    EOSNodeburnuprefab                                           
    brnold                                                       
    grnold                                                       
    frdenold                                                     
    gbtot                                                        
    tempkold                                                     
    pf                                                           
    decay                                                        
    half                                                         
    openp                                                        
    gb                                                           
    grs                                                          
    gg                                                           
    gbold                                                        
    ggold                                                        
    grsold                                                       
    g1                                                           
    g2                                                           
    g3                                                           
    g4                                                           
    g1old                                                        
    g2old                                                        
    g3old                                                        
    g4old                                                        
    brnup1                                                       
    conU235                                                      
    conU238                                                      
    conPu239                                                     
    conPu240                                                     
    conPu241                                                     
    conPu242                                                     
    coU235av                                                     
    coU238av                                                     
    coPu239av                                                    
    coPu240av                                                    
    coPu241av                                                    
    coPu242av                                                    
    enriU235                                                     
    enriU238                                                     
    enriPu239                                                    
    enriPu240                                                    
    enriPu241                                                    
    enriPu242                                                    
    pfU235                                                       
    pfU238                                                       
    pfPu239                                                      
    pfPu240                                                      
    pfPu241                                                      
    pfPu242                                                      
"""


a = set(a.split())
b = set(b.split())


print a-b
print b-a

#this % releas                                = this % r__releas                                
#this % dltgc                                 = this % r__dltgc                                 


