this % nthermex                                  => fraptran_rod(1) % Variables%nthermex                                                                            
this % modheat                                   => fraptran_rod(1) % Variables%modheat                                                                            
this % tref                                      => fraptran_rod(1) % Variables%tref                                                                            
this % htco                                      => fraptran_rod(1) % Variables%htco                                                                            
this % tem                                       => fraptran_rod(1) % Variables%tem                                                                            
this % pbh1                                      => fraptran_rod(1) % Variables%pbh1                                                                            
this % pbh2                                      => fraptran_rod(1) % Variables%pbh2                                                                            
this % hlqcl                                     => fraptran_rod(1) % Variables%hlqcl                                                                            
this % gadoln                                    => fraptran_rod(1) % Variables%gadoln                                                                            
this % cladtype                                  => fraptran_rod(1) % Oxidation%CladType                                                                            
this % protectiveoxide                           => fraptran_rod(1) % Oxidation%ProtectiveOxide                                                                            
this % nidoxide                                  => fraptran_rod(1) % Oxidation%nIDoxide                                                                            
this % explenumv                                 => fraptran_rod(1) % Oxidation%explenumv                                                                            
this % cexh2a                                    => fraptran_rod(1) % Oxidation%cexh2a                                                                            
this % explenumt                                 => fraptran_rod(1) % Oxidation%explenumt                                                                            
this % maxit                                     => fraptran_rod(1) % inpdat%maxit                                                                               
this % noiter                                    => fraptran_rod(1) % inpdat%noiter                                                                               
this % trise                                     => fraptran_rod(1) % modcom%trise                                                                               
this % jchf                                      => fraptran_rod(1) % bcdcom%jchf                                                                               
this % nbhtc                                     => fraptran_rod(1) % bcdcom%nbhtc                                                                               
this % jtr                                       => fraptran_rod(1) % bcdcom%jtr                                                                               
this % achn                                      => fraptran_rod(1) % bcdcom%achn                                                                               
this % dhe                                       => fraptran_rod(1) % bcdcom%dhe                                                                               
this % dhy                                       => fraptran_rod(1) % bcdcom%dhy                                                                               
this % radiation                                 => fraptran_rod(1) % bcdcom%Radiation                                                                               
this % indexfc2print                             => fraptran_rod(1) % scalr%IndexFC2Print                                                                                
this % mechan                                    => fraptran_rod(1) % scalr%mechan                                                                                
this % irupt                                     => fraptran_rod(1) % scalr%irupt                                                                                
this % irefine                                   => fraptran_rod(1) % scalr%irefine                                                                                
this % frcoef                                    => fraptran_rod(1) % scalr%frcoef                                                                                
this % ruptstrain                                => fraptran_rod(1) % scalr%ruptstrain                                                                                
this % refine                                    => fraptran_rod(1) % scalr%refine                                                                                
this % cfluxa                                    => fraptran_rod(1) % scalr%cfluxa                                                                                
this % coldw                                     => fraptran_rod(1) % scalr%coldw                                                                                
this % dishd                                     => fraptran_rod(1) % scalr%dishd                                                                                
this % dishv0                                    => fraptran_rod(1) % scalr%dishv0                                                                                
this % bup                                       => fraptran_rod(1) % scalr%bup                                                                                
this % frden                                     => fraptran_rod(1) % scalr%frden                                                                                
this % frpo2                                     => fraptran_rod(1) % scalr%frpo2                                                                                
this % dtss                                      => fraptran_rod(1) % scalr%dtss                                                                                
this % fpdcay                                    => fraptran_rod(1) % scalr%fpdcay                                                                                
this % pelh                                      => fraptran_rod(1) % scalr%pelh                                                                                
this % powop                                     => fraptran_rod(1) % scalr%powop                                                                                
this % prsacc                                    => fraptran_rod(1) % scalr%prsacc                                                                                
this % zvoid1                                    => fraptran_rod(1) % scalr%zvoid1                                                                                
this % rshd                                      => fraptran_rod(1) % scalr%rshd                                                                                
this % rvoid                                     => fraptran_rod(1) % scalr%rvoid                                                                                
this % tflux                                     => fraptran_rod(1) % scalr%tflux                                                                                
this % tgas0                                     => fraptran_rod(1) % scalr%tgas0                                                                                
this % timop                                     => fraptran_rod(1) % scalr%timop                                                                                
this % tmpac1                                    => fraptran_rod(1) % scalr%tmpac1                                                                                
this % tpowf                                     => fraptran_rod(1) % scalr%tpowf                                                                                
this % trest                                     => fraptran_rod(1) % scalr%trest                                                                                
this % zvoid2                                    => fraptran_rod(1) % scalr%zvoid2                                                                                
this % openporosityfraction                      => fraptran_rod(1) % scalr%OpenPorosityFraction                                                                                
this % spl                                       => fraptran_rod(1) % scalr%spl                                                                                
this % scd                                       => fraptran_rod(1) % scalr%scd                                                                                
this % swd                                       => fraptran_rod(1) % scalr%swd                                                                                
this % relocmodel                                => fraptran_rod(1) % scalr%relocmodel                                                                                
this % vplen                                     => fraptran_rod(1) % scalr%vplen                                                                                
this % gappr0                                    => fraptran_rod(1) % scalr%gappr0                                                                                
this % scd                                       => fraptran_rod(1) % scalr%scd                                                                                
this % spl                                       => fraptran_rod(1) % scalr%spl                                                                                
this % swd                                       => fraptran_rod(1) % scalr%swd                                                                                
this % roughf                                    => fraptran_rod(1) % presb%roughf                                                                                
this % roughc                                    => fraptran_rod(1) % presb%roughc                                                                                
this % numaxprofiles                             => fraptran_rod(1) % powrd%NumAxProfiles                                                                                
this % profilestarttime                          => fraptran_rod(1) % powrd%ProfileStartTime                                                                                
this % rodavepower                               => fraptran_rod(1) % powrd%RodAvePower                                                                                
this % axpowprofile                              => fraptran_rod(1) % powrd%AxPowProfile                                                                                
this % pazp                                      => fraptran_rod(1) % powrd%pazp                                                                                
this % ncmesh                                    => fraptran_rod(1) % numcom%ncmesh                                                                               
this % nfmesh                                    => fraptran_rod(1) % numcom%nfmesh                                                                               
this % cmesh                                     => fraptran_rod(1) % numcom%cmesh                                                                               
this % fmesh                                     => fraptran_rod(1) % numcom%fmesh                                                                               
this % zelev                                     => fraptran_rod(1) % numcom%zelev                                                                               
this % rshrd                                     => fraptran_rod(1) % htcb%rshrd                                                                                 
this % bowthr                                    => fraptran_rod(1) % htcb%bowthr                                                                                 
this % epsht1                                    => fraptran_rod(1) % HeatConduction%epsht1                                                                       
this % transwell                                 => fraptran_rod(1) % FGR%TranSwell                                                                                  
this % presfgr                                   => fraptran_rod(1) % FGR%presfgr                                                                                  
this % gasmoles0                                 => fraptran_rod(1) % FGR%GasMoles0                                                                                  
this % relfraca                                  => fraptran_rod(1) % FGR%relfraca                                                                                  
this % fuelgasswell                              => fraptran_rod(1) % FGR%FuelGasSwell                                                                                  
this % pdrato                                    => fraptran_rod(1) % bloon%pdrato                                                                                
this % rnbnt                                     => fraptran_rod(1) % bloon%rnbnt                                                                                
this % totnb                                     => fraptran_rod(1) % bloon%totnb                                                                                
this % oxideid                                   => fraptran_rod(1) % dyna%oxideid                                                                                 
this % oxideod                                   => fraptran_rod(1) % dyna%oxideod                                                                                 
this % extentofbow                               => fraptran_rod(1) % dyna%ExtentOfBow                                                                                 
this % techf                                     => fraptran_rod(1) % dyna%techf                                                                                 
this % tschf                                     => fraptran_rod(1) % dyna%tschf                                                                                 
this % nodchf                                    => fraptran_rod(1) % dyna%nodchf                                                                                 
this % nce                                       => fraptran_rod(1) % dyna%nce                                                                                 
this % prestmp                                   => fraptran_rod(1) % collct%prestmp                                                                               
this % gasphs                                    => fraptran_rod(1) % collct%gasphs                                                                               
this % gasths                                    => fraptran_rod(1) % collct%gasths                                                                               
this % gbse                                      => fraptran_rod(1) % collct%gbse                                                                               
this % naz                                       => fraptran_rod(1) % excb%naz                                                                                 
this % ncolbp                                    => fraptran_rod(1) % excb%ncolbp                                                                                 
this % dofset                                    => fraptran_rod(1) % excb%dofset                                                                                 
this % dofang                                    => fraptran_rod(1) % excb%dofang                                                                                 
this % pitch                                     => fraptran_rod(1) % excb%pitch                                                                                 
this % fgrns                                     => fraptran_rod(1) % excb%fgrns                                                                                 
this % fotmtl                                    => fraptran_rod(1) % excb%fotmtl                                                                                 
this % tsntrk                                    => fraptran_rod(1) % excb%tsntrk                                                                                 
this % volbp                                     => fraptran_rod(1) % excb%volbp                                                                                 
this % splbp                                     => fraptran_rod(1) % excb%splbp                                                                                 
this % coldbp                                    => fraptran_rod(1) % excb%coldbp                                                                                 
this % spdbp                                     => fraptran_rod(1) % excb%spdbp                                                                                 
this % cldwdc                                    => fraptran_rod(1) % excb%cldwdc                                                                                 
this % dtpoa                                     => fraptran_rod(1) % excb%dtpoa                                                                                 
this % htclev                                    => fraptran_rod(1) % Coolant%htclev                                                                              
this % gbh                                       => fraptran_rod(1) % Coolant%gbh                                                                              
this % hbh                                       => fraptran_rod(1) % Coolant%hbh                                                                              
this % hinta                                     => fraptran_rod(1) % Coolant%hinta                                                                              
this % hupta                                     => fraptran_rod(1) % Coolant%hupta                                                                              
this % htca                                      => fraptran_rod(1) % Coolant%htca                                                                              
this % tblka                                     => fraptran_rod(1) % Coolant%tblka                                                                              
this % hrad                                      => fraptran_rod(1) % Coolant%hrad                                                                              
this % refdtm                                    => fraptran_rod(1) % Coolant%refdtm                                                                              
this % hydiam                                    => fraptran_rod(1) % Coolant%hydiam                                                                              
this % flxsec                                    => fraptran_rod(1) % Coolant%flxsec                                                                              
this % fltgap                                    => fraptran_rod(1) % Coolant%fltgap                                                                              
this % zad                                       => fraptran_rod(1) % Coolant%zad                                                                              
this % zs                                        => fraptran_rod(1) % Coolant%zs                                                                              
this % prestm                                    => fraptran_rod(1) % Coolant%prestm                                                                              
this % temptm                                    => fraptran_rod(1) % Coolant%temptm                                                                              
this % fldrat                                    => fraptran_rod(1) % Coolant%fldrat                                                                              
this % fuelpeldiam                               => fraptran_rod(1) % intcom%FuelPelDiam                                                                               
this % eppinp                                    => fraptran_rod(1) % intcom%eppinp                                                                               
this % radpel                                    => fraptran_rod(1) % intcom%radpel                                                                               
this % dtplta                                    => fraptran_rod(1) % iocom%dtplta                                                                                
this % naxn                                      => fraptran_rod(1) % resti%naxn                                                                                
this % nchn                                      => fraptran_rod(1) % resti%nchn                                                                                
this % ngastmp                                   => fraptran_rod(1) % resti%ngastmp                                                                                
this % istoicgrad                                => fraptran_rod(1) % resti%iStoicGrad                                                                                
this % ncs                                       => fraptran_rod(1) % resti%ncs                                                                                
this % dtmaxa                                    => fraptran_rod(1) % resti%dtmaxa                                                                                
this % azpang                                    => fraptran_rod(1) % resti%azpang                                                                                
this % fluxz                                     => fraptran_rod(1) % resti%fluxz                                                                                
this % ncards                                    => fraptran_rod(1) % thcntl%ncards                                                                               
this % nrestart                                  => fraptran_rod(1) % thcntl%NRestart                                                                               
this % namerf                                    => namerf                                                                     
this % reflood                                   => reflood                                                                     
this % reflo                                     => reflo                                                                     
this % deformation                               => deformation                                                                     
this % inp                                       => inp                                                                     
this % inst                                      => inst                                                                     
this % metal                                     => metal                                                                     
this % cathca                                    => cathca                                                                     
this % lowpl                                     => lowpl                                                                     
this % rtheta                                    => rtheta                                                                     
this % geom                                      => geom                                                                     
this % nvol1                                     => nvol1                                                                     
this % gasflo                                    => gasflo                                                                     
this % noball                                    => noball                                                                     
this % prescri                                   => prescri                                                                     
this % azang                                     => azang                                                                     
this % ph                                        => ph                                                                     
this % idoxid                                    => idoxid                                                                     
this % tape1                                     => tape1                                                                     
this % massfl                                    => massfl                                                                     
this % odoxid                                    => odoxid                                                                     
this % unitin                                    => unitin                                                                     
this % geometry                                  => geometry                                                                     
this % filmbo                                    => filmbo                                                                     
this % chf                                       => chf                                                                     
this % coreav                                    => coreav                                                                     
this % bheat                                     => bheat                                                                     
this % mheat                                     => mheat                                                                     
this % indexgrainbndsep                          => indexgrainbndsep                                                                     
this % cenvoi                                    => cenvoi                                                                     
this % grass                                     => grass                                                                     
this % baker                                     => baker                                                                     
this % geomet                                    => geomet                                                                     
this % soltyp                                    => soltyp                                                                     
this % profile                                   => profile                                                                     
this % nsym                                      => nsym                                                                     
this % unitout                                   => unitout                                                                     
this % tape2                                     => tape2                                                                     
this % nvol2                                     => nvol2                                                                     
this % zone                                      => zone                                                                     
this % upppl                                     => upppl                                                                     
this % jfb                                       => jfb                                                                     
this % nucbo                                     => nucbo                                                                     
this % plenumtemp                                => plenumtemp                                                                     
this % coldwa                                    => coldwa                                                                     
this % axpow                                     => axpow                                                                     
this % bowing                                    => bowing                                                                     
this % spefbz                                    => spefbz                                                                     
this % nbundl                                    => nbundl                                                                     
this % refloodtime                               => refloodtime                                                                     
this % collaps                                   => collaps                                                                     
this % frapt4                                    => frapt4                                                                     
this % buoxide                                   => buoxide                                                                     
this % cladpower                                 => cladpower                                                                     
this % inlet                                     => inlet                                                                     
this % roddiameter                               => roddiameter                                                                     
this % gapthk                                    => gapthk                                                                     
this % radiat                                    => radiat                                                                     
this % ffch                                      => ffch                                                                     
this % fpowr                                     => fpowr                                                                     
this % doffst                                    => doffst                                                                     
this % rodlength                                 => rodlength                                                                     
this % ruptur                                    => ruptur                                                                     
this % emptm                                     => emptm                                                                     
this % fltgap2                                   => fltgap2                                                                     
this % gsms                                      => gsms                                                                     
this % pressu                                    => pressu                                                                     
this % internal                                  => internal                                                                     
this % pow                                       => pow                                                                     
this % press                                     => press                                                                     
this % radtemp                                   => radtemp                                                                     
this % fuelrad                                   => fuelrad                                                                     
this % gfrac                                     => gfrac                                                                     
this % res                                       => res                                                                     
this % pressure                                  => pressure                                                                     
this % temp                                      => temp                                                                     
this % butemp                                    => butemp                                                                     
this % coolant                                   => coolant                                                                     
this % pl                                        => pl                                                                     
this % liquid                                    => liquid                                                                     
