call clone( this % r__emflag , emflag )
call clone( this % r__ifstor , ifstor )
call clone( this % r__ichf , ichf )
call clone( this % r__nswpm , nswpm )
call clone( this % r__tem , tem )
call clone( this % r__imaterials , imaterials )
call clone( this % r__modfal , modfal )
call clone( this % r__idumr1 , idumr1 )
call clone( this % r__ih , ih )
call clone( this % r__iffrp , iffrp )
call clone( this % r__ihtreg , ihtreg )
call clone( this % r__indxjk , indxjk )
call clone( this % r__ibnopt , ibnopt )
call clone( this % r__ruptfailindex , ruptfailindex )
call clone( this % r__nm , nm )
call clone( this % r__ies , ies )
call clone( this % r__nopt , nopt )
call clone( this % r__indexpcmionce , indexpcmionce )
call clone( this % r__cladcollapseindex , cladcollapseindex )
call clone( this % r__rodfailindex , rodfailindex )
call clone( this % r__gapindex , gapindex )
call clone( this % r__irest2 , irest2 )
call clone( this % r__imatflag , imatflag )
call clone( this % r__oldgapindex , oldgapindex )
call clone( this % r__htco , htco )
call clone( this % r__indextempconverg , indextempconverg )
call clone( this % r__bosgapindex , bosgapindex )
call clone( this % r__idatapairs , idatapairs )
call clone( this % r__ncs , ncs )
call clone( this % r__nvprs , nvprs )
call clone( this % r__npprs , npprs )
call clone( this % r__irest3 , irest3 )
call clone( this % r__bosgapindex0 , bosgapindex0 )
call clone( this % r__ntprs , ntprs )
call clone( this % r__ihdata , ihdata )
call clone( this % r__imatflag1 , imatflag1 )
call clone( this % r__cladcollindx0 , cladcollindx0 )
call clone( this % r__nunopt , nunopt )
call clone( this % r__nhprs , nhprs )
call clone( this % r__nodesintertemp , nodesintertemp )
call clone( this % r__ngastmp , ngastmp )
call clone( this % r__ndchfi , ndchfi )
call clone( this % r__iheattablen , iheattablen )
call clone( this % r__indexpcmi , indexpcmi )
call clone( this % r__numazmuthnod , numazmuthnod )
call clone( this % r__roi , roi )
call clone( this % r__alphathk11 , alphathk11 )
call clone( this % r__tbulk_v , tbulk_v )
call clone( this % r__cladenrgperl , cladenrgperl )
call clone( this % r__efffastflustrencoef , efffastflustrencoef )
call clone( this % r__scd , scd )
call clone( this % r__watrmetlenrgy , watrmetlenrgy )
call clone( this % r__coolpress , coolpress )
call clone( this % r__dtplta , dtplta )
call clone( this % r__oxconcenaio , oxconcenaio )
call clone( this % r__apln , apln )
call clone( this % r__oxygenuptake , oxygenuptake )
call clone( this % r__thermalconductadv , thermalconductadv )
call clone( this % r__ascal2 , ascal2 )
call clone( this % r__gasax , gasax )
call clone( this % r__profilestarttime , profilestarttime )
call clone( this % r__ascal1 , ascal1 )
call clone( this % r__htflxfac , htflxfac )
call clone( this % r__htclev , htclev )
call clone( this % r__tbulk_l , tbulk_l )
call clone( this % r__prop , prop )
call clone( this % r__oxconcenado , oxconcenado )
call clone( this % r__flwblk , flwblk )
call clone( this % r__tempfc , tempfc )
call clone( this % r__oxconcenadi , oxconcenadi )
call clone( this % r__rinterfacgap , rinterfacgap )
call clone( this % r__stressatinststrain , stressatinststrain )
call clone( this % r__rinterfacprs0 , rinterfacprs0 )
call clone( this % r__ts , ts )
call clone( this % r__tp , tp )
call clone( this % r__claddingpower , claddingpower )
call clone( this % r__oldcoolprs0 , oldcoolprs0 )
call clone( this % r__voidvolumeratio , voidvolumeratio )
call clone( this % r__techf , techf )
call clone( this % r__eosoxidethick , eosoxidethick )
call clone( this % r__cexh2a , cexh2a )
call clone( this % r__pelraddeviat , pelraddeviat )
call clone( this % r__coolenthalpy0 , coolenthalpy0 )
call clone( this % r__epstrain1old , epstrain1old )
call clone( this % r__azpang , azpang )
call clone( this % r__coolmassflx , coolmassflx )
call clone( this % r__hmaxinitial , hmaxinitial )
call clone( this % r__betathickness , betathickness )
call clone( this % r__oxstalphathkremain , oxstalphathkremain )
call clone( this % r__powave , powave )
call clone( this % r__axburnup , axburnup )
call clone( this % r__apln0 , apln0 )
call clone( this % r__alphathk1 , alphathk1 )
call clone( this % r__amatpc , amatpc )
call clone( this % r__fdial , fdial )
call clone( this % r__vrlfrp , vrlfrp )
call clone( this % r__rinterfacprs , rinterfacprs )
call clone( this % r__energyperl , energyperl )
call clone( this % r__dvdt , dvdt )
call clone( this % r__effcoldwkstrnhardexp , effcoldwkstrnhardexp )
call clone( this % r__gapthick0 , gapthick0 )
call clone( this % r__oxconcenaci , oxconcenaci )
call clone( this % r__gbse , gbse )
call clone( this % r__fmgp , fmgp )
call clone( this % r__oldcoolprs , oldcoolprs )
call clone( this % r__sshgap , sshgap )
call clone( this % r__workspacetcmx , workspacetcmx )
call clone( this % r__sedpnnlold , sedpnnlold )
call clone( this % r__heatflux , heatflux )
call clone( this % r__boundarycondition , boundarycondition )
call clone( this % r__gadoln , gadoln )
call clone( this % r__oxconcenaco , oxconcenaco )
call clone( this % r__gfrac , gfrac )
call clone( this % r__radialpower , radialpower )
call clone( this % r__stressaxialold , stressaxialold )
call clone( this % r__surfhtflux , surfhtflux )
call clone( this % r__oldcldplasstrn , oldcldplasstrn )
call clone( this % r__gbh , gbh )
call clone( this % r__prevtemp , prevtemp )
call clone( this % r__workspacereloc , workspacereloc )
call clone( this % r__pelletrad0 , pelletrad0 )
call clone( this % r__rmrlp , rmrlp )
call clone( this % r__hz2 , hz2 )
call clone( this % r__fastflux , fastflux )
call clone( this % r__bbht1 , bbht1 )
call clone( this % r__pbh , pbh )
call clone( this % r__gaptemp , gaptemp )
call clone( this % r__arest1 , arest1 )
call clone( this % r__dvdt0 , dvdt0 )
call clone( this % r__drdfrp , drdfrp )
call clone( this % r__oldgasprs , oldgasprs )
call clone( this % r__fuelgasswell , fuelgasswell )
call clone( this % r__oxuptakeid2 , oxuptakeid2 )
call clone( this % r__stresshoopold , stresshoopold )
call clone( this % r__effcoldwkstrencoef , effcoldwkstrencoef )
call clone( this % r__oxconcenago , oxconcenago )
call clone( this % r__rodod0 , rodod0 )
call clone( this % r__dtmaxa , dtmaxa )
call clone( this % r__pelletrad , pelletrad )
call clone( this % r__edint , edint )
call clone( this % r__alphathk2 , alphathk2 )
call clone( this % r__axialpowr , axialpowr )
call clone( this % r__pelsrfdispl , pelsrfdispl )
call clone( this % r__hgapav , hgapav )
call clone( this % r__tmelt , tmelt )
call clone( this % r__temptm , temptm )
call clone( this % r__enthl , enthl )
call clone( this % r__flthit , flthit )
call clone( this % r__bpln , bpln )
call clone( this % r__cladmaxt , cladmaxt )
call clone( this % r__qaxzq , qaxzq )
call clone( this % r__oxconcenaii , oxconcenaii )
call clone( this % r__vfrad1 , vfrad1 )
call clone( this % r__vfrad3 , vfrad3 )
call clone( this % r__vfrad2 , vfrad2 )
call clone( this % r__oxconcenafo , oxconcenafo )
call clone( this % r__tend , tend )
call clone( this % r__aexcb , aexcb )
call clone( this % r__sedepri , sedepri )
call clone( this % r__alphathk22 , alphathk22 )
call clone( this % r__oxithk1 , oxithk1 )
call clone( this % r__bufrp , bufrp )
call clone( this % r__hz1 , hz1 )
call clone( this % r__swelldispl , swelldispl )
call clone( this % r__oxithk2 , oxithk2 )
call clone( this % r__tshrda , tshrda )
call clone( this % r__vs0 , vs0 )
call clone( this % r__acoold , acoold )
call clone( this % r__hgpfrp , hgpfrp )
call clone( this % r__pbh2 , pbh2 )
call clone( this % r__hlqcl , hlqcl )
call clone( this % r__finaltemp , finaltemp )
call clone( this % r__techfi , techfi )
call clone( this % r__pbh1 , pbh1 )
call clone( this % r__aflcht , aflcht )
call clone( this % r__bu , bu )
call clone( this % r__ecr , ecr )
call clone( this % r__vreloc0 , vreloc0 )
call clone( this % r__epstrain2old , epstrain2old )
call clone( this % r__hlqclp , hlqclp )
call clone( this % r__bpln0 , bpln0 )
call clone( this % r__pz2 , pz2 )
call clone( this % r__cesiumcontent , cesiumcontent )
call clone( this % r__z1 , z1 )
call clone( this % r__z2 , z2 )
call clone( this % r__faxzq , faxzq )
call clone( this % r__fluxz , fluxz )
call clone( this % r__gapthick , gapthick )
call clone( this % r__hbh , hbh )
call clone( this % r__oldepeff , oldepeff )
call clone( this % r__oldeffstrainpnnl , oldeffstrainpnnl )
call clone( this % r__cladavetemp , cladavetemp )
call clone( this % r__nodchf , nodchf )
call clone( this % r__oldgasprs0 , oldgasprs0 )
call clone( this % r__aasth , aasth )
call clone( this % r__aprntb , aprntb )
call clone( this % r__volopenpor , volopenpor )
call clone( this % r__farbal , farbal )
call clone( this % r__extentofbow , extentofbow )
call clone( this % r__oldcldaxstrn0 , oldcldaxstrn0 )
call clone( this % r__sdfar , sdfar )
call clone( this % r__ablona , ablona )
call clone( this % r__cladeffstress , cladeffstress )
call clone( this % r__rodavepower , rodavepower )
call clone( this % r__gasmolesax0 , gasmolesax0 )
call clone( this % r__cooldensity0 , cooldensity0 )
call clone( this % r__ascal3 , ascal3 )
call clone( this % r__arrayf , arrayf )
call clone( this % r__oldpeldis , oldpeldis )
call clone( this % r__edotfz , edotfz )
call clone( this % r__workspacerco , workspacerco )
call clone( this % r__workspaceep1 , workspaceep1 )
call clone( this % r__cldpermstrn , cldpermstrn )
call clone( this % r__hydrogencontent , hydrogencontent )
call clone( this % r__gasfraction , gasfraction )
call clone( this % r__tz2 , tz2 )
call clone( this % r__workspacerci , workspacerci )
call clone( this % r__hfusn , hfusn )
call clone( this % r__prcntsatbeta , prcntsatbeta )
call clone( this % r__qpln0 , qpln0 )
call clone( this % r__oxconcenaai , oxconcenaai )
call clone( this % r__oldpeldis0 , oldpeldis0 )
call clone( this % r__flowg , flowg )
call clone( this % r__oxconcenaao , oxconcenaao )
call clone( this % r__iodinecontent , iodinecontent )
call clone( this % r__oldfuelaxstrn , oldfuelaxstrn )
call clone( this % r__terfacepres , terfacepres )
call clone( this % r__axnodelevat , axnodelevat )
call clone( this % r__cladsurft , cladsurft )
call clone( this % r__oxconcenabi , oxconcenabi )
call clone( this % r__cladyieldstress , cladyieldstress )
call clone( this % r__oxideid , oxideid )
call clone( this % r__swd , swd )
call clone( this % r__tschfi , tschfi )
call clone( this % r__strainrateterm , strainrateterm )
call clone( this % r__hsolold , hsolold )
call clone( this % r__gasmolesax , gasmolesax )
call clone( this % r__hfxsum , hfxsum )
call clone( this % r__pclrlp , pclrlp )
call clone( this % r__elevatthermhydr , elevatthermhydr )
call clone( this % r__timeofgbsep , timeofgbsep )
call clone( this % r__effstrain0 , effstrain0 )
call clone( this % r__oxideod , oxideod )
call clone( this % r__coolqual , coolqual )
call clone( this % r__crithtflux , crithtflux )
call clone( this % r__axialnodlen , axialnodlen )
call clone( this % r__oxconcenahi , oxconcenahi )
call clone( this % r__effstrain , effstrain )
call clone( this % r__filmcoeffav , filmcoeffav )
call clone( this % r__workspacepint , workspacepint )
call clone( this % r__sedpnnl , sedpnnl )
call clone( this % r__heatflux0 , heatflux0 )
call clone( this % r__rmassflux , rmassflux )
call clone( this % r__qmaxmelt , qmaxmelt )
call clone( this % r__cldpermhoopstrn , cldpermhoopstrn )
call clone( this % r__stressradialold , stressradialold )
call clone( this % r__fuelsrfstrrat , fuelsrfstrrat )
call clone( this % r__cladeffstressold , cladeffstressold )
call clone( this % r__oxconcenaeo , oxconcenaeo )
call clone( this % r__cracktemp , cracktemp )
call clone( this % r__thermalconductivity , thermalconductivity )
call clone( this % r__fldrat , fldrat )
call clone( this % r__qmaxmeltp1 , qmaxmeltp1 )
call clone( this % r__pgpfrp , pgpfrp )
call clone( this % r__radpel , radpel )
call clone( this % r__oxconcenaei , oxconcenaei )
call clone( this % r__coefm , coefm )
call clone( this % r__coefn , coefn )
call clone( this % r__coefk , coefk )
call clone( this % r__openportemp , openportemp )
call clone( this % r__rodod , rodod )
call clone( this % r__fuelsrfstrrat0 , fuelsrfstrrat0 )
call clone( this % r__deltox , deltox )
call clone( this % r__vreloc , vreloc )
call clone( this % r__cldpermaxstrn , cldpermaxstrn )
call clone( this % r__fmesh , fmesh )
call clone( this % r__pelprm , pelprm )
call clone( this % r__workspacegap , workspacegap )
call clone( this % r__cmesh , cmesh )
call clone( this % r__gsmol0 , gsmol0 )
call clone( this % r__openporvol , openporvol )
call clone( this % r__bowrat , bowrat )
call clone( this % r__gappr0 , gappr0 )
call clone( this % r__vplen , vplen )
call clone( this % r__arraye , arraye )
call clone( this % r__openporosity , openporosity )
call clone( this % r__centvoidvol , centvoidvol )
call clone( this % r__bulkcooltemp , bulkcooltemp )
call clone( this % r__crackvolume , crackvolume )
call clone( this % r__butemp , butemp )
call clone( this % r__hydrostatpress , hydrostatpress )
call clone( this % r__gasphs , gasphs )
call clone( this % r__hlqcl1 , hlqcl1 )
call clone( this % r__dtdkta , dtdkta )
call clone( this % r__gaspress0 , gaspress0 )
call clone( this % r__pelsrfstrn0 , pelsrfstrn0 )
call clone( this % r__workspaceurc , workspaceurc )
call clone( this % r__hupta , hupta )
call clone( this % r__spl , spl )
call clone( this % r__oxuptakeid1 , oxuptakeid1 )
call clone( this % r__fuelsurft , fuelsurft )
call clone( this % r__aaht1 , aaht1 )
call clone( this % r__oxconcenaho , oxconcenaho )
call clone( this % r__eppinp , eppinp )
call clone( this % r__ispace , ispace )
call clone( this % r__pswll0 , pswll0 )
call clone( this % r__bosoxidethick , bosoxidethick )
call clone( this % r__oxconcenagi , oxconcenagi )
call clone( this % r__dishvperl , dishvperl )
call clone( this % r__qpln , qpln )
call clone( this % r__sedepriold , sedepriold )
call clone( this % r__radialbound , radialbound )
call clone( this % r__explenumt , explenumt )
call clone( this % r__crackwidth , crackwidth )
call clone( this % r__edotfz0 , edotfz0 )
call clone( this % r__coolenthalpy , coolenthalpy )
call clone( this % r__dtpoa , dtpoa )
call clone( this % r__oldcladt , oldcladt )
call clone( this % r__vsn , vsn )
call clone( this % r__ureloc , ureloc )
call clone( this % r__afrap , afrap )
call clone( this % r__efffastflustrnhardexp , efffastflustrnhardexp )
call clone( this % r__epstrain3old , epstrain3old )
call clone( this % r__gaspress , gaspress )
call clone( this % r__radpowprofile , radpowprofile )
call clone( this % r__relfraca , relfraca )
call clone( this % r__effstrainpnnl , effstrainpnnl )
call clone( this % r__tz1 , tz1 )
call clone( this % r__emodulus , emodulus )
call clone( this % r__einstabilstrain , einstabilstrain )
call clone( this % r__tschf , tschf )
call clone( this % r__elvrad , elvrad )
call clone( this % r__oldcladt0 , oldcladt0 )
call clone( this % r__oldfuelaxstrn0 , oldfuelaxstrn0 )
call clone( this % r__ansr , ansr )
call clone( this % r__gfint , gfint )
call clone( this % r__pz1 , pz1 )
call clone( this % r__axialpowr0 , axialpowr0 )
call clone( this % r__oxygenconcenave , oxygenconcenave )
call clone( this % r__a1 , a1 )
call clone( this % r__zfarbl , zfarbl )
call clone( this % r__fuelcentert , fuelcentert )
call clone( this % r__workspacegapi , workspacegapi )
call clone( this % r__oldeps , oldeps )
call clone( this % r__hinta , hinta )
call clone( this % r__oxstalphathknearfuel , oxstalphathknearfuel )
call clone( this % r__oxconcenabo , oxconcenabo )
call clone( this % r__avedishtemp , avedishtemp )
call clone( this % r__gz2 , gz2 )
call clone( this % r__gz1 , gz1 )
call clone( this % r__oldcldaxstrn , oldcldaxstrn )
call clone( this % r__cooldensity , cooldensity )
call clone( this % r__prestm , prestm )
call clone( this % r__cldpermstrn0 , cldpermstrn0 )
call clone( this % r__elevatfrap , elevatfrap )
call clone( this % r__pinput , pinput )
call clone( this % r__htc_v , htc_v )
call clone( this % r__potput , potput )
call clone( this % r__oxconcenafi , oxconcenafi )
call clone( this % r__acolct , acolct )
call clone( this % r__zelev , zelev )
call clone( this % r__gadolin , gadolin )
call clone( this % r__htc_l , htc_l )
call clone( this % r__oxipowergen , oxipowergen )
call clone( this % r__icglob , icglob )
call clone( this % r__nrc , nrc )
call clone( this % r__iokold , iokold )
call clone( this % r__iok , iok )
call clone( this % r__gasavail1 , gasavail1 )
call clone( this % r__tmprlp , tmprlp )
call clone( this % r__gasavail2 , gasavail2 )
call clone( this % r__volumeweightr , volumeweightr )
call clone( this % r__enrgymeltz , enrgymeltz )
call clone( this % r__acond , acond )
call clone( this % r__cldthermstrn , cldthermstrn )
call clone( this % r__frapcontemp , frapcontemp )
call clone( this % r__baln2twall , baln2twall )
call clone( this % r__qcold , qcold )
call clone( this % r__fuelresidstrn , fuelresidstrn )
call clone( this % r__tplbt1 , tplbt1 )
call clone( this % r__previteratetemp , previteratetemp )
call clone( this % r__buradv , buradv )
call clone( this % r__rhocp0 , rhocp0 )
call clone( this % r__tblka , tblka )
call clone( this % r__burad , burad )
call clone( this % r__htca , htca )
call clone( this % r__enrgymelt , enrgymelt )
call clone( this % r__cldstrnrat , cldstrnrat )
call clone( this % r__deformedradiusofmesh , deformedradiusofmesh )
call clone( this % r__bosrad , bosrad )
call clone( this % r__pelsrfstrn , pelsrfstrn )
call clone( this % r__eosrad , eosrad )
call clone( this % r__radsrc , radsrc )
call clone( this % r__cldplasstrn0 , cldplasstrn0 )
call clone( this % r__cldstress , cldstress )
call clone( this % r__rhocp , rhocp )
call clone( this % r__radialboundo , radialboundo )
call clone( this % r__volumeweightl , volumeweightl )
call clone( this % r__axpowprofile , axpowprofile )
call clone( this % r__enrgymeltzp1 , enrgymeltzp1 )
call clone( this % r__pazp , pazp )
call clone( this % r__tpln , tpln )
call clone( this % r__radpow , radpow )
call clone( this % r__areaweight , areaweight )
call clone( this % r__eostemp , eostemp )
call clone( this % r__pchn , pchn )
call clone( this % r__trad2 , trad2 )
call clone( this % r__trad3 , trad3 )
call clone( this % r__trad1 , trad1 )
call clone( this % r__gasths , gasths )
call clone( this % r__fuelrad , fuelrad )
call clone( this % r__cldresidstrn0 , cldresidstrn0 )
call clone( this % r__dktouts , dktouts )
call clone( this % r__cldstrnrat0 , cldstrnrat0 )
call clone( this % r__cldplasstrn , cldplasstrn )
call clone( this % r__bufrad , bufrad )
call clone( this % r__radsrco , radsrco )
call clone( this % r__cldresidstrn , cldresidstrn )
call clone( this % r__radtemp , radtemp )
call clone( this % r__workspaceepp1 , workspaceepp1 )
call clone( this % r__fuelresidstrn0 , fuelresidstrn0 )
call clone( this % r__cldelstrn , cldelstrn )
call clone( this % r__enrgymeltp1 , enrgymeltp1 )
call clone( this % r__tplbot , tplbot )
call clone( this % r__bostemp , bostemp )
call clone( this % r__cldstrn , cldstrn )
call clone( this % r__grsv , grsv )
call clone( this % r__tplna , tplna )

!        ALLOCATE (this % r__cexh2a(1:naxialnodes) )
!        ALLOCATE (this % r__deltox(1:naxialnodes) )
!        ALLOCATE (this % r__explenumt(1:2*ntimesteps) )
!        ALLOCATE (this % r__tEnd(1:ntimepairs) )
!        ALLOCATE (this % r__gfInt(1:ntimepairs) )
!        ALLOCATE (this % r__edInt(1:ntimepairs) )
!        ALLOCATE (this % r__CladdingPower(1:naxialnodes) )
!        ALLOCATE (this % r__RadPowProfile(1:size1) )
!        ALLOCATE (this % r__radtemp(1:naxialnodes,1:ntimesteps) )
!        ALLOCATE (this % r__fuelrad(1:naxialnodes,1:ntimesteps) )
!        ALLOCATE (this % r__ndchfi(1:naxialnodes) )
!        ALLOCATE (this % r__bowrat(1:naxialnodes) )
!        ALLOCATE (this % r__techfi(1:naxialnodes) )
!        ALLOCATE (this % r__tschfi(1:naxialnodes) )
!        ALLOCATE (this % r__hlqcl1(1:ntimesteps) )
!        ALLOCATE (this % r__fdial(1:30) )
!        ALLOCATE (this % r__ibnopt(1:33) )
!        ALLOCATE (this % r__nopt(1:8) )
!        ALLOCATE (this % r__nunopt(1:14) )
!        ALLOCATE (this % r__idumr1(1:7) )
!        ALLOCATE (this % r__vplen(1) )
!        ALLOCATE (this % r__apln0(1) )
!        ALLOCATE (this % r__bpln0(1) )
!        ALLOCATE (this % r__vsn(1) )
!        ALLOCATE (this % r__bu(1) )
!        ALLOCATE (this % r__gappr0(1) )
!        ALLOCATE (this % r__scd(1) )
!        ALLOCATE (this % r__spl(1) )
!        ALLOCATE (this % r__swd(1) )
!        ALLOCATE (this % r__qpln(1) )
!        ALLOCATE (this % r__qpln0(1) )
!        ALLOCATE (this % r__flwblk(1) )
!        ALLOCATE (this % r__tp(1) )
!        ALLOCATE (this % r__powave(1) )
!        ALLOCATE (this % r__dvdt(1) )
!        ALLOCATE (this % r__apln(1) )
!        ALLOCATE (this % r__bpln(1) )
!        ALLOCATE (this % r__dvdt0(1) )
!        ALLOCATE (this % r__hfusn(1:3) )
!        ALLOCATE (this % r__tmelt(1:3) )
!        ALLOCATE (this % r__ascal3(1:25) )
!        ALLOCATE (this % r__ascal2(1:57) )
!        ALLOCATE (this % r__ascal1(1:29) )
!        ALLOCATE (this % r__gadolin(1:naxialnodes) )
!        ALLOCATE (this % r__pchn(1,1) )
!        ALLOCATE (this % r__burad(1:naxialnodes,1:nradialnodes) )
!        ALLOCATE (this % r__radpow(1:naxialnodes,1:nradialnodes) )
!        ALLOCATE (this % r__radsrc(1:naxialnodes,1:nradialnodes) )
!        ALLOCATE (this % r__radsrco(1:naxialnodes,1:nradialnodes) )
!        ALLOCATE (this % r__butemp(1:naxialnodes*nradialnodes) )
!        ALLOCATE (this % r__aprntb(1) )
!        ALLOCATE (this % r__ies(1) )
!        ALLOCATE (this % r__pswll0(1) )
!        ALLOCATE (this % r__roi(1) )
!        ALLOCATE (this % r__vs0(1) )
!        ALLOCATE (this % r__flowg(1) )
!        ALLOCATE (this % r__GasAx(1:naxialnodes) )
!        ALLOCATE (this % r__ProfileStartTime(1:ntimesteps) )
!        ALLOCATE (this % r__RodAvePower(1:ntimesteps) )
!        ALLOCATE (this % r__AxPowProfile(1:2*naxialnodes,1:ntimesteps) )
!        ALLOCATE (this % r__pazp(1:2*nradialnodes, 1:naxialnodes) )
!        ALLOCATE (this % r__cmesh(1:nradialnodes) )
!        ALLOCATE (this % r__fmesh(1:nradialnodes) )
!        ALLOCATE (this % r__zelev(1:naxialnodes) )
!        ALLOCATE (this % r__BoundaryCondition(1:6) )
!        ALLOCATE (this % r__ThermalConductAdv(1:nradialnodes) )
!        ALLOCATE (this % r__FinalTemp(1:nradialnodes) )
!        ALLOCATE (this % r__PrevTemp(1:nradialnodes) )
!        ALLOCATE (this % r__ArrayE(1:nradialnodes) )
!        ALLOCATE (this % r__ArrayF(1:nradialnodes) )
!        ALLOCATE (this % r__VolumeWeightL(1:nradialnodes,1:naxialnodes) )
!        ALLOCATE (this % r__VolumeWeightR(1:nradialnodes,1:naxialnodes) )
!        ALLOCATE (this % r__AreaWeight(1:nradialnodes,1:naxialnodes) )
!        ALLOCATE (this % r__ThermalConductivity(1:nradialnodes) )
!        ALLOCATE (this % r__acond(1:30,1:10) )
!        ALLOCATE (this % r__RhoCp(1:nradialnodes,1:naxialnodes) )
!        ALLOCATE (this % r__RhoCp0(1:nradialnodes,1:naxialnodes) )
!        ALLOCATE (this % r__PrevIterateTemp(1:nradialnodes,1:naxialnodes) )
!        ALLOCATE (this % r__relfraca(1:2*ntimesteps) )
!        ALLOCATE (this % r__FuelGasSwell(1:2*ntimesteps) )
!        ALLOCATE (this % r__ansr(1:nradialnodes) )
!        ALLOCATE (this % r__fmgp(1:naxialnodes) )
!        ALLOCATE (this % r__gasavail1(1:naxialnodes,1:nradialnodes)) ! 1:ngas r
!        ALLOCATE (this % r__gasavail2(1:naxialnodes,1:nradialnodes)) ! 1:ngas r
!        ALLOCATE (this % r__farbal(1:20) )
!        ALLOCATE (this % r__sdfar(1:20) )
!        ALLOCATE (this % r__zfarbl(1:20) )
!        ALLOCATE (this % r__ablona(1:73) )
!        ALLOCATE (this % r__IndexTempConverg(1:naxialnodes) )
!        ALLOCATE (this % r__RadialPower(1:nradialnodes) )
!        ALLOCATE (this % r__RadialBound(1:nradialnodes) )
!        ALLOCATE (this % r__qmaxmelt(1:nradialnodes) )
!        ALLOCATE (this % r__qmaxmeltp1(1:nradialnodes) )
!        ALLOCATE (this % r__rmassflux(1:naxialnodes) )
!        ALLOCATE (this % r__coolqual(1:naxialnodes) )
!        ALLOCATE (this % r__AAHT1(1:naxialnodes) )
!        ALLOCATE (this % r__BBHT1(1:naxialnodes) )
!        ALLOCATE (this % r__GasPress0(1:naxialnodes) )
!        ALLOCATE (this % r__CoolPress(1:naxialnodes) )
!        ALLOCATE (this % r__GasMolesAx(1:naxialnodes) )
!        ALLOCATE (this % r__GasMolesAx0(1:naxialnodes) )
!        ALLOCATE (this % r__GasPress(1:naxialnodes) )
!        ALLOCATE (this % r__FuelSurfT(1:naxialnodes) )
!        ALLOCATE (this % r__FuelCenterT(1:naxialnodes) )
!        ALLOCATE (this % r__CrackTemp(1:naxialnodes) )
!        ALLOCATE (this % r__VolOpenPor(1:naxialnodes) )
!        ALLOCATE (this % r__GapThick(1:naxialnodes) )
!        ALLOCATE (this % r__GapThick0(1:naxialnodes) )
!        ALLOCATE (this % r__GapTemp(1:naxialnodes) )
!        ALLOCATE (this % r__PelletRad(1:naxialnodes) )
!        ALLOCATE (this % r__PelletRad0(1:naxialnodes) )
!        ALLOCATE (this % r__HeatFlux(1:naxialnodes) )
!        ALLOCATE (this % r__HeatFlux0(1:naxialnodes) )
!        ALLOCATE (this % r__SurfHtFlux(1:naxialnodes) )
!        ALLOCATE (this % r__CladMaxT(1:naxialnodes) )
!        ALLOCATE (this % r__Vreloc(1:naxialnodes) )
!        ALLOCATE (this % r__Vreloc0(1:naxialnodes) )
!        ALLOCATE (this % r__PelSrfDispl(1:naxialnodes) )
!        ALLOCATE (this % r__OldPelDis(1:naxialnodes) )
!        ALLOCATE (this % r__OldPelDis0(1:naxialnodes) )
!        ALLOCATE (this % r__OxiThk1(1:naxialnodes) )
!        ALLOCATE (this % r__OxiThk2(1:naxialnodes) )
!        ALLOCATE (this % r__DishVperL(1:naxialnodes) )
!        ALLOCATE (this % r__FastFlux(1:naxialnodes) )
!        ALLOCATE (this % r__AlphaThk1(1:naxialnodes) )
!        ALLOCATE (this % r__AlphaThk2(1:naxialnodes) )
!        ALLOCATE (this % r__AlphaThk11(1:naxialnodes) )
!        ALLOCATE (this % r__AlphaThk22(1:naxialnodes) )
!        ALLOCATE (this % r__oxideid(1:naxialnodes) )
!        ALLOCATE (this % r__EffStrain(1:naxialnodes) )
!        ALLOCATE (this % r__EffStrain0(1:naxialnodes) )
!        ALLOCATE (this % r__oxideod(1:naxialnodes) )
!        ALLOCATE (this % r__CldPermStrn(1:naxialnodes) )
!        ALLOCATE (this % r__CldPermStrn0(1:naxialnodes) )
!        ALLOCATE (this % r__SSHgap(1:naxialnodes) )
!        ALLOCATE (this % r__OldCoolPrs(1:naxialnodes) )
!        ALLOCATE (this % r__OldCoolPrs0(1:naxialnodes) )
!        ALLOCATE (this % r__CladAveTemp(1:naxialnodes) )
!        ALLOCATE (this % r__OldGasPrs(1:naxialnodes) )
!        ALLOCATE (this % r__OldGasPrs0(1:naxialnodes) )
!        ALLOCATE (this % r__HtFlxFac(1:naxialnodes) )
!        ALLOCATE (this % r__OldCladT(1:naxialnodes) )
!        ALLOCATE (this % r__OldFuelAxStrn(1:naxialnodes) )
!        ALLOCATE (this % r__RodOD(1:naxialnodes) )
!        ALLOCATE (this % r__OldCldAxStrn(1:naxialnodes) )
!        ALLOCATE (this % r__OldCldAxStrn0(1:naxialnodes) )
!        ALLOCATE (this % r__RodOD0(1:naxialnodes) )
!        ALLOCATE (this % r__OldCladT0(1:naxialnodes) )
!        ALLOCATE (this % r__OldFuelAxStrn0(1:naxialnodes) )
!        ALLOCATE (this % r__TimeofGBSep(1:naxialnodes) )
!        ALLOCATE (this % r__SwellDispl(1:naxialnodes) )
!        ALLOCATE (this % r__HmaxInitial(1:naxialnodes) )
!        ALLOCATE (this % r__CoolEnthalpy(1:naxialnodes) )
!        ALLOCATE (this % r__RInterfacPrs(1:naxialnodes) )
!        ALLOCATE (this % r__RInterfacPrs0(1:naxialnodes) )
!        ALLOCATE (this % r__HGapAv(1:naxialnodes) )
!        ALLOCATE (this % r__FilmCoeffAv(1:naxialnodes) )
!        ALLOCATE (this % r__AxialPowr(1:naxialnodes) )
!        ALLOCATE (this % r__AxialPowr0(1:naxialnodes) )
!        ALLOCATE (this % r__CritHtFlux(1:naxialnodes) )
!        ALLOCATE (this % r__FuelSrfStrRat(1:naxialnodes) )
!        ALLOCATE (this % r__WatrMetlEnrgy(1:naxialnodes) )
!        ALLOCATE (this % r__RInterfacGap(1:naxialnodes) )
!        ALLOCATE (this % r__CladSurfT(1:naxialnodes) )
!        ALLOCATE (this % r__EDotFZ(1:naxialnodes) )
!        ALLOCATE (this % r__PelSrfStrn0(1:naxialnodes) )
!        ALLOCATE (this % r__FuelSrfStrRat0(1:naxialnodes) )
!        ALLOCATE (this % r__EDotFZ0(1:naxialnodes) )
!        ALLOCATE (this % r__EnergyPerL(1:naxialnodes) )
!        ALLOCATE (this % r__HFXSum(1:naxialnodes) )
!        ALLOCATE (this % r__CladEnrgPerL(1:naxialnodes) )
!        ALLOCATE (this % r__CoolEnthalpy0(1:naxialnodes) )
!        ALLOCATE (this % r__CoolMassFlx(1:naxialnodes) )
!        ALLOCATE (this % r__Enthl(1:naxialnodes) )
!        ALLOCATE (this % r__CoolDensity(1:naxialnodes) )
!        ALLOCATE (this % r__CoolDensity0(1:naxialnodes) )
!        ALLOCATE (this % r__PelRadDeviat(1:naxialnodes) )
!        ALLOCATE (this % r__CldPermAxStrn(1:naxialnodes) )
!        ALLOCATE (this % r__VoidVolumeRatio(1:n_void_volumes) )
!        ALLOCATE (this % r__CldPermHoopStrn(1:naxialnodes) )
!        ALLOCATE (this % r__ECR(1:naxialnodes) )
!        ALLOCATE (this % r__OxUptakeID1(1:naxialnodes) )
!        ALLOCATE (this % r__OxUpTakeID2(1:naxialnodes) )
!        ALLOCATE (this % r__SEDPNNL(1:naxialnodes) )
!        ALLOCATE (this % r__EffStrainPNNL(1:naxialnodes) )
!        ALLOCATE (this % r__coefk(1:naxialnodes) )
!        ALLOCATE (this % r__coefn(1:naxialnodes) )
!        ALLOCATE (this % r__coefm(1:naxialnodes) )
!        ALLOCATE (this % r__Emodulus(1:naxialnodes) )
!        ALLOCATE (this % r__strainrateterm(1:naxialnodes) )
!        ALLOCATE (this % r__SEDEPRI(1:naxialnodes) )
!        ALLOCATE (this % r__EffFastFluStrnHardExp(1:naxialnodes) )
!        ALLOCATE (this % r__BetaThickness(1:naxialnodes) )
!        ALLOCATE (this % r__EffColdWkStrnHardExp(1:naxialnodes) )
!        ALLOCATE (this % r__OxygenConcenAve(1:naxialnodes) )
!        ALLOCATE (this % r__EffColdWkStrenCoef(1:naxialnodes) )
!        ALLOCATE (this % r__OxygenUptake(1:naxialnodes) )
!        ALLOCATE (this % r__OxStAlphaThkRemain(1:naxialnodes) )
!        ALLOCATE (this % r__OxStAlphaThkNearFuel(1:naxialnodes) )
!        ALLOCATE (this % r__EffFastFluStrenCoef(1:naxialnodes) )
!        ALLOCATE (this % r__OxiPowerGen(1:naxialnodes) )
!        ALLOCATE (this % r__PrcntSatBeta(1:naxialnodes) )
!        ALLOCATE (this % r__OxConcenAAO(1:naxialnodes) )
!        ALLOCATE (this % r__OxConcenABO(1:naxialnodes) )
!        ALLOCATE (this % r__OxConcenACO(1:naxialnodes) )
!        ALLOCATE (this % r__OxConcenADO(1:naxialnodes) )
!        ALLOCATE (this % r__OxConcenAEO(1:naxialnodes) )
!        ALLOCATE (this % r__OxConcenAFO(1:naxialnodes) )
!        ALLOCATE (this % r__OxConcenAGO(1:naxialnodes) )
!        ALLOCATE (this % r__OxConcenAHO(1:naxialnodes) )
!        ALLOCATE (this % r__OxConcenAIO(1:naxialnodes) )
!        ALLOCATE (this % r__OxConcenAAI(1:naxialnodes) )
!        ALLOCATE (this % r__OxConcenABI(1:naxialnodes) )
!        ALLOCATE (this % r__OxConcenACI(1:naxialnodes) )
!        ALLOCATE (this % r__OxConcenADI(1:naxialnodes) )
!        ALLOCATE (this % r__OxConcenAEI(1:naxialnodes) )
!        ALLOCATE (this % r__OxConcenAFI(1:naxialnodes) )
!        ALLOCATE (this % r__OxConcenAGI(1:naxialnodes) )
!        ALLOCATE (this % r__OxConcenAHI(1:naxialnodes) )
!        ALLOCATE (this % r__OxConcenAII(1:naxialnodes) )
!        ALLOCATE (this % r__CrackVolume(1:naxialnodes) )
!        ALLOCATE (this % r__OpenPorTemp(1:naxialnodes) )
!        ALLOCATE (this % r__AveDishTemp(1:naxialnodes) )
!        ALLOCATE (this % r__CentVoidVol(1:naxialnodes) )
!        ALLOCATE (this % r__ExtentOfBow(1:naxialnodes) )
!        ALLOCATE (this % r__AxialNodLen(1:naxialnodes) )
!        ALLOCATE (this % r__TerfacePres(1:naxialnodes) )
!        ALLOCATE (this % r__CrackWidth(1:naxialnodes) )
!        ALLOCATE (this % r__EinstabilStrain(1:naxialnodes) )
!        ALLOCATE (this % r__AxBurnup(1:naxialnodes) )
!        ALLOCATE (this % r__BOSOxideThick(1:naxialnodes) )
!        ALLOCATE (this % r__EOSOxideThick(1:naxialnodes) )
!        ALLOCATE (this % r__OpenPorVol(1:naxialnodes) )
!        ALLOCATE (this % r__OpenPorosity(1:naxialnodes) )
!        ALLOCATE (this % r__CladEffStress(1:naxialnodes) )
!        ALLOCATE (this % r__BulkCoolTemp(1:naxialnodes) )
!        ALLOCATE (this % r__CladYieldStress(1:naxialnodes) )
!        ALLOCATE (this % r__StressAtInstStrain(1:naxialnodes) )
!        ALLOCATE (this % r__techf(1:naxialnodes) )
!        ALLOCATE (this % r__CesiumContent(1:naxialnodes) )
!        ALLOCATE (this % r__HydrogenContent(1:naxialnodes) )
!        ALLOCATE (this % r__tschf(1:naxialnodes) )
!        ALLOCATE (this % r__WorkSpaceGAPI(1:naxialnodes) )
!        ALLOCATE (this % r__WorkSpaceEP1(1:naxialnodes) )
!        ALLOCATE (this % r__WorkSpaceURC(1:naxialnodes) )
!        ALLOCATE (this % r__WorkSpaceTCMx(1:naxialnodes) )
!        ALLOCATE (this % r__WorkSpaceGAP(1:naxialnodes) )
!        ALLOCATE (this % r__nodchf(1:naxialnodes+1) )
!        ALLOCATE (this % r__BOSTemp(1:nradialnodes,1:naxialnodes) )
!        ALLOCATE (this % r__EOSTemp(1:nradialnodes,1:naxialnodes) )
!        ALLOCATE (this % r__EOSRad(1:nradialnodes,1:naxialnodes) )
!        ALLOCATE (this % r__BOSRad(1:nradialnodes,1:naxialnodes) )
!        ALLOCATE (this % r__EnrgyMeltP1(1:nradialnodes,1:naxialnodes) )
!        ALLOCATE (this % r__EnrgyMeltZ(1:nradialnodes,1:naxialnodes) )
!        ALLOCATE (this % r__EnrgyMelt(1:nradialnodes,1:naxialnodes) )
!        ALLOCATE (this % r__EnrgyMeltZp1(1:nradialnodes,1:naxialnodes) )
!        ALLOCATE (this % r__RadialBoundO(1:nradialnodes,1:naxialnodes) )
!        ALLOCATE (this % r__DeformedRadiusOfMesh(1:nradialnodes,1:naxialnodes) )
!        ALLOCATE (this % r__WorkSpaceEPP1(1:naxialnodes,1:3) )
!        ALLOCATE (this % r__WorkSpacePINT(1:naxialnodes) )
!        ALLOCATE (this % r__WorkSpaceRCI(1:naxialnodes) )
!        ALLOCATE (this % r__WorkSpaceRCO(1:naxialnodes) )
!        ALLOCATE (this % r__WorkSpaceReloc(1:naxialnodes) )
!        ALLOCATE (this % r__AxNodElevat(1:naxialnodes) )
!        ALLOCATE (this % r__ureloc(1:naxialnodes) )
!        ALLOCATE (this % r__a1(1:10000) )
!        ALLOCATE (this % r__CldElStrn(1:naxialnodes,1:3) )
!        ALLOCATE (this % r__CldPlasStrn(1:naxialnodes,1:3) )
!        ALLOCATE (this % r__CldPlasStrn0(1:naxialnodes,1:3) )
!        ALLOCATE (this % r__CldStrn(1:naxialnodes,1:3) )
!        ALLOCATE (this % r__CldStrnRat(1:naxialnodes,1:3) )
!        ALLOCATE (this % r__CldStrnRat0(1:naxialnodes,1:3) )
!        ALLOCATE (this % r__HydrostatPress(1:naxialnodes) )
!        ALLOCATE (this % r__FuelResidStrn(1:naxialnodes,1:3) )
!        ALLOCATE (this % r__FuelResidStrn0(1:naxialnodes,1:3) )
!        ALLOCATE (this % r__Baln2Twall(1:16,1:16) )
!        ALLOCATE (this % r__CldresidStrn(1:naxialnodes,1:3) )
!        ALLOCATE (this % r__CldResidStrn0(1:naxialnodes,1:3) )
!        ALLOCATE (this % r__IodineContent(1:naxialnodes) )
!        ALLOCATE (this % r__PelSrfStrn(1:naxialnodes,1:3) )
!        ALLOCATE (this % r__CldStress(1:naxialnodes,1:3) )
!        ALLOCATE (this % r__CldThermStrn(1:naxialnodes,1:3) )
!        ALLOCATE (this % r__GRsv(4,1:nradialnodes,1:nradialnodes) )
!        ALLOCATE (this % r__IndexPCMI(1:naxialnodes) )
!        ALLOCATE (this % r__IndexPCMIOnce(1:naxialnodes) )
!        ALLOCATE (this % r__NumAzmuthNod(1:naxialnodes) )
!        ALLOCATE (this % r__Ichf(1:naxialnodes) )
!        ALLOCATE (this % r__Ih(1:naxialnodes) )
!        ALLOCATE (this % r__Ihtreg(1:naxialnodes) )
!        ALLOCATE (this % r__GapIndex(1:naxialnodes) )
!        ALLOCATE (this % r__BOSGapIndex(1:naxialnodes) )
!        ALLOCATE (this % r__BOSGapIndex0(1:naxialnodes) )
!        ALLOCATE (this % r__RuptFailIndex(1:naxialnodes) )
!        ALLOCATE (this % r__CladCollapseIndex(1:naxialnodes) )
!        ALLOCATE (this % r__CladCollIndx0(1:naxialnodes) )
!        ALLOCATE (this % r__OldGapIndex(1:naxialnodes) )
!        ALLOCATE (this % r__NodeSinterTemp(1:naxialnodes) )
!        ALLOCATE (this % r__RodFailIndex(1:naxialnodes) )
!        ALLOCATE (this % r__Ifstor(1:30) )
!        ALLOCATE (this % r__ihData(1:30) )
!        ALLOCATE (this % r__icglob(1:12,1:8) )
!        ALLOCATE (this % r__acolct(1:665) )
!        ALLOCATE (this % r__gasphs(1:2*ntimesteps) )
!        ALLOCATE (this % r__gasths(1:2*ntimesteps,1:2) )
!        ALLOCATE (this % r__gbse(1:5) )
!        ALLOCATE (this % r__pelprm(1:40) )
!        ALLOCATE (this % r__pinput(1:60) )
!        ALLOCATE (this % r__potput(1:60) )
!        ALLOCATE (this % r__tpln(1:6,1:2) )
!        ALLOCATE (this % r__tplbt1(1:6,1:2) )
!        ALLOCATE (this % r__aexcb(1) )
!        ALLOCATE (this % r__dtpoa(1:pre_nt+2) )
!        ALLOCATE (this % r__tplbot(1:6,1:2) )
!        ALLOCATE (this % r__Prop(1:26) )
!        ALLOCATE (this % r__nhprs(1:naxialnodes) )
!        ALLOCATE (this % r__ntprs(1:naxialnodes) )
!        ALLOCATE (this % r__nvprs(1:naxialnodes) )
!        ALLOCATE (this % r__npprs(1:naxialnodes) )
!        ALLOCATE (this % r__acoold(1) )
!        ALLOCATE (this % r__vfrad1(1:5) )
!        ALLOCATE (this % r__vfrad2(1:5) )
!        ALLOCATE (this % r__vfrad3(1:5) )
!        ALLOCATE (this % r__elvrad(1:5) )
!        ALLOCATE (this % r__htclev(1:naxialnodes) )
!        ALLOCATE (this % r__gbh(1:ntimesteps) )
!        ALLOCATE (this % r__hbh(1:ntimesteps) )
!        ALLOCATE (this % r__hinta(1:ntimesteps) )
!        ALLOCATE (this % r__hupta(1:ntimesteps) )
!        ALLOCATE (this % r__pbh(1:ntimesteps) )
!        ALLOCATE (this % r__tshrda(1:ntimesteps) )
!        ALLOCATE (this % r__htca(1:ntimesteps,1:naxialnodes) )
!        ALLOCATE (this % r__tblka(1:ntimesteps,1:naxialnodes) )
!        ALLOCATE (this % r__trad1(1:20,1:5) )
!        ALLOCATE (this % r__trad2(1:20,1:5) )
!        ALLOCATE (this % r__trad3(1:20,1:5) )
!        ALLOCATE (this % r__flthit(1:40) )
!        ALLOCATE (this % r__faxzq(1:2*naxialnodes) )
!        ALLOCATE (this % r__qaxzq(1:2*naxialnodes) )
!        ALLOCATE (this % r__tempfc(1:2*naxialnodes) )
!        ALLOCATE (this % r__aflcht(1:630) )
!        ALLOCATE (this % r__prestm(1:ntimesteps) )
!        ALLOCATE (this % r__hlqclp(1:ntimesteps) )
!        ALLOCATE (this % r__temptm(1:ntimesteps) )
!        ALLOCATE (this % r__fldrat(1:ntimesteps) )
!        ALLOCATE (this % r__tz2(1:naxialnodes) )
!        ALLOCATE (this % r__z1(1:naxialnodes) )
!        ALLOCATE (this % r__z2(1:naxialnodes) )
!        ALLOCATE (this % r__gz1(1:naxialnodes) )
!        ALLOCATE (this % r__gz2(1:naxialnodes) )
!        ALLOCATE (this % r__hz1(1:naxialnodes) )
!        ALLOCATE (this % r__hz2(1:naxialnodes) )
!        ALLOCATE (this % r__pz1(1:naxialnodes) )
!        ALLOCATE (this % r__pz2(1:naxialnodes) )
!        ALLOCATE (this % r__tz1(1:Total) )
!        ALLOCATE (this % r__aasth(1:17000) )
!        ALLOCATE (this % r__eppinp(1:2*naxialnodes) )
!        ALLOCATE (this % r__radpel(1:2*naxialnodes) )
!        ALLOCATE (this % r__dtplta(1:pre_nt+2) )
!        ALLOCATE (this % r__ngastmp(1:2) )
!        ALLOCATE (this % r__modfal(1) )
!        ALLOCATE (this % r__nswpm(1) )
!        ALLOCATE (this % r__irest2(1) )
!        ALLOCATE (this % r__ncs(1) )
!        ALLOCATE (this % r__irest3(1) )
!        ALLOCATE (this % r__indxjk(1:nradialnodes) )
!        ALLOCATE (this % r__nrc(1,1) )
!        ALLOCATE (this % r__dtmaxa(1:pre_nt+2) )
!        ALLOCATE (this % r__arest1(1:136) )
!        ALLOCATE (this % r__azpang(1:naxialnodes) )
!        ALLOCATE (this % r__fluxz(1:2*naxialnodes) )
!        ALLOCATE (this % r__tplna(1:6,1:2,1) )
!        ALLOCATE (this % r__imaterials(1:nradialnodes) )
!        ALLOCATE (this % r__imatflag(1:nradialnodes) )
!        ALLOCATE (this % r__imatflag1(1:nradialnodes) )
!        ALLOCATE (this % r__iDatapairs(1:nradialnodes) )
!        ALLOCATE (this % r__iheattablen(1:nradialnodes) )
!        ALLOCATE (this % r__nm(1:3) )
!        ALLOCATE (this % r__htco(1:naxialnodes) )
!        ALLOCATE (this % r__tem(1:naxialnodes) )
!        ALLOCATE (this % r__pbh1(1:ntimesteps) )
!        ALLOCATE (this % r__pbh2(1:ntimesteps) )
!        ALLOCATE (this % r__hlqcl(1:ntimesteps) )
!        ALLOCATE (this % r__ts(1:ntimesteps) )
!        ALLOCATE (this % r__gadoln(1:naxialnodes) )
!        ALLOCATE (this % r__oldepeff(1:naxialnodes) )
!        ALLOCATE (this % r__oldeps(1:naxialnodes) )
!        ALLOCATE (this % r__afrap(1:40000) )
!        ALLOCATE (this % r__amatpc(1) )
!        ALLOCATE (this % r__ispace(1:11) )
!        ALLOCATE (this % r__emflag(1:21) )
!        ALLOCATE (this % r__iok(1:5,1:naxialnodes) )
!        ALLOCATE (this % r__iokold(1:5,1:naxialnodes) )
!        ALLOCATE (this % r__FrapconTemp(1:nradialnodes,1:naxialnodes) )
!        ALLOCATE (this % r__qcold(1:20,1:20) )
!        ALLOCATE (this % r__SEDPNNLold(1:naxialnodes) )
!        ALLOCATE (this % r__oldEffStrainPNNL(1:naxialnodes) )
!        ALLOCATE (this % r__SEDEPRIold(1:naxialnodes) )
!        ALLOCATE (this % r__EPStrain1old(1:naxialnodes) )
!        ALLOCATE (this % r__EPStrain2old(1:naxialnodes) )
!        ALLOCATE (this % r__EPStrain3old(1:naxialnodes) )
!        ALLOCATE (this % r__StressHoopOld(1:naxialnodes) )
!        ALLOCATE (this % r__StressRadialOld(1:naxialnodes) )
!        ALLOCATE (this % r__StressAxialOld(1:naxialnodes) )
!        ALLOCATE (this % r__CladEffStressOld(1:naxialnodes) )
!        ALLOCATE (this % r__hsolold(1:naxialnodes) )
!        ALLOCATE (this % r__OldCldPlasStrn(1:naxialnodes) )
!        ALLOCATE (this % r__Iffrp(1:axial) )
!        ALLOCATE (this % r__pclrlp(1:axial) )
!        ALLOCATE (this % r__rmrlp(1:radial) )
!        ALLOCATE (this % r__hgpfrp(1:axial) )
!        ALLOCATE (this % r__ElevatThermHydr(1:axial) )
!        ALLOCATE (this % r__tmprlp(1:radial,1:axial) )
!        ALLOCATE (this % r__bufrp(1:axial) )
!        ALLOCATE (this % r__pgpfrp(1:axial) )
!        ALLOCATE (this % r__vrlfrp(1:axial) )
!        ALLOCATE (this % r__drdfrp(1:axial) )
!        ALLOCATE (this % r__ElevatFrap(1:axial) )
!        ALLOCATE (this % r__HTC_L(1:axial) )
!        ALLOCATE (this % r__HTC_V(1:axial) )
!        ALLOCATE (this % r__TBulk_L(1:axial) )
!        ALLOCATE (this % r__TBulk_V(1:axial) )
!        allocate (this % r__gfrac(1:8) )
!        allocate (this % r__gasfraction(1:ngases) )
!        ALLOCATE (this % r__gsmol0(1:ngases) )
!        ALLOCATE (this % r__dtdkta(1:pre_nt+2))
!        ALLOCATE (this % r__dktouts(1,1))
