read(ifile) this % r__convert_units        
read(ifile) this % r__printballoon         
read(ifile) this % r__printrodburst        
read(ifile) this % r__allocate_arrays_ft   
read(ifile) this % r__coupled              
read(ifile) this % r__ndebug               
read(ifile) this % r__dakota               
read(ifile) this % r__setunits             
read(ifile) this % r__first_pass           
read(ifile) this % r__first_call           
read(ifile) this % r__unit                 
read(ifile) this % r__rupflg               
read(ifile) this % r__coolant              
read(ifile) this % r__fraptranfn           
read(ifile) this % r__metal                
read(ifile) this % r__modheatmodel         
read(ifile) this % r__relocmodel           
read(ifile) this % r__lodmrk               
read(ifile) this % r__reflood              
read(ifile) this % r__namerf               
read(ifile) this % r__inst                 
read(ifile) this % r__bheat                
read(ifile) this % r__internal             
read(ifile) this % r__mheat                
read(ifile) this % r__radiation            
read(ifile) this % r__deformation          
read(ifile) this % r__ifaila               
read(ifile) this % r__kaxnlo               
read(ifile) this % r__ncirlp               
read(ifile) this % r__nprsw                
read(ifile) this % r__npbh                 
read(ifile) this % r__nbncal               
read(ifile) this % r__llp                  
read(ifile) this % r__ierr                 
read(ifile) this % r__lcoold               
read(ifile) this % r__nidoxide             
read(ifile) this % r__press                
read(ifile) this % r__cathca               
read(ifile) this % r__klp2                 
read(ifile) this % r__nelrad               
read(ifile) this % r__frapt4               
read(ifile) this % r__ntapou               
read(ifile) this % r__kaxhtc               
read(ifile) this % r__indexthermcon        
read(ifile) this % r__prestmp              
read(ifile) this % r__irupt                
read(ifile) this % r__indxmd               
read(ifile) this % r__nbowr                
read(ifile) this % r__ldialb               
read(ifile) this % r__modbal               
read(ifile) this % r__pressu               
read(ifile) this % r__inlet                
read(ifile) this % r__zone                 
read(ifile) this % r__ndap1                
read(ifile) this % r__nbhtc                
read(ifile) this % r__protectiveoxide      
read(ifile) this % r__rtheta               
read(ifile) this % r__ldir                 
read(ifile) this % r__istoicgrad           
read(ifile) this % r__ifail                
read(ifile) this % r__lchf                 
read(ifile) this % r__itswt                
read(ifile) this % r__pow                  
read(ifile) this % r__nsymm                
read(ifile) this % r__naazp                
read(ifile) this % r__nvol2                
read(ifile) this % r__idebug               
read(ifile) this % r__nvol1                
read(ifile) this % r__mhbh                 
read(ifile) this % r__modfd                
read(ifile) this % r__ixazmn               
read(ifile) this % r__gasflo               
read(ifile) this % r__nbrtmp               
read(ifile) this % r__nbrfdr               
read(ifile) this % r__prescri              
read(ifile) this % r__mbowr                
read(ifile) this % r__mtabl3               
read(ifile) this % r__mechan               
read(ifile) this % r__nfmesh               
read(ifile) this % r__mndchf               
read(ifile) this % r__naazpd               
read(ifile) this % r__npelraddeviat        
read(ifile) this % r__itdmx                
read(ifile) this % r__nhbh                 
read(ifile) this % r__nfrapconinitialization
read(ifile) this % r__ncool                
read(ifile) this % r__nsrad3               
read(ifile) this % r__indexgrainbndsep     
read(ifile) this % r__nedtsw               
read(ifile) this % r__azang                
read(ifile) this % r__m5fc2                
read(ifile) this % r__radiat               
read(ifile) this % r__mhinta               
read(ifile) this % r__luout                
read(ifile) this % r__nmesh                
read(ifile) this % r__mgaspr               
read(ifile) this % r__iagap                
read(ifile) this % r__indxkf               
read(ifile) this % r__nitmin               
read(ifile) this % r__nconsw               
read(ifile) this % r__numdta               
read(ifile) this % r__nhtcz                
read(ifile) this % r__kntbal               
read(ifile) this % r__nrazp                
read(ifile) this % r__iplant               
read(ifile) this % r__indexthermconadv     
read(ifile) this % r__mhlqc1               
read(ifile) this % r__nplnt                
read(ifile) this % r__nbrliq               
read(ifile) this % r__idoxid               
read(ifile) this % r__lcombk               
read(ifile) this % r__indexgeom            
read(ifile) this % r__kbaln                
read(ifile) this % r__nbuq                 
read(ifile) this % r__mtempt               
read(ifile) this % r__maxit                
read(ifile) this % r__nbundl               
read(ifile) this % r__reflo                
read(ifile) this % r__nlac                 
read(ifile) this % r__jchf                 
read(ifile) this % r__ntco                 
read(ifile) this % r__kflgb                
read(ifile) this % r__tape1                
read(ifile) this % r__lengmd               
read(ifile) this % r__tape2                
read(ifile) this % r__nitdt                
read(ifile) this % r__res                  
read(ifile) this % r__la1max               
read(ifile) this % r__jtr                  
read(ifile) this % r__nqbow                
read(ifile) this % r__idx2                 
read(ifile) this % r__geom                 
read(ifile) this % r__mhlqcp               
read(ifile) this % r__lowpl                
read(ifile) this % r__la1fil               
read(ifile) this % r__np                   
read(ifile) this % r__ifcmi                
read(ifile) this % r__ntempf               
read(ifile) this % r__izadfg               
read(ifile) this % r__npdtpo               
read(ifile) this % r__massfl               
read(ifile) this % r__ncards               
read(ifile) this % r__iterationcount       
read(ifile) this % r__itcntd               
read(ifile) this % r__iagap0               
read(ifile) this % r__odoxid               
read(ifile) this % r__ntstep               
read(ifile) this % r__kswell               
read(ifile) this % r__pressure             
read(ifile) this % r__mhupta               
read(ifile) this % r__ndtred               
read(ifile) this % r__nptha                
read(ifile) this % r__ncorlp               
read(ifile) this % r__bowing               
read(ifile) this % r__transwell            
read(ifile) this % r__unitin               
read(ifile) this % r__indexfc2print        
read(ifile) this % r__nepp0                
read(ifile) this % r__ntimesteps           
read(ifile) this % r__nchan                
read(ifile) this % r__nradialnodes         
read(ifile) this % r__mzq1                 
read(ifile) this % r__geometry             
read(ifile) this % r__upppl                
read(ifile) this % r__ruptur               
read(ifile) this % r__geomet               
read(ifile) this % r__nradq                
read(ifile) this % r__lcolct               
read(ifile) this % r__noiter               
read(ifile) this % r__nchfmd               
read(ifile) this % r__nchn                 
read(ifile) this % r__lresr2               
read(ifile) this % r__ntimes               
read(ifile) this % r__nfhtc                
read(ifile) this % r__lresr1               
read(ifile) this % r__mpbh                 
read(ifile) this % r__ncmesh               
read(ifile) this % r__nsc                  
read(ifile) this % r__indxkc               
read(ifile) this % r__ndim                 
read(ifile) this % r__naxn                 
read(ifile) this % r__lflect               
read(ifile) this % r__ns                   
read(ifile) this % r__nradsh               
read(ifile) this % r__lprntb               
read(ifile) this % r__mprest               
read(ifile) this % r__dktoutcounter        
read(ifile) this % r__nsf                  
read(ifile) this % r__ncooli               
read(ifile) this % r__m6fc2                
read(ifile) this % r__indxpr               
read(ifile) this % r__jmnbal               
read(ifile) this % r__modmw                
read(ifile) this % r__ncard2               
read(ifile) this % r__lsclr1               
read(ifile) this % r__nprad                
read(ifile) this % r__nhtca                
read(ifile) this % r__knonue               
read(ifile) this % r__chf                  
read(ifile) this % r__irefine              
read(ifile) this % r__mgbh                 
read(ifile) this % r__ndktparams           
read(ifile) this % r__lsclr2               
read(ifile) this % r__lsclr3               
read(ifile) this % r__defsize              
read(ifile) this % r__nflec                
read(ifile) this % r__lblona               
read(ifile) this % r__nodpln               
read(ifile) this % r__nrestart             
read(ifile) this % r__lafrap               
read(ifile) this % r__coreav               
read(ifile) this % r__nfuelswellpairs      
read(ifile) this % r__nswmd                
read(ifile) this % r__nvoid                
read(ifile) this % r__lmatpc               
read(ifile) this % r__inpfil               
read(ifile) this % r__numaxprofiles        
read(ifile) this % r__nkc                  
read(ifile) this % r__nomat                
read(ifile) this % r__nkf                  
read(ifile) this % r__nfgrpairs            
read(ifile) this % r__nhtclv               
read(ifile) this % r__npaxp                
read(ifile) this % r__ncool2               
read(ifile) this % r__kmxrlp               
read(ifile) this % r__kmxfrp               
read(ifile) this % r__indexbc              
read(ifile) this % r__ncall                
read(ifile) this % r__ndtmax               
read(ifile) this % r__naxialnodes          
read(ifile) this % r__soltyp               
read(ifile) this % r__nptha1               
read(ifile) this % r__ntplot               
read(ifile) this % r__ns2                  
read(ifile) this % r__nce                  
read(ifile) this % r__modkf                
read(ifile) this % r__mtabl1               
read(ifile) this % r__mtabl2               
read(ifile) this % r__nbalsw               
read(ifile) this % r__ixazim               
read(ifile) this % r__temp                 
read(ifile) this % r__indexinittemp        
read(ifile) this % r__cenvoi               
read(ifile) this % r__nrefld               
read(ifile) this % r__ndtad                
read(ifile) this % r__ntabl1               
read(ifile) this % r__nbrfht               
read(ifile) this % r__nqchn                
read(ifile) this % r__klp                  
read(ifile) this % r__npid                 
read(ifile) this % r__nforlp               
read(ifile) this % r__nswinw               
read(ifile) this % r__grass                
read(ifile) this % r__mpdcay               
read(ifile) this % r__baker                
read(ifile) this % r__spefbz               
read(ifile) this % r__ncolbp               
read(ifile) this % r__nt5                  
read(ifile) this % r__mwork                
read(ifile) this % r__nbrpst               
read(ifile) this % r__jpl                  
read(ifile) this % r__presfgr              
read(ifile) this % r__mbdl                 
read(ifile) this % r__nerr                 
read(ifile) this % r__inp                  
read(ifile) this % r__iflagn               
read(ifile) this % r__nhinta               
read(ifile) this % r__lthyd                
read(ifile) this % r__indexfintemp         
read(ifile) this % r__nnaz                 
read(ifile) this % r__npaxp1               
read(ifile) this % r__nrazpd               
read(ifile) this % r__mflt                 
read(ifile) this % r__maximumiterations    
read(ifile) this % r__npramp               
read(ifile) this % r__nzmesh               
read(ifile) this % r__nprofile             
read(ifile) this % r__igpnod               
read(ifile) this % r__npair                
read(ifile) this % r__coldwa               
read(ifile) this % r__refloodtime          
read(ifile) this % r__ngbh                 
read(ifile) this % r__lphypr               
read(ifile) this % r__ifbaln               
read(ifile) this % r__nrest2               
read(ifile) this % r__length               
read(ifile) this % r__nfastf               
read(ifile) this % r__nthermex             
read(ifile) this % r__lhtc                 
read(ifile) this % r__naz                  
read(ifile) this % r__nvol                 
read(ifile) this % r__imox                 
read(ifile) this % r__nt                   
read(ifile) this % r__maxidx               
read(ifile) this % r__lhtcb                
read(ifile) this % r__collaps              
read(ifile) this % r__profile              
read(ifile) this % r__nucbo                
read(ifile) this % r__filmbo               
read(ifile) this % r__cladtype             
read(ifile) this % r__ndtadv               
read(ifile) this % r__ncladi               
read(ifile) this % r__npaxpf               
read(ifile) this % r__jfb                  
read(ifile) this % r__n4                   
read(ifile) this % r__nhtc                 
read(ifile) this % r__ngasr                
read(ifile) this % r__ithymx               
read(ifile) this % r__ifailue              
read(ifile) this % r__axpow                
read(ifile) this % r__n1                   
read(ifile) this % r__nsteadytrans         
read(ifile) this % r__nprntb               
read(ifile) this % r__nbotpl               
read(ifile) this % r__nsym                 
read(ifile) this % r__la1req               
read(ifile) this % r__noball               
read(ifile) this % r__kbot                 
read(ifile) this % r__n3                   
read(ifile) this % r__lresi3               
read(ifile) this % r__lresi2               
read(ifile) this % r__liquid               
read(ifile) this % r__nodprm               
read(ifile) this % r__ngaspr               
read(ifile) this % r__ntabl3               
read(ifile) this % r__ntabl2               
read(ifile) this % r__iflago               
read(ifile) this % r__indx                 
read(ifile) this % r__ndktn                
read(ifile) this % r__npltn                
read(ifile) this % r__unitout              
read(ifile) this % r__ifchk                
read(ifile) this % r__plenumtemp           
read(ifile) this % r__lexcb                
read(ifile) this % r__kdbug                
read(ifile) this % r__n2                   
read(ifile) this % r__gammait              
read(ifile) this % r__liqnod               
read(ifile) this % r__nhupta               
read(ifile) this % r__irup                 
read(ifile) this % r__splbp                
read(ifile) this % r__tpowf                
read(ifile) this % r__kappag               
read(ifile) this % r__dtpo                 
read(ifile) this % r__refdtm               
read(ifile) this % r__achn                 
read(ifile) this % r__prodxe               
read(ifile) this % r__pdeint               
read(ifile) this % r__zbaln                
read(ifile) this % r__tplenb               
read(ifile) this % r__tflood               
read(ifile) this % r__kappaf               
read(ifile) this % r__sigcladthermcond     
read(ifile) this % r__pitch                
read(ifile) this % r__dcldh                
read(ifile) this % r__cnfsol               
read(ifile) this % r__gasmoles0            
read(ifile) this % r__tfoldf               
read(ifile) this % r__bowthr               
read(ifile) this % r__hrad                 
read(ifile) this % r__dofang               
read(ifile) this % r__t0f                  
read(ifile) this % r__pressr               
read(ifile) this % r__t0c                  
read(ifile) this % r__maxenthalpy          
read(ifile) this % r__tp1bal               
read(ifile) this % r__tmaxf                
read(ifile) this % r__tt                   
read(ifile) this % r__rmpbal               
read(ifile) this % r__qlbal                
read(ifile) this % r__frden                
read(ifile) this % r__vsubg                
read(ifile) this % r__vsubf                
read(ifile) this % r__dtbal                
read(ifile) this % r__delth                
read(ifile) this % r__prodkr               
read(ifile) this % r__tshtc                
read(ifile) this % r__cexh2l               
read(ifile) this % r__zpkfc                
read(ifile) this % r__htcgba               
read(ifile) this % r__frbal                
read(ifile) this % r__reflpr               
read(ifile) this % r__qbal                 
read(ifile) this % r__pelh                 
read(ifile) this % r__arean                
read(ifile) this % r__zndbal               
read(ifile) this % r__t12                  
read(ifile) this % r__debugtime            
read(ifile) this % r__pavg                 
read(ifile) this % r__aidsht               
read(ifile) this % r__rl                   
read(ifile) this % r__maxcladtemp          
read(ifile) this % r__dtheta               
read(ifile) this % r__hsubf                
read(ifile) this % r__gapconductivity      
read(ifile) this % r__cpmult               
read(ifile) this % r__fdelta               
read(ifile) this % r__sigfuelthermexp      
read(ifile) this % r__totnb                
read(ifile) this % r__sigcladthermexp      
read(ifile) this % r__timop                
read(ifile) this % r__src2                 
read(ifile) this % r__flowbk               
read(ifile) this % r__totalvoidvol         
read(ifile) this % r__htcbal               
read(ifile) this % r__powop                
read(ifile) this % r__tplen                
read(ifile) this % r__flxsec               
read(ifile) this % r__t2                   
read(ifile) this % r__t0                   
read(ifile) this % r__t1                   
read(ifile) this % r__ffch                 
read(ifile) this % r__dtenfb               
read(ifile) this % r__crf                  
read(ifile) this % r__fpdcay               
read(ifile) this % r__debugtimestop        
read(ifile) this % r__roughc               
read(ifile) this % r__x                    
read(ifile) this % r__chstrs               
read(ifile) this % r__roughf               
read(ifile) this % r__dtenfo               
read(ifile) this % r__drod                 
read(ifile) this % r__jhtc                 
read(ifile) this % r__hliq                 
read(ifile) this % r__rfbal                
read(ifile) this % r__pctop                
read(ifile) this % r__prsacc               
read(ifile) this % r__tprlp                
read(ifile) this % r__relfract             
read(ifile) this % r__fpowr                
read(ifile) this % r__gum                  
read(ifile) this % r__gpthk0               
read(ifile) this % r__tref                 
read(ifile) this % r__ftmelt               
read(ifile) this % r__zs                   
read(ifile) this % r__tc0bal               
read(ifile) this % r__tgbal                
read(ifile) this % r__apowrd               
read(ifile) this % r__rodlength            
read(ifile) this % r__psat                 
read(ifile) this % r__srcv2                
read(ifile) this % r__time0                
read(ifile) this % r__flxbal               
read(ifile) this % r__fuelrd               
read(ifile) this % r__zmesh                
read(ifile) this % r__rf                   
read(ifile) this % r__ctmelt               
read(ifile) this % r__htflxa               
read(ifile) this % r__pdrato               
read(ifile) this % r__templo               
read(ifile) this % r__zro                  
read(ifile) this % r__drflt                
read(ifile) this % r__tgas0                
read(ifile) this % r__swllfr               
read(ifile) this % r__gsmfrp               
read(ifile) this % r__modheat              
read(ifile) this % r__spdbp                
read(ifile) this % r__pfail                
read(ifile) this % r__cladid               
read(ifile) this % r__fldrpr               
read(ifile) this % r__nu3                  
read(ifile) this % r__pmxbal               
read(ifile) this % r__nu1                  
read(ifile) this % r__timmd                
read(ifile) this % r__aidtot               
read(ifile) this % r__aidsur               
read(ifile) this % r__tsub                 
read(ifile) this % r__sigcladyieldstr      
read(ifile) this % r__fabal                
read(ifile) this % r__rhoc                 
read(ifile) this % r__tflux                
read(ifile) this % r__rhof                 
read(ifile) this % r__tdbugd               
read(ifile) this % r__sigfuelheatcapa      
read(ifile) this % r__deloxy               
read(ifile) this % r__r8bal                
read(ifile) this % r__z                    
read(ifile) this % r__delth0               
read(ifile) this % r__tmax                 
read(ifile) this % r__qmax                 
read(ifile) this % r__chefus               
read(ifile) this % r__trabal               
read(ifile) this % r__rcpar                
read(ifile) this % r__pressi               
read(ifile) this % r__t22                  
read(ifile) this % r__ffchf                
read(ifile) this % r__roddiameter          
read(ifile) this % r__coolantpress         
read(ifile) this % r__ruplev               
read(ifile) this % r__epsht1               
read(ifile) this % r__h0bal                
read(ifile) this % r__tmaxc                
read(ifile) this % r__zad                  
read(ifile) this % r__tranfuelswell        
read(ifile) this % r__csubp                
read(ifile) this % r__cladpower            
read(ifile) this % r__src1                 
read(ifile) this % r__rshrd                
read(ifile) this % r__dppowi               
read(ifile) this % r__zqch                 
read(ifile) this % r__frcoef               
read(ifile) this % r__empytm               
read(ifile) this % r__zroug2               
read(ifile) this % r__frchmx               
read(ifile) this % r__tbkbal               
read(ifile) this % r__timbal               
read(ifile) this % r__pcbal                
read(ifile) this % r__plenumgasmoles       
read(ifile) this % r__xtime                
read(ifile) this % r__doffst               
read(ifile) this % r__hsubg                
read(ifile) this % r__powimx               
read(ifile) this % r__buoxide              
read(ifile) this % r__fltgap               
read(ifile) this % r__psbal                
read(ifile) this % r__emptm                
read(ifile) this % r__dvdtp                
read(ifile) this % r__tm1bal               
read(ifile) this % r__trise                
read(ifile) this % r__usubf                
read(ifile) this % r__usubg                
read(ifile) this % r__fltgap2              
read(ifile) this % r__hydiam               
read(ifile) this % r__dishd                
read(ifile) this % r__beta1                
read(ifile) this % r__cldwdc               
read(ifile) this % r__cpstem               
read(ifile) this % r__tplot                
read(ifile) this % r__csubpg               
read(ifile) this % r__csubpf               
read(ifile) this % r__tfavba               
read(ifile) this % r__fotmtl               
read(ifile) this % r__timeincrement        
read(ifile) this % r__tmpac1               
read(ifile) this % r__sigfuelthermcond     
read(ifile) this % r__crfpr                
read(ifile) this % r__sigsurfhtc           
read(ifile) this % r__trecrd               
read(ifile) this % r__emwbal               
read(ifile) this % r__cladod               
read(ifile) this % r__ruptstrain           
read(ifile) this % r__zqchpr               
read(ifile) this % r__tsntrk               
read(ifile) this % r__rsntr                
read(ifile) this % r__nu2                  
read(ifile) this % r__volavegastemp        
read(ifile) this % r__zroug1               
read(ifile) this % r__aidlng               
read(ifile) this % r__rhostm               
read(ifile) this % r__ph                   
read(ifile) this % r__coldbp               
read(ifile) this % r__tempmx               
read(ifile) this % r__betag                
read(ifile) this % r__betaf                
read(ifile) this % r__kappa                
read(ifile) this % r__cfluxa               
read(ifile) this % r__dtold                
read(ifile) this % r__zvoid1               
read(ifile) this % r__atop                 
read(ifile) this % r__rvoid                
read(ifile) this % r__qaxpk                
read(ifile) this % r__dofset               
read(ifile) this % r__tf0bal               
read(ifile) this % r__ubar                 
read(ifile) this % r__pl                   
read(ifile) this % r__v                    
read(ifile) this % r__tdkt                 
read(ifile) this % r__dtp                  
read(ifile) this % r__totalgasmoles        
read(ifile) this % r__refine               
read(ifile) this % r__gflow                
read(ifile) this % r__gfloa1               
read(ifile) this % r__temphi               
read(ifile) this % r__frchdt               
read(ifile) this % r__fhtc                 
read(ifile) this % r__frpo2                
read(ifile) this % r__trest                
read(ifile) this % r__fgrns                
read(ifile) this % r__dtmpcl               
read(ifile) this % r__areao                
read(ifile) this % r__pfnuc                
read(ifile) this % r__r0bal                
read(ifile) this % r__fuelpeldiam          
read(ifile) this % r__tsatt                
read(ifile) this % r__pdecy                
read(ifile) this % r__ztmax                
read(ifile) this % r__zqflt                
read(ifile) this % r__fldrte               
read(ifile) this % r__coldw                
read(ifile) this % r__openporosityfraction 
read(ifile) this % r__dhe                  
read(ifile) this % r__explenumv            
read(ifile) this % r__compmt               
read(ifile) this % r__maxgaspressure       
read(ifile) this % r__dtss                 
read(ifile) this % r__oldtim               
read(ifile) this % r__dhy                  
read(ifile) this % r__tc1                  
read(ifile) this % r__volbp                
read(ifile) this % r__bup                  
read(ifile) this % r__fhefus               
read(ifile) this % r__powict               
read(ifile) this % r__fr                   
read(ifile) this % r__pois                 
read(ifile) this % r__dtobal               
read(ifile) this % r__dcldh0               
read(ifile) this % r__pavgft               
read(ifile) this % r__tc2                  
read(ifile) this % r__gsms                 
read(ifile) this % r__time                 
read(ifile) this % r__taxbal               
read(ifile) this % r__trodfc               
read(ifile) this % r__dishv0               
read(ifile) this % r__beta                 
read(ifile) this % r__tpo                  
read(ifile) this % r__cladtk               
read(ifile) this % r__zm1bal               
read(ifile) this % r__dzmesh               
read(ifile) this % r__toldfc               
read(ifile) this % r__rnbnt                
read(ifile) this % r__defaulttemp          
read(ifile) this % r__hbar                 
read(ifile) this % r__e                    
read(ifile) this % r__gapthk               
read(ifile) this % r__zbot                 
read(ifile) this % r__vplenc               
read(ifile) this % r__vplenb               
read(ifile) this % r__bottomplenumgasmoles 
read(ifile) this % r__bumtp                
read(ifile) this % r__zvoid2               
read(ifile) this % r__zp1bal               
read(ifile) this % r__fqcrit               
read(ifile) this % r__rshd                 
read(ifile) this % r__tcebal               
read(ifile) this % r__tempcs               
read(ifile) this % r__maxfueltemp          
read(ifile) this % r__pfflec               
read(ifile) this % r__gapmin               
read(ifile) this % r__cnfliq               
read(ifile) this % r__emflag               
read(ifile) this % r__ifstor               
read(ifile) this % r__ichf                 
read(ifile) this % r__nswpm                
read(ifile) this % r__tem                  
read(ifile) this % r__imaterials           
read(ifile) this % r__modfal               
read(ifile) this % r__idumr1               
read(ifile) this % r__ih                   
read(ifile) this % r__iffrp                
read(ifile) this % r__ihtreg               
read(ifile) this % r__indxjk               
read(ifile) this % r__ibnopt               
read(ifile) this % r__ruptfailindex        
read(ifile) this % r__nm                   
read(ifile) this % r__ies                  
read(ifile) this % r__nopt                 
read(ifile) this % r__indexpcmionce        
read(ifile) this % r__cladcollapseindex    
read(ifile) this % r__rodfailindex         
read(ifile) this % r__gapindex             
read(ifile) this % r__irest2               
read(ifile) this % r__imatflag             
read(ifile) this % r__oldgapindex          
read(ifile) this % r__htco                 
read(ifile) this % r__indextempconverg     
read(ifile) this % r__bosgapindex          
read(ifile) this % r__idatapairs           
read(ifile) this % r__ncs                  
read(ifile) this % r__nvprs                
read(ifile) this % r__npprs                
read(ifile) this % r__irest3               
read(ifile) this % r__bosgapindex0         
read(ifile) this % r__ntprs                
read(ifile) this % r__ihdata               
read(ifile) this % r__imatflag1            
read(ifile) this % r__cladcollindx0        
read(ifile) this % r__nunopt               
read(ifile) this % r__nhprs                
read(ifile) this % r__nodesintertemp       
read(ifile) this % r__ngastmp              
read(ifile) this % r__ndchfi               
read(ifile) this % r__iheattablen          
read(ifile) this % r__indexpcmi            
read(ifile) this % r__numazmuthnod         
read(ifile) this % r__roi                  
read(ifile) this % r__alphathk11           
read(ifile) this % r__tbulk_v              
read(ifile) this % r__cladenrgperl         
read(ifile) this % r__efffastflustrencoef  
read(ifile) this % r__scd                  
read(ifile) this % r__watrmetlenrgy        
read(ifile) this % r__coolpress            
read(ifile) this % r__dtplta               
read(ifile) this % r__oxconcenaio          
read(ifile) this % r__apln                 
read(ifile) this % r__oxygenuptake         
read(ifile) this % r__thermalconductadv    
read(ifile) this % r__ascal2               
read(ifile) this % r__gasax                
read(ifile) this % r__profilestarttime     
read(ifile) this % r__ascal1               
read(ifile) this % r__htflxfac             
read(ifile) this % r__htclev               
read(ifile) this % r__tbulk_l              
read(ifile) this % r__prop                 
read(ifile) this % r__oxconcenado          
read(ifile) this % r__flwblk               
read(ifile) this % r__tempfc               
read(ifile) this % r__oxconcenadi          
read(ifile) this % r__rinterfacgap         
read(ifile) this % r__stressatinststrain   
read(ifile) this % r__rinterfacprs0        
read(ifile) this % r__ts                   
read(ifile) this % r__tp                   
read(ifile) this % r__claddingpower        
read(ifile) this % r__oldcoolprs0          
read(ifile) this % r__voidvolumeratio      
read(ifile) this % r__techf                
read(ifile) this % r__eosoxidethick        
read(ifile) this % r__cexh2a               
read(ifile) this % r__pelraddeviat         
read(ifile) this % r__coolenthalpy0        
read(ifile) this % r__epstrain1old         
read(ifile) this % r__azpang               
read(ifile) this % r__coolmassflx          
read(ifile) this % r__hmaxinitial          
read(ifile) this % r__betathickness        
read(ifile) this % r__oxstalphathkremain   
read(ifile) this % r__powave               
read(ifile) this % r__axburnup             
read(ifile) this % r__apln0                
read(ifile) this % r__alphathk1            
read(ifile) this % r__amatpc               
read(ifile) this % r__fdial                
read(ifile) this % r__vrlfrp               
read(ifile) this % r__rinterfacprs         
read(ifile) this % r__energyperl           
read(ifile) this % r__dvdt                 
read(ifile) this % r__effcoldwkstrnhardexp 
read(ifile) this % r__gapthick0            
read(ifile) this % r__oxconcenaci          
read(ifile) this % r__gbse                 
read(ifile) this % r__fmgp                 
read(ifile) this % r__oldcoolprs           
read(ifile) this % r__sshgap               
read(ifile) this % r__workspacetcmx        
read(ifile) this % r__sedpnnlold           
read(ifile) this % r__heatflux             
read(ifile) this % r__boundarycondition    
read(ifile) this % r__gadoln               
read(ifile) this % r__oxconcenaco          
read(ifile) this % r__gfrac                
read(ifile) this % r__radialpower          
read(ifile) this % r__stressaxialold       
read(ifile) this % r__surfhtflux           
read(ifile) this % r__oldcldplasstrn       
read(ifile) this % r__gbh                  
read(ifile) this % r__prevtemp             
read(ifile) this % r__workspacereloc       
read(ifile) this % r__pelletrad0           
read(ifile) this % r__rmrlp                
read(ifile) this % r__hz2                  
read(ifile) this % r__fastflux             
read(ifile) this % r__bbht1                
read(ifile) this % r__pbh                  
read(ifile) this % r__gaptemp              
read(ifile) this % r__arest1               
read(ifile) this % r__dvdt0                
read(ifile) this % r__drdfrp               
read(ifile) this % r__oldgasprs            
read(ifile) this % r__fuelgasswell         
read(ifile) this % r__oxuptakeid2          
read(ifile) this % r__stresshoopold        
read(ifile) this % r__effcoldwkstrencoef   
read(ifile) this % r__oxconcenago          
read(ifile) this % r__rodod0               
read(ifile) this % r__dtmaxa               
read(ifile) this % r__pelletrad            
read(ifile) this % r__edint                
read(ifile) this % r__alphathk2            
read(ifile) this % r__axialpowr            
read(ifile) this % r__pelsrfdispl          
read(ifile) this % r__hgapav               
read(ifile) this % r__tmelt                
read(ifile) this % r__temptm               
read(ifile) this % r__enthl                
read(ifile) this % r__flthit               
read(ifile) this % r__bpln                 
read(ifile) this % r__cladmaxt             
read(ifile) this % r__qaxzq                
read(ifile) this % r__oxconcenaii          
read(ifile) this % r__vfrad1               
read(ifile) this % r__vfrad3               
read(ifile) this % r__vfrad2               
read(ifile) this % r__oxconcenafo          
read(ifile) this % r__tend                 
read(ifile) this % r__aexcb                
read(ifile) this % r__sedepri              
read(ifile) this % r__alphathk22           
read(ifile) this % r__oxithk1              
read(ifile) this % r__bufrp                
read(ifile) this % r__hz1                  
read(ifile) this % r__swelldispl           
read(ifile) this % r__oxithk2              
read(ifile) this % r__tshrda               
read(ifile) this % r__vs0                  
read(ifile) this % r__acoold               
read(ifile) this % r__hgpfrp               
read(ifile) this % r__hlqcl                
read(ifile) this % r__finaltemp            
read(ifile) this % r__techfi               
read(ifile) this % r__pbh1                 
read(ifile) this % r__pbh2                 
read(ifile) this % r__aflcht               
read(ifile) this % r__bu                   
read(ifile) this % r__ecr                  
read(ifile) this % r__vreloc0              
read(ifile) this % r__epstrain2old         
read(ifile) this % r__hlqclp               
read(ifile) this % r__bpln0                
read(ifile) this % r__pz2                  
read(ifile) this % r__cesiumcontent        
read(ifile) this % r__z1                   
read(ifile) this % r__z2                   
read(ifile) this % r__faxzq                
read(ifile) this % r__fluxz                
read(ifile) this % r__gapthick             
read(ifile) this % r__hbh                  
read(ifile) this % r__oldepeff             
read(ifile) this % r__oldeffstrainpnnl     
read(ifile) this % r__cladavetemp          
read(ifile) this % r__nodchf               
read(ifile) this % r__oldgasprs0           
read(ifile) this % r__aasth                
read(ifile) this % r__aprntb               
read(ifile) this % r__volopenpor           
read(ifile) this % r__farbal               
read(ifile) this % r__extentofbow          
read(ifile) this % r__oldcldaxstrn0        
read(ifile) this % r__sdfar                
read(ifile) this % r__ablona               
read(ifile) this % r__cladeffstress        
read(ifile) this % r__rodavepower          
read(ifile) this % r__gasmolesax0          
read(ifile) this % r__cooldensity0         
read(ifile) this % r__ascal3               
read(ifile) this % r__arrayf               
read(ifile) this % r__oldpeldis            
read(ifile) this % r__edotfz               
read(ifile) this % r__workspacerco         
read(ifile) this % r__workspaceep1         
read(ifile) this % r__cldpermstrn          
read(ifile) this % r__hydrogencontent      
read(ifile) this % r__gasfraction          
read(ifile) this % r__tz2                  
read(ifile) this % r__workspacerci         
read(ifile) this % r__hfusn                
read(ifile) this % r__prcntsatbeta         
read(ifile) this % r__qpln0                
read(ifile) this % r__oxconcenaai          
read(ifile) this % r__oldpeldis0           
read(ifile) this % r__flowg                
read(ifile) this % r__oxconcenaao          
read(ifile) this % r__iodinecontent        
read(ifile) this % r__oldfuelaxstrn        
read(ifile) this % r__terfacepres          
read(ifile) this % r__axnodelevat          
read(ifile) this % r__cladsurft            
read(ifile) this % r__oxconcenabi          
read(ifile) this % r__cladyieldstress      
read(ifile) this % r__oxideid              
read(ifile) this % r__swd                  
read(ifile) this % r__tschfi               
read(ifile) this % r__strainrateterm       
read(ifile) this % r__hsolold              
read(ifile) this % r__gasmolesax           
read(ifile) this % r__hfxsum               
read(ifile) this % r__pclrlp               
read(ifile) this % r__elevatthermhydr      
read(ifile) this % r__timeofgbsep          
read(ifile) this % r__effstrain0           
read(ifile) this % r__oxideod              
read(ifile) this % r__coolqual             
read(ifile) this % r__crithtflux           
read(ifile) this % r__axialnodlen          
read(ifile) this % r__oxconcenahi          
read(ifile) this % r__effstrain            
read(ifile) this % r__filmcoeffav          
read(ifile) this % r__workspacepint        
read(ifile) this % r__sedpnnl              
read(ifile) this % r__heatflux0            
read(ifile) this % r__rmassflux            
read(ifile) this % r__qmaxmelt             
read(ifile) this % r__cldpermhoopstrn      
read(ifile) this % r__stressradialold      
read(ifile) this % r__fuelsrfstrrat        
read(ifile) this % r__cladeffstressold     
read(ifile) this % r__oxconcenaeo          
read(ifile) this % r__cracktemp            
read(ifile) this % r__thermalconductivity  
read(ifile) this % r__fldrat               
read(ifile) this % r__qmaxmeltp1           
read(ifile) this % r__pgpfrp               
read(ifile) this % r__radpel               
read(ifile) this % r__oxconcenaei          
read(ifile) this % r__coefm                
read(ifile) this % r__coefn                
read(ifile) this % r__coefk                
read(ifile) this % r__openportemp          
read(ifile) this % r__rodod                
read(ifile) this % r__fuelsrfstrrat0       
read(ifile) this % r__deltox               
read(ifile) this % r__vreloc               
read(ifile) this % r__cldpermaxstrn        
read(ifile) this % r__fmesh                
read(ifile) this % r__pelprm               
read(ifile) this % r__workspacegap         
read(ifile) this % r__cmesh                
read(ifile) this % r__gsmol0               
read(ifile) this % r__openporvol           
read(ifile) this % r__bowrat               
read(ifile) this % r__gappr0               
read(ifile) this % r__vplen                
read(ifile) this % r__arraye               
read(ifile) this % r__openporosity         
read(ifile) this % r__centvoidvol          
read(ifile) this % r__bulkcooltemp         
read(ifile) this % r__crackvolume          
read(ifile) this % r__butemp               
read(ifile) this % r__hydrostatpress       
read(ifile) this % r__gasphs               
read(ifile) this % r__hlqcl1               
read(ifile) this % r__dtdkta               
read(ifile) this % r__gaspress0            
read(ifile) this % r__pelsrfstrn0          
read(ifile) this % r__workspaceurc         
read(ifile) this % r__hupta                
read(ifile) this % r__spl                  
read(ifile) this % r__oxuptakeid1          
read(ifile) this % r__fuelsurft            
read(ifile) this % r__aaht1                
read(ifile) this % r__oxconcenaho          
read(ifile) this % r__eppinp               
read(ifile) this % r__ispace               
read(ifile) this % r__pswll0               
read(ifile) this % r__bosoxidethick        
read(ifile) this % r__oxconcenagi          
read(ifile) this % r__dishvperl            
read(ifile) this % r__qpln                 
read(ifile) this % r__sedepriold           
read(ifile) this % r__radialbound          
read(ifile) this % r__explenumt            
read(ifile) this % r__crackwidth           
read(ifile) this % r__edotfz0              
read(ifile) this % r__coolenthalpy         
read(ifile) this % r__dtpoa                
read(ifile) this % r__oldcladt             
read(ifile) this % r__vsn                  
read(ifile) this % r__ureloc               
read(ifile) this % r__afrap                
read(ifile) this % r__efffastflustrnhardexp
read(ifile) this % r__epstrain3old         
read(ifile) this % r__gaspress             
read(ifile) this % r__radpowprofile        
read(ifile) this % r__relfraca             
read(ifile) this % r__effstrainpnnl        
read(ifile) this % r__tz1                  
read(ifile) this % r__emodulus             
read(ifile) this % r__einstabilstrain      
read(ifile) this % r__tschf                
read(ifile) this % r__elvrad               
read(ifile) this % r__oldcladt0            
read(ifile) this % r__oldfuelaxstrn0       
read(ifile) this % r__ansr                 
read(ifile) this % r__gfint                
read(ifile) this % r__pz1                  
read(ifile) this % r__axialpowr0           
read(ifile) this % r__oxygenconcenave      
read(ifile) this % r__a1                   
read(ifile) this % r__zfarbl               
read(ifile) this % r__fuelcentert          
read(ifile) this % r__workspacegapi        
read(ifile) this % r__oldeps               
read(ifile) this % r__hinta                
read(ifile) this % r__oxstalphathknearfuel 
read(ifile) this % r__oxconcenabo          
read(ifile) this % r__avedishtemp          
read(ifile) this % r__gz2                  
read(ifile) this % r__gz1                  
read(ifile) this % r__oldcldaxstrn         
read(ifile) this % r__cooldensity          
read(ifile) this % r__prestm               
read(ifile) this % r__cldpermstrn0         
read(ifile) this % r__elevatfrap           
read(ifile) this % r__pinput               
read(ifile) this % r__htc_v                
read(ifile) this % r__potput               
read(ifile) this % r__oxconcenafi          
read(ifile) this % r__acolct               
read(ifile) this % r__zelev                
read(ifile) this % r__gadolin              
read(ifile) this % r__htc_l                
read(ifile) this % r__oxipowergen          
read(ifile) this % r__icglob               
read(ifile) this % r__nrc                  
read(ifile) this % r__iokold               
read(ifile) this % r__iok                  
read(ifile) this % r__gasavail1            
read(ifile) this % r__tmprlp               
read(ifile) this % r__gasavail2            
read(ifile) this % r__volumeweightr        
read(ifile) this % r__enrgymeltz           
read(ifile) this % r__acond                
read(ifile) this % r__cldthermstrn         
read(ifile) this % r__frapcontemp          
read(ifile) this % r__baln2twall           
read(ifile) this % r__qcold                
read(ifile) this % r__fuelresidstrn        
read(ifile) this % r__tplbt1               
read(ifile) this % r__previteratetemp      
read(ifile) this % r__buradv               
read(ifile) this % r__rhocp0               
read(ifile) this % r__tblka                
read(ifile) this % r__burad                
read(ifile) this % r__htca                 
read(ifile) this % r__enrgymelt            
read(ifile) this % r__cldstrnrat           
read(ifile) this % r__deformedradiusofmesh 
read(ifile) this % r__bosrad               
read(ifile) this % r__pelsrfstrn           
read(ifile) this % r__eosrad               
read(ifile) this % r__radsrc               
read(ifile) this % r__cldplasstrn0         
read(ifile) this % r__cldstress            
read(ifile) this % r__rhocp                
read(ifile) this % r__radialboundo         
read(ifile) this % r__volumeweightl        
read(ifile) this % r__axpowprofile         
read(ifile) this % r__enrgymeltzp1         
read(ifile) this % r__pazp                 
read(ifile) this % r__tpln                 
read(ifile) this % r__radpow               
read(ifile) this % r__areaweight           
read(ifile) this % r__eostemp              
read(ifile) this % r__pchn                 
read(ifile) this % r__trad2                
read(ifile) this % r__trad3                
read(ifile) this % r__trad1                
read(ifile) this % r__gasths               
read(ifile) this % r__fuelrad              
read(ifile) this % r__cldresidstrn0        
read(ifile) this % r__dktouts              
read(ifile) this % r__cldstrnrat0          
read(ifile) this % r__cldplasstrn          
read(ifile) this % r__bufrad               
read(ifile) this % r__radsrco              
read(ifile) this % r__cldresidstrn         
read(ifile) this % r__radtemp              
read(ifile) this % r__workspaceepp1        
read(ifile) this % r__fuelresidstrn0       
read(ifile) this % r__cldelstrn            
read(ifile) this % r__enrgymeltp1          
read(ifile) this % r__tplbot               
read(ifile) this % r__bostemp              
read(ifile) this % r__cldstrn              
read(ifile) this % r__grsv                 
read(ifile) this % r__tplna                
