write(ifile) this % r__convert_units        
write(ifile) this % r__printballoon         
write(ifile) this % r__printrodburst        
write(ifile) this % r__allocate_arrays_ft   
write(ifile) this % r__coupled              
write(ifile) this % r__ndebug               
write(ifile) this % r__dakota               
write(ifile) this % r__setunits             
write(ifile) this % r__first_pass           
write(ifile) this % r__first_call           
write(ifile) this % r__unit                 
write(ifile) this % r__rupflg               
write(ifile) this % r__coolant              
write(ifile) this % r__fraptranfn           
write(ifile) this % r__metal                
write(ifile) this % r__modheatmodel         
write(ifile) this % r__relocmodel           
write(ifile) this % r__lodmrk               
write(ifile) this % r__reflood              
write(ifile) this % r__namerf               
write(ifile) this % r__inst                 
write(ifile) this % r__bheat                
write(ifile) this % r__internal             
write(ifile) this % r__mheat                
write(ifile) this % r__radiation            
write(ifile) this % r__deformation          
write(ifile) this % r__ifaila               
write(ifile) this % r__kaxnlo               
write(ifile) this % r__ncirlp               
write(ifile) this % r__nprsw                
write(ifile) this % r__npbh                 
write(ifile) this % r__nbncal               
write(ifile) this % r__llp                  
write(ifile) this % r__ierr                 
write(ifile) this % r__lcoold               
write(ifile) this % r__nidoxide             
write(ifile) this % r__press                
write(ifile) this % r__cathca               
write(ifile) this % r__klp2                 
write(ifile) this % r__nelrad               
write(ifile) this % r__frapt4               
write(ifile) this % r__ntapou               
write(ifile) this % r__kaxhtc               
write(ifile) this % r__indexthermcon        
write(ifile) this % r__prestmp              
write(ifile) this % r__irupt                
write(ifile) this % r__indxmd               
write(ifile) this % r__nbowr                
write(ifile) this % r__ldialb               
write(ifile) this % r__modbal               
write(ifile) this % r__pressu               
write(ifile) this % r__inlet                
write(ifile) this % r__zone                 
write(ifile) this % r__ndap1                
write(ifile) this % r__nbhtc                
write(ifile) this % r__protectiveoxide      
write(ifile) this % r__rtheta               
write(ifile) this % r__ldir                 
write(ifile) this % r__istoicgrad           
write(ifile) this % r__ifail                
write(ifile) this % r__lchf                 
write(ifile) this % r__itswt                
write(ifile) this % r__pow                  
write(ifile) this % r__nsymm                
write(ifile) this % r__naazp                
write(ifile) this % r__nvol2                
write(ifile) this % r__idebug               
write(ifile) this % r__nvol1                
write(ifile) this % r__mhbh                 
write(ifile) this % r__modfd                
write(ifile) this % r__ixazmn               
write(ifile) this % r__gasflo               
write(ifile) this % r__nbrtmp               
write(ifile) this % r__nbrfdr               
write(ifile) this % r__prescri              
write(ifile) this % r__mbowr                
write(ifile) this % r__mtabl3               
write(ifile) this % r__mechan               
write(ifile) this % r__nfmesh               
write(ifile) this % r__mndchf               
write(ifile) this % r__naazpd               
write(ifile) this % r__npelraddeviat        
write(ifile) this % r__itdmx                
write(ifile) this % r__nhbh                 
write(ifile) this % r__nfrapconinitialization
write(ifile) this % r__ncool                
write(ifile) this % r__nsrad3               
write(ifile) this % r__indexgrainbndsep     
write(ifile) this % r__nedtsw               
write(ifile) this % r__azang                
write(ifile) this % r__m5fc2                
write(ifile) this % r__radiat               
write(ifile) this % r__mhinta               
write(ifile) this % r__luout                
write(ifile) this % r__nmesh                
write(ifile) this % r__mgaspr               
write(ifile) this % r__iagap                
write(ifile) this % r__indxkf               
write(ifile) this % r__nitmin               
write(ifile) this % r__nconsw               
write(ifile) this % r__numdta               
write(ifile) this % r__nhtcz                
write(ifile) this % r__kntbal               
write(ifile) this % r__nrazp                
write(ifile) this % r__iplant               
write(ifile) this % r__indexthermconadv     
write(ifile) this % r__mhlqc1               
write(ifile) this % r__nplnt                
write(ifile) this % r__nbrliq               
write(ifile) this % r__idoxid               
write(ifile) this % r__lcombk               
write(ifile) this % r__indexgeom            
write(ifile) this % r__kbaln                
write(ifile) this % r__nbuq                 
write(ifile) this % r__mtempt               
write(ifile) this % r__maxit                
write(ifile) this % r__nbundl               
write(ifile) this % r__reflo                
write(ifile) this % r__nlac                 
write(ifile) this % r__jchf                 
write(ifile) this % r__ntco                 
write(ifile) this % r__kflgb                
write(ifile) this % r__tape1                
write(ifile) this % r__lengmd               
write(ifile) this % r__tape2                
write(ifile) this % r__nitdt                
write(ifile) this % r__res                  
write(ifile) this % r__la1max               
write(ifile) this % r__jtr                  
write(ifile) this % r__nqbow                
write(ifile) this % r__idx2                 
write(ifile) this % r__geom                 
write(ifile) this % r__mhlqcp               
write(ifile) this % r__lowpl                
write(ifile) this % r__la1fil               
write(ifile) this % r__np                   
write(ifile) this % r__ifcmi                
write(ifile) this % r__ntempf               
write(ifile) this % r__izadfg               
write(ifile) this % r__npdtpo               
write(ifile) this % r__massfl               
write(ifile) this % r__ncards               
write(ifile) this % r__iterationcount       
write(ifile) this % r__itcntd               
write(ifile) this % r__iagap0               
write(ifile) this % r__odoxid               
write(ifile) this % r__ntstep               
write(ifile) this % r__kswell               
write(ifile) this % r__pressure             
write(ifile) this % r__mhupta               
write(ifile) this % r__ndtred               
write(ifile) this % r__nptha                
write(ifile) this % r__ncorlp               
write(ifile) this % r__bowing               
write(ifile) this % r__transwell            
write(ifile) this % r__unitin               
write(ifile) this % r__indexfc2print        
write(ifile) this % r__nepp0                
write(ifile) this % r__ntimesteps           
write(ifile) this % r__nchan                
write(ifile) this % r__nradialnodes         
write(ifile) this % r__mzq1                 
write(ifile) this % r__geometry             
write(ifile) this % r__upppl                
write(ifile) this % r__ruptur               
write(ifile) this % r__geomet               
write(ifile) this % r__nradq                
write(ifile) this % r__lcolct               
write(ifile) this % r__noiter               
write(ifile) this % r__nchfmd               
write(ifile) this % r__nchn                 
write(ifile) this % r__lresr2               
write(ifile) this % r__ntimes               
write(ifile) this % r__nfhtc                
write(ifile) this % r__lresr1               
write(ifile) this % r__mpbh                 
write(ifile) this % r__ncmesh               
write(ifile) this % r__nsc                  
write(ifile) this % r__indxkc               
write(ifile) this % r__ndim                 
write(ifile) this % r__naxn                 
write(ifile) this % r__lflect               
write(ifile) this % r__ns                   
write(ifile) this % r__nradsh               
write(ifile) this % r__lprntb               
write(ifile) this % r__mprest               
write(ifile) this % r__dktoutcounter        
write(ifile) this % r__nsf                  
write(ifile) this % r__ncooli               
write(ifile) this % r__m6fc2                
write(ifile) this % r__indxpr               
write(ifile) this % r__jmnbal               
write(ifile) this % r__modmw                
write(ifile) this % r__ncard2               
write(ifile) this % r__lsclr1               
write(ifile) this % r__nprad                
write(ifile) this % r__nhtca                
write(ifile) this % r__knonue               
write(ifile) this % r__chf                  
write(ifile) this % r__irefine              
write(ifile) this % r__mgbh                 
write(ifile) this % r__ndktparams           
write(ifile) this % r__lsclr2               
write(ifile) this % r__lsclr3               
write(ifile) this % r__defsize              
write(ifile) this % r__nflec                
write(ifile) this % r__lblona               
write(ifile) this % r__nodpln               
write(ifile) this % r__nrestart             
write(ifile) this % r__lafrap               
write(ifile) this % r__coreav               
write(ifile) this % r__nfuelswellpairs      
write(ifile) this % r__nswmd                
write(ifile) this % r__nvoid                
write(ifile) this % r__lmatpc               
write(ifile) this % r__inpfil               
write(ifile) this % r__numaxprofiles        
write(ifile) this % r__nkc                  
write(ifile) this % r__nomat                
write(ifile) this % r__nkf                  
write(ifile) this % r__nfgrpairs            
write(ifile) this % r__nhtclv               
write(ifile) this % r__npaxp                
write(ifile) this % r__ncool2               
write(ifile) this % r__kmxrlp               
write(ifile) this % r__kmxfrp               
write(ifile) this % r__indexbc              
write(ifile) this % r__ncall                
write(ifile) this % r__ndtmax               
write(ifile) this % r__naxialnodes          
write(ifile) this % r__soltyp               
write(ifile) this % r__nptha1               
write(ifile) this % r__ntplot               
write(ifile) this % r__ns2                  
write(ifile) this % r__nce                  
write(ifile) this % r__modkf                
write(ifile) this % r__mtabl1               
write(ifile) this % r__mtabl2               
write(ifile) this % r__nbalsw               
write(ifile) this % r__ixazim               
write(ifile) this % r__temp                 
write(ifile) this % r__indexinittemp        
write(ifile) this % r__cenvoi               
write(ifile) this % r__nrefld               
write(ifile) this % r__ndtad                
write(ifile) this % r__ntabl1               
write(ifile) this % r__nbrfht               
write(ifile) this % r__nqchn                
write(ifile) this % r__klp                  
write(ifile) this % r__npid                 
write(ifile) this % r__nforlp               
write(ifile) this % r__nswinw               
write(ifile) this % r__grass                
write(ifile) this % r__mpdcay               
write(ifile) this % r__baker                
write(ifile) this % r__spefbz               
write(ifile) this % r__ncolbp               
write(ifile) this % r__nt5                  
write(ifile) this % r__mwork                
write(ifile) this % r__nbrpst               
write(ifile) this % r__jpl                  
write(ifile) this % r__presfgr              
write(ifile) this % r__mbdl                 
write(ifile) this % r__nerr                 
write(ifile) this % r__inp                  
write(ifile) this % r__iflagn               
write(ifile) this % r__nhinta               
write(ifile) this % r__lthyd                
write(ifile) this % r__indexfintemp         
write(ifile) this % r__nnaz                 
write(ifile) this % r__npaxp1               
write(ifile) this % r__nrazpd               
write(ifile) this % r__mflt                 
write(ifile) this % r__maximumiterations    
write(ifile) this % r__npramp               
write(ifile) this % r__nzmesh               
write(ifile) this % r__nprofile             
write(ifile) this % r__igpnod               
write(ifile) this % r__npair                
write(ifile) this % r__coldwa               
write(ifile) this % r__refloodtime          
write(ifile) this % r__ngbh                 
write(ifile) this % r__lphypr               
write(ifile) this % r__ifbaln               
write(ifile) this % r__nrest2               
write(ifile) this % r__length               
write(ifile) this % r__nfastf               
write(ifile) this % r__nthermex             
write(ifile) this % r__lhtc                 
write(ifile) this % r__naz                  
write(ifile) this % r__nvol                 
write(ifile) this % r__imox                 
write(ifile) this % r__nt                   
write(ifile) this % r__maxidx               
write(ifile) this % r__lhtcb                
write(ifile) this % r__collaps              
write(ifile) this % r__profile              
write(ifile) this % r__nucbo                
write(ifile) this % r__filmbo               
write(ifile) this % r__cladtype             
write(ifile) this % r__ndtadv               
write(ifile) this % r__ncladi               
write(ifile) this % r__npaxpf               
write(ifile) this % r__jfb                  
write(ifile) this % r__n4                   
write(ifile) this % r__nhtc                 
write(ifile) this % r__ngasr                
write(ifile) this % r__ithymx               
write(ifile) this % r__ifailue              
write(ifile) this % r__axpow                
write(ifile) this % r__n1                   
write(ifile) this % r__nsteadytrans         
write(ifile) this % r__nprntb               
write(ifile) this % r__nbotpl               
write(ifile) this % r__nsym                 
write(ifile) this % r__la1req               
write(ifile) this % r__noball               
write(ifile) this % r__kbot                 
write(ifile) this % r__n3                   
write(ifile) this % r__lresi3               
write(ifile) this % r__lresi2               
write(ifile) this % r__liquid               
write(ifile) this % r__nodprm               
write(ifile) this % r__ngaspr               
write(ifile) this % r__ntabl3               
write(ifile) this % r__ntabl2               
write(ifile) this % r__iflago               
write(ifile) this % r__indx                 
write(ifile) this % r__ndktn                
write(ifile) this % r__npltn                
write(ifile) this % r__unitout              
write(ifile) this % r__ifchk                
write(ifile) this % r__plenumtemp           
write(ifile) this % r__lexcb                
write(ifile) this % r__kdbug                
write(ifile) this % r__n2                   
write(ifile) this % r__gammait              
write(ifile) this % r__liqnod               
write(ifile) this % r__nhupta               
write(ifile) this % r__irup                 
write(ifile) this % r__splbp                
write(ifile) this % r__tpowf                
write(ifile) this % r__kappag               
write(ifile) this % r__dtpo                 
write(ifile) this % r__refdtm               
write(ifile) this % r__achn                 
write(ifile) this % r__prodxe               
write(ifile) this % r__pdeint               
write(ifile) this % r__zbaln                
write(ifile) this % r__tplenb               
write(ifile) this % r__tflood               
write(ifile) this % r__kappaf               
write(ifile) this % r__sigcladthermcond     
write(ifile) this % r__pitch                
write(ifile) this % r__dcldh                
write(ifile) this % r__cnfsol               
write(ifile) this % r__gasmoles0            
write(ifile) this % r__tfoldf               
write(ifile) this % r__bowthr               
write(ifile) this % r__hrad                 
write(ifile) this % r__dofang               
write(ifile) this % r__t0f                  
write(ifile) this % r__pressr               
write(ifile) this % r__t0c                  
write(ifile) this % r__maxenthalpy          
write(ifile) this % r__tp1bal               
write(ifile) this % r__tmaxf                
write(ifile) this % r__tt                   
write(ifile) this % r__rmpbal               
write(ifile) this % r__qlbal                
write(ifile) this % r__frden                
write(ifile) this % r__vsubg                
write(ifile) this % r__vsubf                
write(ifile) this % r__dtbal                
write(ifile) this % r__delth                
write(ifile) this % r__prodkr               
write(ifile) this % r__tshtc                
write(ifile) this % r__cexh2l               
write(ifile) this % r__zpkfc                
write(ifile) this % r__htcgba               
write(ifile) this % r__frbal                
write(ifile) this % r__reflpr               
write(ifile) this % r__qbal                 
write(ifile) this % r__pelh                 
write(ifile) this % r__arean                
write(ifile) this % r__zndbal               
write(ifile) this % r__t12                  
write(ifile) this % r__debugtime            
write(ifile) this % r__pavg                 
write(ifile) this % r__aidsht               
write(ifile) this % r__rl                   
write(ifile) this % r__maxcladtemp          
write(ifile) this % r__dtheta               
write(ifile) this % r__hsubf                
write(ifile) this % r__gapconductivity      
write(ifile) this % r__cpmult               
write(ifile) this % r__fdelta               
write(ifile) this % r__sigfuelthermexp      
write(ifile) this % r__totnb                
write(ifile) this % r__sigcladthermexp      
write(ifile) this % r__timop                
write(ifile) this % r__src2                 
write(ifile) this % r__flowbk               
write(ifile) this % r__totalvoidvol         
write(ifile) this % r__htcbal               
write(ifile) this % r__powop                
write(ifile) this % r__tplen                
write(ifile) this % r__flxsec               
write(ifile) this % r__t2                   
write(ifile) this % r__t0                   
write(ifile) this % r__t1                   
write(ifile) this % r__ffch                 
write(ifile) this % r__dtenfb               
write(ifile) this % r__crf                  
write(ifile) this % r__fpdcay               
write(ifile) this % r__debugtimestop        
write(ifile) this % r__roughc               
write(ifile) this % r__x                    
write(ifile) this % r__chstrs               
write(ifile) this % r__roughf               
write(ifile) this % r__dtenfo               
write(ifile) this % r__drod                 
write(ifile) this % r__jhtc                 
write(ifile) this % r__hliq                 
write(ifile) this % r__rfbal                
write(ifile) this % r__pctop                
write(ifile) this % r__prsacc               
write(ifile) this % r__tprlp                
write(ifile) this % r__relfract             
write(ifile) this % r__fpowr                
write(ifile) this % r__gum                  
write(ifile) this % r__gpthk0               
write(ifile) this % r__tref                 
write(ifile) this % r__ftmelt               
write(ifile) this % r__zs                   
write(ifile) this % r__tc0bal               
write(ifile) this % r__tgbal                
write(ifile) this % r__apowrd               
write(ifile) this % r__rodlength            
write(ifile) this % r__psat                 
write(ifile) this % r__srcv2                
write(ifile) this % r__time0                
write(ifile) this % r__flxbal               
write(ifile) this % r__fuelrd               
write(ifile) this % r__zmesh                
write(ifile) this % r__rf                   
write(ifile) this % r__ctmelt               
write(ifile) this % r__htflxa               
write(ifile) this % r__pdrato               
write(ifile) this % r__templo               
write(ifile) this % r__zro                  
write(ifile) this % r__drflt                
write(ifile) this % r__tgas0                
write(ifile) this % r__swllfr               
write(ifile) this % r__gsmfrp               
write(ifile) this % r__modheat              
write(ifile) this % r__spdbp                
write(ifile) this % r__pfail                
write(ifile) this % r__cladid               
write(ifile) this % r__fldrpr               
write(ifile) this % r__nu3                  
write(ifile) this % r__pmxbal               
write(ifile) this % r__nu1                  
write(ifile) this % r__timmd                
write(ifile) this % r__aidtot               
write(ifile) this % r__aidsur               
write(ifile) this % r__tsub                 
write(ifile) this % r__sigcladyieldstr      
write(ifile) this % r__fabal                
write(ifile) this % r__rhoc                 
write(ifile) this % r__tflux                
write(ifile) this % r__rhof                 
write(ifile) this % r__tdbugd               
write(ifile) this % r__sigfuelheatcapa      
write(ifile) this % r__deloxy               
write(ifile) this % r__r8bal                
write(ifile) this % r__z                    
write(ifile) this % r__delth0               
write(ifile) this % r__tmax                 
write(ifile) this % r__qmax                 
write(ifile) this % r__chefus               
write(ifile) this % r__trabal               
write(ifile) this % r__rcpar                
write(ifile) this % r__pressi               
write(ifile) this % r__t22                  
write(ifile) this % r__ffchf                
write(ifile) this % r__roddiameter          
write(ifile) this % r__coolantpress         
write(ifile) this % r__ruplev               
write(ifile) this % r__epsht1               
write(ifile) this % r__h0bal                
write(ifile) this % r__tmaxc                
write(ifile) this % r__zad                  
write(ifile) this % r__tranfuelswell        
write(ifile) this % r__csubp                
write(ifile) this % r__cladpower            
write(ifile) this % r__src1                 
write(ifile) this % r__rshrd                
write(ifile) this % r__dppowi               
write(ifile) this % r__zqch                 
write(ifile) this % r__frcoef               
write(ifile) this % r__empytm               
write(ifile) this % r__zroug2               
write(ifile) this % r__frchmx               
write(ifile) this % r__tbkbal               
write(ifile) this % r__timbal               
write(ifile) this % r__pcbal                
write(ifile) this % r__plenumgasmoles       
write(ifile) this % r__xtime                
write(ifile) this % r__doffst               
write(ifile) this % r__hsubg                
write(ifile) this % r__powimx               
write(ifile) this % r__buoxide              
write(ifile) this % r__fltgap               
write(ifile) this % r__psbal                
write(ifile) this % r__emptm                
write(ifile) this % r__dvdtp                
write(ifile) this % r__tm1bal               
write(ifile) this % r__trise                
write(ifile) this % r__usubf                
write(ifile) this % r__usubg                
write(ifile) this % r__fltgap2              
write(ifile) this % r__hydiam               
write(ifile) this % r__dishd                
write(ifile) this % r__beta1                
write(ifile) this % r__cldwdc               
write(ifile) this % r__cpstem               
write(ifile) this % r__tplot                
write(ifile) this % r__csubpg               
write(ifile) this % r__csubpf               
write(ifile) this % r__tfavba               
write(ifile) this % r__fotmtl               
write(ifile) this % r__timeincrement        
write(ifile) this % r__tmpac1               
write(ifile) this % r__sigfuelthermcond     
write(ifile) this % r__crfpr                
write(ifile) this % r__sigsurfhtc           
write(ifile) this % r__trecrd               
write(ifile) this % r__emwbal               
write(ifile) this % r__cladod               
write(ifile) this % r__ruptstrain           
write(ifile) this % r__zqchpr               
write(ifile) this % r__tsntrk               
write(ifile) this % r__rsntr                
write(ifile) this % r__nu2                  
write(ifile) this % r__volavegastemp        
write(ifile) this % r__zroug1               
write(ifile) this % r__aidlng               
write(ifile) this % r__rhostm               
write(ifile) this % r__ph                   
write(ifile) this % r__coldbp               
write(ifile) this % r__tempmx               
write(ifile) this % r__betag                
write(ifile) this % r__betaf                
write(ifile) this % r__kappa                
write(ifile) this % r__cfluxa               
write(ifile) this % r__dtold                
write(ifile) this % r__zvoid1               
write(ifile) this % r__atop                 
write(ifile) this % r__rvoid                
write(ifile) this % r__qaxpk                
write(ifile) this % r__dofset               
write(ifile) this % r__tf0bal               
write(ifile) this % r__ubar                 
write(ifile) this % r__pl                   
write(ifile) this % r__v                    
write(ifile) this % r__tdkt                 
write(ifile) this % r__dtp                  
write(ifile) this % r__totalgasmoles        
write(ifile) this % r__refine               
write(ifile) this % r__gflow                
write(ifile) this % r__gfloa1               
write(ifile) this % r__temphi               
write(ifile) this % r__frchdt               
write(ifile) this % r__fhtc                 
write(ifile) this % r__frpo2                
write(ifile) this % r__trest                
write(ifile) this % r__fgrns                
write(ifile) this % r__dtmpcl               
write(ifile) this % r__areao                
write(ifile) this % r__pfnuc                
write(ifile) this % r__r0bal                
write(ifile) this % r__fuelpeldiam          
write(ifile) this % r__tsatt                
write(ifile) this % r__pdecy                
write(ifile) this % r__ztmax                
write(ifile) this % r__zqflt                
write(ifile) this % r__fldrte               
write(ifile) this % r__coldw                
write(ifile) this % r__openporosityfraction 
write(ifile) this % r__dhe                  
write(ifile) this % r__explenumv            
write(ifile) this % r__compmt               
write(ifile) this % r__maxgaspressure       
write(ifile) this % r__dtss                 
write(ifile) this % r__oldtim               
write(ifile) this % r__dhy                  
write(ifile) this % r__tc1                  
write(ifile) this % r__volbp                
write(ifile) this % r__bup                  
write(ifile) this % r__fhefus               
write(ifile) this % r__powict               
write(ifile) this % r__fr                   
write(ifile) this % r__pois                 
write(ifile) this % r__dtobal               
write(ifile) this % r__dcldh0               
write(ifile) this % r__pavgft               
write(ifile) this % r__tc2                  
write(ifile) this % r__gsms                 
write(ifile) this % r__time                 
write(ifile) this % r__taxbal               
write(ifile) this % r__trodfc               
write(ifile) this % r__dishv0               
write(ifile) this % r__beta                 
write(ifile) this % r__tpo                  
write(ifile) this % r__cladtk               
write(ifile) this % r__zm1bal               
write(ifile) this % r__dzmesh               
write(ifile) this % r__toldfc               
write(ifile) this % r__rnbnt                
write(ifile) this % r__defaulttemp          
write(ifile) this % r__hbar                 
write(ifile) this % r__e                    
write(ifile) this % r__gapthk               
write(ifile) this % r__zbot                 
write(ifile) this % r__vplenc               
write(ifile) this % r__vplenb               
write(ifile) this % r__bottomplenumgasmoles 
write(ifile) this % r__bumtp                
write(ifile) this % r__zvoid2               
write(ifile) this % r__zp1bal               
write(ifile) this % r__fqcrit               
write(ifile) this % r__rshd                 
write(ifile) this % r__tcebal               
write(ifile) this % r__tempcs               
write(ifile) this % r__maxfueltemp          
write(ifile) this % r__pfflec               
write(ifile) this % r__gapmin               
write(ifile) this % r__cnfliq               
write(ifile) this % r__emflag               
write(ifile) this % r__ifstor               
write(ifile) this % r__ichf                 
write(ifile) this % r__nswpm                
write(ifile) this % r__tem                  
write(ifile) this % r__imaterials           
write(ifile) this % r__modfal               
write(ifile) this % r__idumr1               
write(ifile) this % r__ih                   
write(ifile) this % r__iffrp                
write(ifile) this % r__ihtreg               
write(ifile) this % r__indxjk               
write(ifile) this % r__ibnopt               
write(ifile) this % r__ruptfailindex        
write(ifile) this % r__nm                   
write(ifile) this % r__ies                  
write(ifile) this % r__nopt                 
write(ifile) this % r__indexpcmionce        
write(ifile) this % r__cladcollapseindex    
write(ifile) this % r__rodfailindex         
write(ifile) this % r__gapindex             
write(ifile) this % r__irest2               
write(ifile) this % r__imatflag             
write(ifile) this % r__oldgapindex          
write(ifile) this % r__htco                 
write(ifile) this % r__indextempconverg     
write(ifile) this % r__bosgapindex          
write(ifile) this % r__idatapairs           
write(ifile) this % r__ncs                  
write(ifile) this % r__nvprs                
write(ifile) this % r__npprs                
write(ifile) this % r__irest3               
write(ifile) this % r__bosgapindex0         
write(ifile) this % r__ntprs                
write(ifile) this % r__ihdata               
write(ifile) this % r__imatflag1            
write(ifile) this % r__cladcollindx0        
write(ifile) this % r__nunopt               
write(ifile) this % r__nhprs                
write(ifile) this % r__nodesintertemp       
write(ifile) this % r__ngastmp              
write(ifile) this % r__ndchfi               
write(ifile) this % r__iheattablen          
write(ifile) this % r__indexpcmi            
write(ifile) this % r__numazmuthnod         
write(ifile) this % r__roi                  
write(ifile) this % r__alphathk11           
write(ifile) this % r__tbulk_v              
write(ifile) this % r__cladenrgperl         
write(ifile) this % r__efffastflustrencoef  
write(ifile) this % r__scd                  
write(ifile) this % r__watrmetlenrgy        
write(ifile) this % r__coolpress            
write(ifile) this % r__dtplta               
write(ifile) this % r__oxconcenaio          
write(ifile) this % r__apln                 
write(ifile) this % r__oxygenuptake         
write(ifile) this % r__thermalconductadv    
write(ifile) this % r__ascal2               
write(ifile) this % r__gasax                
write(ifile) this % r__profilestarttime     
write(ifile) this % r__ascal1               
write(ifile) this % r__htflxfac             
write(ifile) this % r__htclev               
write(ifile) this % r__tbulk_l              
write(ifile) this % r__prop                 
write(ifile) this % r__oxconcenado          
write(ifile) this % r__flwblk               
write(ifile) this % r__tempfc               
write(ifile) this % r__oxconcenadi          
write(ifile) this % r__rinterfacgap         
write(ifile) this % r__stressatinststrain   
write(ifile) this % r__rinterfacprs0        
write(ifile) this % r__ts                   
write(ifile) this % r__tp                   
write(ifile) this % r__claddingpower        
write(ifile) this % r__oldcoolprs0          
write(ifile) this % r__voidvolumeratio      
write(ifile) this % r__techf                
write(ifile) this % r__eosoxidethick        
write(ifile) this % r__cexh2a               
write(ifile) this % r__pelraddeviat         
write(ifile) this % r__coolenthalpy0        
write(ifile) this % r__epstrain1old         
write(ifile) this % r__azpang               
write(ifile) this % r__coolmassflx          
write(ifile) this % r__hmaxinitial          
write(ifile) this % r__betathickness        
write(ifile) this % r__oxstalphathkremain   
write(ifile) this % r__powave               
write(ifile) this % r__axburnup             
write(ifile) this % r__apln0                
write(ifile) this % r__alphathk1            
write(ifile) this % r__amatpc               
write(ifile) this % r__fdial                
write(ifile) this % r__vrlfrp               
write(ifile) this % r__rinterfacprs         
write(ifile) this % r__energyperl           
write(ifile) this % r__dvdt                 
write(ifile) this % r__effcoldwkstrnhardexp 
write(ifile) this % r__gapthick0            
write(ifile) this % r__oxconcenaci          
write(ifile) this % r__gbse                 
write(ifile) this % r__fmgp                 
write(ifile) this % r__oldcoolprs           
write(ifile) this % r__sshgap               
write(ifile) this % r__workspacetcmx        
write(ifile) this % r__sedpnnlold           
write(ifile) this % r__heatflux             
write(ifile) this % r__boundarycondition    
write(ifile) this % r__gadoln               
write(ifile) this % r__oxconcenaco          
write(ifile) this % r__gfrac                
write(ifile) this % r__radialpower          
write(ifile) this % r__stressaxialold       
write(ifile) this % r__surfhtflux           
write(ifile) this % r__oldcldplasstrn       
write(ifile) this % r__gbh                  
write(ifile) this % r__prevtemp             
write(ifile) this % r__workspacereloc       
write(ifile) this % r__pelletrad0           
write(ifile) this % r__rmrlp                
write(ifile) this % r__hz2                  
write(ifile) this % r__fastflux             
write(ifile) this % r__bbht1                
write(ifile) this % r__pbh                  
write(ifile) this % r__gaptemp              
write(ifile) this % r__arest1               
write(ifile) this % r__dvdt0                
write(ifile) this % r__drdfrp               
write(ifile) this % r__oldgasprs            
write(ifile) this % r__fuelgasswell         
write(ifile) this % r__oxuptakeid2          
write(ifile) this % r__stresshoopold        
write(ifile) this % r__effcoldwkstrencoef   
write(ifile) this % r__oxconcenago          
write(ifile) this % r__rodod0               
write(ifile) this % r__dtmaxa               
write(ifile) this % r__pelletrad            
write(ifile) this % r__edint                
write(ifile) this % r__alphathk2            
write(ifile) this % r__axialpowr            
write(ifile) this % r__pelsrfdispl          
write(ifile) this % r__hgapav               
write(ifile) this % r__tmelt                
write(ifile) this % r__temptm               
write(ifile) this % r__enthl                
write(ifile) this % r__flthit               
write(ifile) this % r__bpln                 
write(ifile) this % r__cladmaxt             
write(ifile) this % r__qaxzq                
write(ifile) this % r__oxconcenaii          
write(ifile) this % r__vfrad1               
write(ifile) this % r__vfrad3               
write(ifile) this % r__vfrad2               
write(ifile) this % r__oxconcenafo          
write(ifile) this % r__tend                 
write(ifile) this % r__aexcb                
write(ifile) this % r__sedepri              
write(ifile) this % r__alphathk22           
write(ifile) this % r__oxithk1              
write(ifile) this % r__bufrp                
write(ifile) this % r__hz1                  
write(ifile) this % r__swelldispl           
write(ifile) this % r__oxithk2              
write(ifile) this % r__tshrda               
write(ifile) this % r__vs0                  
write(ifile) this % r__acoold               
write(ifile) this % r__hgpfrp               
write(ifile) this % r__hlqcl                
write(ifile) this % r__finaltemp            
write(ifile) this % r__techfi               
write(ifile) this % r__pbh1                 
write(ifile) this % r__pbh2                 
write(ifile) this % r__aflcht               
write(ifile) this % r__bu                   
write(ifile) this % r__ecr                  
write(ifile) this % r__vreloc0              
write(ifile) this % r__epstrain2old         
write(ifile) this % r__hlqclp               
write(ifile) this % r__bpln0                
write(ifile) this % r__pz2                  
write(ifile) this % r__cesiumcontent        
write(ifile) this % r__z1                   
write(ifile) this % r__z2                   
write(ifile) this % r__faxzq                
write(ifile) this % r__fluxz                
write(ifile) this % r__gapthick             
write(ifile) this % r__hbh                  
write(ifile) this % r__oldepeff             
write(ifile) this % r__oldeffstrainpnnl     
write(ifile) this % r__cladavetemp          
write(ifile) this % r__nodchf               
write(ifile) this % r__oldgasprs0           
write(ifile) this % r__aasth                
write(ifile) this % r__aprntb               
write(ifile) this % r__volopenpor           
write(ifile) this % r__farbal               
write(ifile) this % r__extentofbow          
write(ifile) this % r__oldcldaxstrn0        
write(ifile) this % r__sdfar                
write(ifile) this % r__ablona               
write(ifile) this % r__cladeffstress        
write(ifile) this % r__rodavepower          
write(ifile) this % r__gasmolesax0          
write(ifile) this % r__cooldensity0         
write(ifile) this % r__ascal3               
write(ifile) this % r__arrayf               
write(ifile) this % r__oldpeldis            
write(ifile) this % r__edotfz               
write(ifile) this % r__workspacerco         
write(ifile) this % r__workspaceep1         
write(ifile) this % r__cldpermstrn          
write(ifile) this % r__hydrogencontent      
write(ifile) this % r__gasfraction          
write(ifile) this % r__tz2                  
write(ifile) this % r__workspacerci         
write(ifile) this % r__hfusn                
write(ifile) this % r__prcntsatbeta         
write(ifile) this % r__qpln0                
write(ifile) this % r__oxconcenaai          
write(ifile) this % r__oldpeldis0           
write(ifile) this % r__flowg                
write(ifile) this % r__oxconcenaao          
write(ifile) this % r__iodinecontent        
write(ifile) this % r__oldfuelaxstrn        
write(ifile) this % r__terfacepres          
write(ifile) this % r__axnodelevat          
write(ifile) this % r__cladsurft            
write(ifile) this % r__oxconcenabi          
write(ifile) this % r__cladyieldstress      
write(ifile) this % r__oxideid              
write(ifile) this % r__swd                  
write(ifile) this % r__tschfi               
write(ifile) this % r__strainrateterm       
write(ifile) this % r__hsolold              
write(ifile) this % r__gasmolesax           
write(ifile) this % r__hfxsum               
write(ifile) this % r__pclrlp               
write(ifile) this % r__elevatthermhydr      
write(ifile) this % r__timeofgbsep          
write(ifile) this % r__effstrain0           
write(ifile) this % r__oxideod              
write(ifile) this % r__coolqual             
write(ifile) this % r__crithtflux           
write(ifile) this % r__axialnodlen          
write(ifile) this % r__oxconcenahi          
write(ifile) this % r__effstrain            
write(ifile) this % r__filmcoeffav          
write(ifile) this % r__workspacepint        
write(ifile) this % r__sedpnnl              
write(ifile) this % r__heatflux0            
write(ifile) this % r__rmassflux            
write(ifile) this % r__qmaxmelt             
write(ifile) this % r__cldpermhoopstrn      
write(ifile) this % r__stressradialold      
write(ifile) this % r__fuelsrfstrrat        
write(ifile) this % r__cladeffstressold     
write(ifile) this % r__oxconcenaeo          
write(ifile) this % r__cracktemp            
write(ifile) this % r__thermalconductivity  
write(ifile) this % r__fldrat               
write(ifile) this % r__qmaxmeltp1           
write(ifile) this % r__pgpfrp               
write(ifile) this % r__radpel               
write(ifile) this % r__oxconcenaei          
write(ifile) this % r__coefm                
write(ifile) this % r__coefn                
write(ifile) this % r__coefk                
write(ifile) this % r__openportemp          
write(ifile) this % r__rodod                
write(ifile) this % r__fuelsrfstrrat0       
write(ifile) this % r__deltox               
write(ifile) this % r__vreloc               
write(ifile) this % r__cldpermaxstrn        
write(ifile) this % r__fmesh                
write(ifile) this % r__pelprm               
write(ifile) this % r__workspacegap         
write(ifile) this % r__cmesh                
write(ifile) this % r__gsmol0               
write(ifile) this % r__openporvol           
write(ifile) this % r__bowrat               
write(ifile) this % r__gappr0               
write(ifile) this % r__vplen                
write(ifile) this % r__arraye               
write(ifile) this % r__openporosity         
write(ifile) this % r__centvoidvol          
write(ifile) this % r__bulkcooltemp         
write(ifile) this % r__crackvolume          
write(ifile) this % r__butemp               
write(ifile) this % r__hydrostatpress       
write(ifile) this % r__gasphs               
write(ifile) this % r__hlqcl1               
write(ifile) this % r__dtdkta               
write(ifile) this % r__gaspress0            
write(ifile) this % r__pelsrfstrn0          
write(ifile) this % r__workspaceurc         
write(ifile) this % r__hupta                
write(ifile) this % r__spl                  
write(ifile) this % r__oxuptakeid1          
write(ifile) this % r__fuelsurft            
write(ifile) this % r__aaht1                
write(ifile) this % r__oxconcenaho          
write(ifile) this % r__eppinp               
write(ifile) this % r__ispace               
write(ifile) this % r__pswll0               
write(ifile) this % r__bosoxidethick        
write(ifile) this % r__oxconcenagi          
write(ifile) this % r__dishvperl            
write(ifile) this % r__qpln                 
write(ifile) this % r__sedepriold           
write(ifile) this % r__radialbound          
write(ifile) this % r__explenumt            
write(ifile) this % r__crackwidth           
write(ifile) this % r__edotfz0              
write(ifile) this % r__coolenthalpy         
write(ifile) this % r__dtpoa                
write(ifile) this % r__oldcladt             
write(ifile) this % r__vsn                  
write(ifile) this % r__ureloc               
write(ifile) this % r__afrap                
write(ifile) this % r__efffastflustrnhardexp
write(ifile) this % r__epstrain3old         
write(ifile) this % r__gaspress             
write(ifile) this % r__radpowprofile        
write(ifile) this % r__relfraca             
write(ifile) this % r__effstrainpnnl        
write(ifile) this % r__tz1                  
write(ifile) this % r__emodulus             
write(ifile) this % r__einstabilstrain      
write(ifile) this % r__tschf                
write(ifile) this % r__elvrad               
write(ifile) this % r__oldcladt0            
write(ifile) this % r__oldfuelaxstrn0       
write(ifile) this % r__ansr                 
write(ifile) this % r__gfint                
write(ifile) this % r__pz1                  
write(ifile) this % r__axialpowr0           
write(ifile) this % r__oxygenconcenave      
write(ifile) this % r__a1                   
write(ifile) this % r__zfarbl               
write(ifile) this % r__fuelcentert          
write(ifile) this % r__workspacegapi        
write(ifile) this % r__oldeps               
write(ifile) this % r__hinta                
write(ifile) this % r__oxstalphathknearfuel 
write(ifile) this % r__oxconcenabo          
write(ifile) this % r__avedishtemp          
write(ifile) this % r__gz2                  
write(ifile) this % r__gz1                  
write(ifile) this % r__oldcldaxstrn         
write(ifile) this % r__cooldensity          
write(ifile) this % r__prestm               
write(ifile) this % r__cldpermstrn0         
write(ifile) this % r__elevatfrap           
write(ifile) this % r__pinput               
write(ifile) this % r__htc_v                
write(ifile) this % r__potput               
write(ifile) this % r__oxconcenafi          
write(ifile) this % r__acolct               
write(ifile) this % r__zelev                
write(ifile) this % r__gadolin              
write(ifile) this % r__htc_l                
write(ifile) this % r__oxipowergen          
write(ifile) this % r__icglob               
write(ifile) this % r__nrc                  
write(ifile) this % r__iokold               
write(ifile) this % r__iok                  
write(ifile) this % r__gasavail1            
write(ifile) this % r__tmprlp               
write(ifile) this % r__gasavail2            
write(ifile) this % r__volumeweightr        
write(ifile) this % r__enrgymeltz           
write(ifile) this % r__acond                
write(ifile) this % r__cldthermstrn         
write(ifile) this % r__frapcontemp          
write(ifile) this % r__baln2twall           
write(ifile) this % r__qcold                
write(ifile) this % r__fuelresidstrn        
write(ifile) this % r__tplbt1               
write(ifile) this % r__previteratetemp      
write(ifile) this % r__buradv               
write(ifile) this % r__rhocp0               
write(ifile) this % r__tblka                
write(ifile) this % r__burad                
write(ifile) this % r__htca                 
write(ifile) this % r__enrgymelt            
write(ifile) this % r__cldstrnrat           
write(ifile) this % r__deformedradiusofmesh 
write(ifile) this % r__bosrad               
write(ifile) this % r__pelsrfstrn           
write(ifile) this % r__eosrad               
write(ifile) this % r__radsrc               
write(ifile) this % r__cldplasstrn0         
write(ifile) this % r__cldstress            
write(ifile) this % r__rhocp                
write(ifile) this % r__radialboundo         
write(ifile) this % r__volumeweightl        
write(ifile) this % r__axpowprofile         
write(ifile) this % r__enrgymeltzp1         
write(ifile) this % r__pazp                 
write(ifile) this % r__tpln                 
write(ifile) this % r__radpow               
write(ifile) this % r__areaweight           
write(ifile) this % r__eostemp              
write(ifile) this % r__pchn                 
write(ifile) this % r__trad2                
write(ifile) this % r__trad3                
write(ifile) this % r__trad1                
write(ifile) this % r__gasths               
write(ifile) this % r__fuelrad              
write(ifile) this % r__cldresidstrn0        
write(ifile) this % r__dktouts              
write(ifile) this % r__cldstrnrat0          
write(ifile) this % r__cldplasstrn          
write(ifile) this % r__bufrad               
write(ifile) this % r__radsrco              
write(ifile) this % r__cldresidstrn         
write(ifile) this % r__radtemp              
write(ifile) this % r__workspaceepp1        
write(ifile) this % r__fuelresidstrn0       
write(ifile) this % r__cldelstrn            
write(ifile) this % r__enrgymeltp1          
write(ifile) this % r__tplbot               
write(ifile) this % r__bostemp              
write(ifile) this % r__cldstrn              
write(ifile) this % r__grsv                 
write(ifile) this % r__tplna                
write(ifile) this % r__axlinpower