module frapi

    use conversions_frapcon
    use conversions_fraptran, only : coneu
    use frapcon4,  only : frapcon_driver
    use fraptran2, only : fraptran_driver
    use m_if_a_else_b, only : if_a_else_b

    implicit none

    real(8), parameter :: intoum = 25.4D+3
    real(8), parameter :: fttom = 0.3048D+0
    real(8), parameter :: fttomm = 0.3048D+3 !3.28084D+3
    real(8), parameter :: mmtoin = 1.D0/25.4D0

    type, public :: t_fuelrod
        type( frapcon_driver) :: dfcon              ! Burnup steady-state calculations
        type(fraptran_driver) :: dftran             ! Transient calculations
        logical               :: is_initdone        ! The flag is about whether initialization has been finished or not yet
        character(len=200)    :: namerf             ! Name of the restart file generated by frapcon for further fraptran running
    contains
        procedure :: make      => frod_make         ! Initialize the fuel rod
        procedure :: init      => frod_init         ! Set the initial fuel rod state, t = 0
        procedure :: next      => frod_next         ! Perform the trial time step, dt > 0
        procedure :: save      => frod_save         ! Save fuel rod state to local memory
        procedure :: load      => frod_load         ! Load fuel rod state from the local memory
        procedure :: makerf    => frod_makerf       ! Make restart file for futher fraptran running

        ! old interface: ---------------------------------------------------
        procedure :: set_value => frod_set_r8_0    ! Set variable value
        procedure :: set_array => frod_set_r8_1    ! Set variable array
        procedure :: get_value => frod_get_r8_0    ! Get variable value
        procedure :: get_array => frod_get_r8_1    ! Get variable array
        !--------------------------------------------------------------------

        procedure :: set_ch_0  => frod_set_ch_0     ! set variable of type character and rank 0
        procedure :: set_i4_0  => frod_set_i4_0     ! set variable of type integer and rank 0
        procedure :: set_i4_1  => frod_set_i4_1     ! set variable of type integer and rank 1
        procedure :: set_r8_0  => frod_set_r8_0     ! set variable of type real and rank 0
        procedure :: set_r8_1  => frod_set_r8_1     ! set variable of type real and rank 1
        procedure :: set_r8_2  => frod_set_r8_2     ! set variable of type real and rank 2

        procedure :: get_i4_0  => frod_get_i4_0     ! get variable of type integer and rank 0
        procedure :: get_i4_1  => frod_get_i4_1     ! get variable of type integer and rank 1
        procedure :: get_r8_0  => frod_get_r8_0     ! get variable of type real and rank 0
        procedure :: get_r8_1  => frod_get_r8_1     ! get variable of type real and rank 1
        procedure :: get_r8_2  => frod_get_r8_2     ! get variable of type real and rank 2

        procedure :: save_bin  => frod_save_bin     ! Save fuel rod state in a file
        procedure :: load_bin  => frod_load_bin     ! Load fuel rod state from a file
        procedure :: destroy   => frod_destroy      ! Deallocate the fuel rod variables
    end type t_fuelrod

    ! TEMPORARY VARIABLES
    character(len=20) :: frapmode_
    integer :: i, j, n, m
    real(8) :: a, b, c, volume
    real(8), allocatable :: weight(:)
    real(8), allocatable :: tmp0(:), tmp1(:), tmp2(:), tmp3(:)

contains

    subroutine frod_make(this, nr, na, ngasr, nce, frapmode, &
               mechan, ngasmod, icm, icor, iplant, &
               imox, igascal, zr2vintage, moxtype, idxgas, iq, ivardm, &
               ifixedcoolt, ifixedcoolp, ifixedtsurf, verbose, flag_iapws)

        class (t_fuelrod), intent(inout) :: this

        include "fi_optstatement_h.f90"

        integer :: nr_ = 17
        integer :: na_ = 10
        integer :: ngasr_ = 45
        integer :: nce_ = 5
        logical :: verbose_ = .false. 

        frapmode_ = 'frapcon'

        n  = na
        m  = nr

        if( present(nr          ) ) nr_      = nr
        if( present(na          ) ) na_      = na
        if( present(ngasr       ) ) ngasr_   = ngasr
        if( present(nce         ) ) nce_     = nce
        if( present(verbose     ) ) verbose_ = verbose
        if( present(frapmode    ) ) frapmode_= frapmode

        select case (frapmode_)

        case ('frapcon')

            call this % dfcon % make(na_, ngasr_, nr_+1, nce_, verbose_)

            call this % dfcon % deft()

            include "fi_optassignment_h.f90"

            call this % dfcon % dump()

        case ('fraptran')

            ! Allocate FRAPTRAN variables for given mesh sizes
            ! Link pointers of dftran to FRAPTRAN variables
            ! Allocate dftran's replicants of FRAPTRAN variables
            ! Set arguments of 'make' by default
            call this % dftran % make(na_, nr_, nce_, verbose_)

            ! Set dftran's variables (i.e. pointers to FRAPTRAN's variables) by default
            call this % dftran % deft()

            ! Read arguments of 'make' and set them to dftran's variables
            include "fi_optassignment_h.f90"

            ! Copy the dftran's variables into replicative variables
            call this % dftran % dump()

        case default
            write(*,*) "ERROR: option 'mode' must be 'frapcon' or 'fraptran' "

        end select

        ! ALLOCATION OF THE TEMPORARY ARRAYS
        if(.not. allocated(weight)) allocate(weight(m))
        if(.not. allocated(tmp0))   allocate(tmp0(m))
        if(.not. allocated(tmp1))   allocate(tmp1(n))
        if(.not. allocated(tmp2))   allocate(tmp2(m+1))
        if(.not. allocated(tmp3))   allocate(tmp3(n+1))

        this % is_initdone = .false.

    end subroutine frod_make

    subroutine frod_init(this)

        class (t_fuelrod), intent(inout) :: this

        select case (frapmode_)
        case ('frapcon')
            call frod_init_frapcon_(this)
        case ('fraptran')
            call frod_init_fraptran_(this)
        end select

    end subroutine frod_init


    subroutine frod_makerf(this)

        class (t_fuelrod), intent(inout) :: this

        select case (frapmode_)
        case ('frapcon')
            this % dfcon % namerf = this % namerf
            call this % dfcon % restfs()
        end select

    end subroutine frod_makerf


    subroutine frod_init_frapcon_(this)

        class (t_fuelrod), intent(inout) :: this

        this % dfcon % namerf = this % namerf

        call this % dfcon % proc()   ! processing and checking of input variables
        call this % dfcon % init()   ! make the very first time step

    end subroutine frod_init_frapcon_

    subroutine frod_init_fraptran_(this)

        class (t_fuelrod), intent(inout) :: this

        this % dftran % namerf = this % namerf
        this % dftran % ntstep = 1
        this % dftran % nsteadytrans = 1

        call this % dftran % init()   ! init variables, including reading of the restart file
        call this % dftran % next0()  ! make very first time step for steady-state

    end subroutine frod_init_fraptran_

    subroutine frod_next(this, dt)

        class (t_fuelrod), intent(inout) :: this

        real(8) :: dt

        if (dt < 1.E-20) then
            write(*,*) 'ERROR: time step is near to zero, dt = ', dt
        endif

        select case (frapmode_)
        case ('frapcon')
            call frod_next_frapcon_(this, dt)
        case ('fraptran')
            call frod_next_fraptran_(this, dt)
        end select

    end subroutine frod_next

    subroutine frod_next_frapcon_(this, dt)

        class (t_fuelrod), intent(inout) :: this

        real(8) :: dt

        !call this % dfcon % load()
        call this % dfcon % next(dt)

    end subroutine frod_next_frapcon_


    subroutine frod_next_fraptran_(this, dt)

        class (t_fuelrod), intent(inout) :: this

        real(8) :: dt, t0

        t0 = 0.D0
        !call this % dftran % load()
        call this % dftran % settime(2,t0)
        call this % dftran % settime(4,t0+dt)
        call this % dftran % next(dt)

    end subroutine frod_next_fraptran_


    subroutine frod_save_bin(this, filename)

        class (t_fuelrod), intent(inout) :: this

        character(*) :: filename

        call this % dfcon % save_state(filename)

    end subroutine frod_save_bin

    subroutine frod_load_bin(this, filename)

        class (t_fuelrod), intent(inout) :: this

        character(*) :: filename

        call this % dfcon % load_state(filename)

    end subroutine frod_load_bin

    subroutine frod_load(this)

        class (t_fuelrod), intent(inout) :: this

        select case (frapmode_)
        case ('frapcon')
            call this % dfcon % load()
        case ('fraptran')
            call this % dftran % load()
        end select

    end subroutine frod_load


    subroutine frod_save(this)

        class (t_fuelrod), intent(inout) :: this

        select case (frapmode_)
        case ('frapcon')
            call this % dfcon % dump()
        case ('fraptran')
            this % is_initdone = .true.
            call this % dftran % dump()
        end select

    end subroutine frod_save


    subroutine frod_set_ch_0(this, key, var)

        class (t_fuelrod), intent(inout) :: this

        character(*) :: key, var
        integer      :: it

        select case (frapmode_)
        case ('frapcon')
            select case (key)
            case ("restart file")
                this % namerf      = trim(var)
                !this % dfcon % namerf      = trim(var)
            case default
                call error_message(key, 'character rank 0 in the frapcon set-list')
            end select

        case ('fraptran') 
            select case (key)
            case ("restart file")
                this % namerf      = trim(var)
                !this % dftran % namerf      = trim(var)
            case ("coolant")
                this % dftran % coolant     = trim(var)
            case ("bheat")
                this % dftran % bheat       = trim(var)
            case ("mheat")
                this % dftran % mheat       = trim(var)
            case ("reflood")
                this % dftran % reflood     = trim(var)
            case ("internal")
                this % dftran % internal    = trim(var)
            case ("metal")
                this % dftran % metal       = trim(var)
            case ("deformation")
                this % dftran % deformation = trim(var)
            case ("inst")
                this % dftran % inst        = trim(var)
            case ("relocmodel")
                this % dftran % relocmodel  = trim(var)
            case default
                call error_message(key, 'character rank 0 in the fraptran set-list')
            end select
        end select

    end subroutine frod_set_ch_0

    subroutine frod_set_i4_0(this, key, var)

        class (t_fuelrod), intent(inout) :: this

        character(*) :: key
        integer      :: it
        integer(4)   :: var

        select case (frapmode_)
        case ('frapcon')
            select case(key)
            case("ifixedcool")
                this % dfcon % ifixedcoolt = var
                this % dfcon % ifixedcoolp = var
            case default
                call error_message (key, 'integer rank 1 in the frapcon set-list')
            end select
        case ('fraptran')
            select case(key)
            case("azang")
                this % dftran % azang = var
            case("iStoicGrad")
                this % dftran % iStoicGrad = var
            case("prestmp")
                this % dftran % prestmp = var
            case("nbhtc")
                this % dftran % nbhtc = var
            case("rtheta")
                this % dftran % rtheta = var
            case("prescri")
                this % dftran % prescri = var
            case("mechan")
                this % dftran % mechan = var
            case("nfmesh")
                this % dftran % nfmesh = var
            case("NumAxProfiles")
                this % dftran % NumAxProfiles = var
            case("radiat")
                this % dftran % radiat = var
            case("maxit")
                this % dftran % maxit = var
            case("tape1")
                this % dftran % tape1 = var
            case("jtr")
                this % dftran % jtr = var
            case("NRestart")
                this % dftran % nrestart = var
            case("irupt")
                this % dftran % irupt = var
            case("CladType")
                this % dftran % CladType = var
            case("odoxid")
                this % dftran % odoxid = var
            case("nchn")
                this % dftran % nchn = var
            case("TranSwell")
                this % dftran % TranSwell = var
            case("noiter")
                this % dftran % noiter = var
            case("nthermex")
                this % dftran % nthermex = var
!            case("ncmesh")
!                this % dftran % ncmesh = var
!            case("naxn")
!                this % dftran % naxn = var
            case("IndexFC2Print")
                this % dftran % IndexFC2Print = var
            case("irefine")
                this % dftran % irefine = var
            case("ProtectiveOxide")
                this % dftran % ProtectiveOxide = var
            case("nIDoxide")
                this % dftran % nIDoxide = var
            case("nce")
                this % dftran % nce = var
            case("IndexGrainBndSep")
                this % dftran % IndexGrainBndSep = var
            case("grass")
                this % dftran % grass = var
            case("ncolbp")
                this % dftran % ncolbp = var
            case("presfgr")
                this % dftran % presfgr = var
            case("inp")
                this % dftran % inp = var
            case("naz")
                this % dftran % naz = var
            case("jchf")
                this % dftran % jchf = var
            case("profile")
                this % dftran % profile = var
            case("nsym")
                this % dftran % nsym = var
            case("geomet")
                this % dftran % geomet      = var
            case("nvol1")
                this % dftran % nvol1       = var
            case("lowpl")
                this % dftran % lowpl       = var
            case("pressu")
                this % dftran % pressu      = var
            case("massfl")
                this % dftran % massfl      = var
            case("coreav")
                this % dftran % coreav      = var
            case("chf")
                this % dftran % chf         = var
            case("filmbo")
                this % dftran % filmbo      = var
            case("coldwa")
                this % dftran % coldwa      = var
            case("axpow")
                this % dftran % axpow       = var
            case("bowing")
                this % dftran % bowing      = var
            case("spefbz")
                this % dftran % spefbz      = var
            case("geometry")
                this % dftran % geometry    = var
            case("nbundl")
                this % dftran % nbundl      = var
            case("refloodtime")
                this % dftran % refloodtime = var
            case("ruptur")
                this % dftran % ruptur      = var
            case("liquid")
                this % dftran % liquid      = var
            case("inlet")
                this % dftran % inlet       = var
            case("reflo")
                this % dftran % reflo       = var
            case("pressure")
                this % dftran % pressure    = var
            case("collaps")
                this % dftran % collaps     = var
            case("frapt4")
                this % dftran % frapt4      = var
            case("geom")
                this % dftran % geom        = var
            case("temp")
                this % dftran % temp        = var
            case("tape2")
                this % dftran % tape2       = var
            case("nvol2")
                this % dftran % nvol2       = var
            case("zone")
                this % dftran % zone        = var
            case("upppl")
                this % dftran % upppl       = var
            case("jfb")
                this % dftran % jfb         = var
            case("nucbo")
                this % dftran % nucbo       = var
            case("unitin")
                this % dftran % unitin      = var
            case("unitout")
                this % dftran % unitout     = var
            case("res")
                this % dftran % res         = var
            case("pow")
                this % dftran % pow         = var
            case("gasflo")
                this % dftran % gasflo      = var
            case("idoxid")
                this % dftran % idoxid      = var
            case("cathca")
                this % dftran % cathca      = var
            case("baker")
                this % dftran % baker       = var
            case("noball")
                this % dftran % noball      = var
            case("cenvoi")
                this % dftran % cenvoi      = var
            case("soltyp")
                this % dftran % soltyp      = var
            case default
                call error_message(key, 'integer rank 1 in the fraptran set-list')
            end select
        end select

    end subroutine frod_set_i4_0


    subroutine frod_set_i4_1(this, key, var)

        class (t_fuelrod), intent(inout) :: this

        character(*) :: key
        integer      :: it
        integer(4)   :: var(:)

        select case (frapmode_)
        case ('frapcon')
            call error_message(key, 'integer rank 2 in the frapcon set-list')
        case ('fraptran')
            select case (key)
            case("ngastmp")
                this % dftran % ngastmp(:) = var(:)
            case("ncs")
                this % dftran % ncs(:) = var(:)
            case default
                call error_message(key, 'integer rank 2 in the fraptran set-list')
            end select
        end select

    end subroutine frod_set_i4_1


    subroutine frod_set_r8_0(this, key, var)

        class (t_fuelrod), intent(inout) :: this

        character(*) :: key
        integer      :: it, it3
        real(8)      :: var

        select case (frapmode_)
        
        case ('frapcon')
            it  = this % dfcon % it
            select case(key)
            case("fuel rod pitch, cm")
                this % dfcon % pitch = var * cmtoin
            case("as-fabricated apparent fuel density, %TD")
                this % dfcon % den = var
            case("coolant mass flux, kg|(s*m^2)")
                this % dfcon % go(it) = var * ksm2tolbhrft2
            case("additional fuel densification factor")
                this % dfcon % afdn         = var
            case("clad texture factor")
                this % dfcon % catexf       = var
            case("as-fabricated clad hydrogen content, wt.ppm")
                this % dfcon % chorg        = var                       
            case("clad cold work")
                this % dfcon % cldwks       = var                       
            case("cold plenum length, m")
                this % dfcon % cpl          = var * mtoin
            case("constant crud thickness, mm")
                this % dfcon % crdt         = var / miltomm
            case("crud accumulation rate")
                this % dfcon % crdtr        = var                       
            case("creep step duration, hr")
                this % dfcon % crephr       = var                       
            case("fuel open porosity fraction, %TD")
                this % dfcon % deng         = var                       
            case("spring diameter, mm")
                this % dfcon % dspg         = var * mmtoin              
            case("spring wire diameter, mm")
                this % dfcon % dspgw        = var * mmtoin              
            case("number of spring turns")
                this % dfcon % vs           = var
            case("peak-to-average power ratio")
                this % dfcon % fa           = var                       
            case("fill gas pressure, Pa")
                this % dfcon % fgpav        = var * PatoPSI             
            case("fuel oxygen-to-metal ratio")
                this % dfcon % fotmtl       = var                       
            case("weight ppm H2O in fuel, wt.ppm")
                this % dfcon % ppmh2o       = var                       
            case("weight ppm N2 in fuel, wt. ppm")
                this % dfcon % ppmn2        = var                       
            case("expected resintering density increase, kg|m^3")
                this % dfcon % rsntr        = var                       
            case("fision gas atoms per 100 fissions")
                this % dfcon % sgapf        = var                       
            case("swelling limit")
                this % dfcon % slim         = var                       
            case("pellet centering temperature, K")
                this % dfcon % tsint        = tkf(var)                  
            case("grain size of the fuel, um")
                this % dfcon % grnsize      = var                       
            case("FEA friction coefficient")
                this % dfcon % frcoef       = var                       
            case("percent IFBA rods in core, %")
                this % dfcon % ifba         = var                       
            case("boron-10 enrichment in ZrB2, atom %")
                this % dfcon % b10          = var                       
            case("ZrB2 thickness, mm")
                this % dfcon % zrb2thick    = var * mmtoin               
            case("ZrB2 density, %TD")
                this % dfcon % zrb2den      = var
            case("decay heat multiplier")
                this % dfcon % fpdcay       = var                       
            case("molar fraction of air")
                this % dfcon % amfair       = var                       
            case("molar fraction of argon")
                this % dfcon % amfarg       = var                       
            case("molar fraction of fission gas")
                this % dfcon % amffg        = var                       
            case("molar fraction of helium")
                this % dfcon % amfhe        = var                       
            case("molar fraction of hydrogen")
                this % dfcon % amfh2        = var                       
            case("molar fraction of water")
                this % dfcon % amfh2o       = var                       
            case("molar fraction of krypton")
                this % dfcon % amfkry       = var                       
            case("molar fraction of nitrogen")
                this % dfcon % amfn2        = var                       
            case("molar fraction of xenon")
                this % dfcon % amfxe        = var                       
            case("Bias on fuel thermal conductivity")
                this % dfcon % sigftc       = var                       
            case("Bias on fuel thermal expansion")
                this % dfcon % sigftex      = var                       
            case("Bias on fission gas release")
                this % dfcon % sigfgr       = var                       
            case("Bias on fuel swelling")
                this % dfcon % sigswell     = var                       
            case("Bias on cladding creep")
                this % dfcon % sigcreep     = var                       
            case("Bias on cladding axial growth")
                this % dfcon % siggro       = var                       
            case("Bias on cladding corrosion")
                this % dfcon % sigcor       = var                       
            case("Bias on cladding hydrogen pickup")
                this % dfcon % sigh2        = var                       
            case("fuel pellet Pu-239 content")
                this % dfcon % enrpu39      = var                       
            case("fuel pellet Pu-240 content")
                this % dfcon % enrpu40      = var                       
            case("fuel pellet Pu-241 content")
                this % dfcon % enrpu41      = var                       
            case("fuel pellet Pu-242 content")
                this % dfcon % enrpu42      = var
            case("pellet height, mm")
                this % dfcon % hplt         = var * mmtoin
            case("chamfer height, mm")
                this % dfcon % chmfrh       = var * mmtoin
            case("chamfer width, mm")
                this % dfcon % chmfrw       = var * mmtoin
            case("dish shoulder width, mm")
                this % dfcon % dishsd       = var * mmtoin
            case("dish height, mm")
                this % dfcon % hdish        = var * mmtoin
            case("clad roughness, mm")
                this % dfcon % roughc       = var * mmtoin
            case("fuel roughness, mm")
                this % dfcon % roughf       = var * mmtoin
            case("end-node to plenum heat transfer fraction")
                this % dfcon % qend(it)     = var
            case("rod internal pressure for FEA model, MPa")
                this % dfcon % p1(it)       = var * patoPSI
            case("inlet coolant temperature, C")
                this % dfcon % tw(it) = tcf(var)
            case("inlet coolant pressure, MPa")
                this % dfcon % p2(it) = var * MPatoPSI
            case("fuel enrichment by u-235, %")
                this % dfcon % enrch(:) = var
            case("cladding thickness, cm")
                this % dfcon % thkcld(:) = var * cmtoin
            case("gap thickness, cm")
                this % dfcon % thkgap(:) = var * cmtoin
            case("outer cladding diameter, cm")
                this % dfcon % dco(:) = var * cmtoin
            case("coolant system pressure, MPa")
                this % dfcon % p2(it) = var * MPatoPSI
            case("radius of the fuel pellet central annulus, mm")
                this % dfcon % rc(:) = var * mmtoin  
            case("total gap conductance, W|(m^2*K)")
                this % dfcon % TotalHgap(:) = var * Wm2KtoBhft2F
                this % dfcon % hgapt_flag   = .true.
            case default
                call error_message (key, 'real rank 0 in the frapcon set-list')
            end select

        case ('fraptran')
            it3 = if_a_else_b(this % is_initdone, 3, 1)
            select case (key)
            case("splbp")
                this % dftran % splbp = var
            case("tpowf")
                this % dftran % tpowf = var
            case("ruptstrain")
                this % dftran % ruptstrain = var
            case("frcoef")
                this % dftran % frcoef = var
            case("epsht1")
                this % dftran % epsht1 = var
            case("CladPower")
                this % dftran % CladPower = var
            case("pitch")
                this % dftran % pitch = var
            case("bowthr")
                this % dftran % bowthr = var
            case("dofang")
                this % dftran % dofang = var
            case("coldbp")
                this % dftran % coldbp = var
            case("frden")
                this % dftran % frden = var
            case("RodDiameter")
                this % dftran % RodDiameter = var
            case("refdtm")
                this % dftran % refdtm = var
            case("totnb")
                this % dftran % totnb = var
            case("powop")
                this % dftran % powop = var
            case("flxsec")
                this % dftran % flxsec = var
            case("ffch")
                this % dftran % ffch = var
            case("fpdcay")
                this % dftran % fpdcay = var
            case("roughc")
                this % dftran % roughc = var
            case("roughf")
                this % dftran % roughf = var
            case("prsacc")
                this % dftran % prsacc = var
            case("fpowr")
                this % dftran % fpowr = var
            case("tref")
                this % dftran % tref = var
            case("pelh")
                this % dftran % pelh = var
            case("pdrato")
                this % dftran % pdrato = var
            case("tgas0")
                this % dftran % tgas0 = var
            case("tsntrk")
                this % dftran % tsntrk = var
            case("spdbp")
                this % dftran % spdbp = var
            case("achn")
                this % dftran % achn = var
            case("tflux")
                this % dftran % tflux = var
            case("RodLength")
                this % dftran % RodLength = var
            case("OpenPorosityFraction")
                this % dftran % OpenPorosityFraction = var
            case("zad")
                this % dftran % zad = var
            case("rshrd")
                this % dftran % rshrd = var
            case("doffst")
                this % dftran % doffst = var
            case("emptm")
                this % dftran % emptm = var
            case("trise")
                this % dftran % trise = var
            case("fltgap2")
                this % dftran % fltgap2 = var
            case("hydiam")
                this % dftran % hydiam = var
            case("dishd")
                this % dftran % dishd = var
            case("ph")
                this % dftran % ph = var
            case("hrad")
                this % dftran % hrad = var
            case("dtss")
                this % dftran % dtss = var
            case("bup")
                this % dftran % bup = var
            case("cldwdc")
                this % dftran % cldwdc = var
            case("timop")
                this % dftran % timop = var
            case("cfluxa")
                this % dftran % cfluxa = var
            case("rvoid")
                this % dftran % rvoid = var
            case("dofset")
                this % dftran % dofset = var
            case("pl")
                this % dftran % pl = var
            case("fltgap")
                this % dftran % fltgap = var
            case("frpo2")
                this % dftran % frpo2 = var
            case("trest")
                this % dftran % trest = var
            case("fgrns")
                this % dftran % fgrns = var
            case("refine")
                this % dftran % refine = var
            case("modheat")
                this % dftran % modheat = var
            case("tmpac1")
                this % dftran % tmpac1 = var
            case("coldw")
                this % dftran % coldw = var
            case("dhe")
                this % dftran % dhe = var
            case("explenumv")
                this % dftran % explenumv = var
            case("dhy")
                this % dftran % dhy = var
            case("volbp")
                this % dftran % volbp = var
            case("rshd")
                this % dftran % rshd = var
            case("fotmtl")
                this % dftran % fotmtl = var
            case("gsms")
                this % dftran % gsms = var
            case("dishv0")
                this % dftran % dishv0 = var
            case("rnbnt")
                this % dftran % rnbnt = var
            case("zvoid2")
                this % dftran % zvoid2 = var
            case("gapthk")
                this % dftran % gapthk = var
            case("zvoid1")
                this % dftran % zvoid1 = var
            case("zs")
                this % dftran % zs = var
            case("FuelPelDiam")
                this % dftran % FuelPelDiam = var
            case("hbh")
                this % dftran % hbh(it3) = var
            case("hupta")
                this % dftran % hupta(it3) = var
            case("hinta")
                this % dftran % hinta(it3) = var
            case("gbh")
                this % dftran % gbh(it3) = var
            case("explenumt")
                this % dftran % explenumt(it3) = var
            case("pbh")
                this % dftran % pbh(it3) = var
            case("RodAvePower")
                this % dftran % RodAvePower(it3) = var
            case("FuelGasSwell")
                this % dftran % FuelGasSwell(it3) = var
            case("temptm")
                this % dftran % temptm(it3) = var
            case("relfraca")
                this % dftran % relfraca(it3) = var
            case("prestm")
                this % dftran % prestm(it3) = var
            case("fldrat")
                this % dftran % fldrat(it3) = var
            case("gasphs")
                this % dftran % gasphs(it3) = var
            case("hlqcl")
                this % dftran % hlqcl(it3) = var
    !        case("ProfileStartTime")
    !            this % dftran % ProfileStartTime(it_) = var
            case default
                call error_message(key, 'real rank 0 in the fraptran set-list')
            end select
        end select

    end subroutine frod_set_r8_0

    subroutine frod_set_r8_1(this, key, var)

        class (t_fuelrod), intent(inout) :: this

        character(*) :: key
        integer      :: it, k
        integer, parameter :: one = 1, two = 2, three = 3
        real(8)      :: var(:)

        select case (frapmode_)

        case ('frapcon')
            it  = this % dfcon % it
            select case(key)
            case("thickness of the axial nodes, cm")
                this % dfcon % deltaz(1:n) = var(:) * cmtoft
                this % dfcon % x(1)        = 0.d0                        ! Axial evaluation for linear power distribution, ft
                this % dfcon % x(2:n+1)    = (/( sum(this % dfcon % deltaz(:i)), i = 1, n )/)
                this % dfcon % deltaz(n+1) = this % dfcon % cpl
                this % dfcon % totl        = sum(this % dfcon % deltaz(1:n))            ! Total length of active fuel, ft
                this % dfcon % zcool(:)    = this % dfcon % x(:)        ! Axial evaluation for coolant temperature distribution, ft
            case("cladding thickness, cm")
                this % dfcon % thkcld(1:n) = var(:) * cmtoin
            case("gap thickness, cm")
                this % dfcon % thkgap(1:n) = var(:) * cmtoin
            case("outer cladding diameter, cm")
                this % dfcon % dco(1:n) = var(:) * cmtoin

            ! Must be removed in the future ---------------------------------------------------------
            case("FRAPCON FORMAT: linear power, W|cm")
                this % dfcon % qmpy(it) = sum(var) / cmtoft * & 
                sum(this % dfcon % deltaz(1:n) / this % dfcon % dco(1:n)) &
                / pi / intoft * WtoBTUh / this % dfcon % totl
                this % dfcon % qf(:) = var(:) / sum(var)
            case("FRAPCON FORMAT: coolant temperature, C")
                this % dfcon % coolanttemp(it,1:n+1) = (/( tcf(var(i)), i = 1, n+1 )/)
                this % dfcon % tcoolant(1:n+1) = (/( tcf(var(i)), i = 1, n+1 )/)
            case("FRAPCON FORMAT: coolant pressure, MPa")
                this % dfcon % p2(it) = var(1) * MPatoPSI
                this % dfcon % coolantpressure(it,1:n+1) = var(:) * MPatoPSI
                this % dfcon % pcoolant(1:n+1) = var(:) * MPatoPSI
            ! ----------------------------------------------------------------------------------------

            case("linear power, W|cm")
                call linterp(var, this % dfcon % deltaz(1:n), tmp3, n)
                a = sum( var(:) * this % dfcon % deltaz(1:n) ) / this % dfcon % totl /cmtoft ! W/ft
                b = sum( this % dfcon % deltaz(1:n) / this % dfcon % dco(1:n) ) &
                    / this % dfcon % totl / intoft ! 1/ft
                this % dfcon % qmpy(it) = a * b / pi * WtoBTUh ! BTUh/ft^2
                this % dfcon % qf(:) = tmp3(:) / sum(tmp3)
            case("coolant temperature, C")
                call linterp(var,  this % dfcon % deltaz(1:n), tmp3, n)
                this % dfcon % coolanttemp(it,1:n+1) = (/( tcf(tmp3(i)), i = 1, n+1 )/)
                this % dfcon % tcoolant(1:n+1) = (/( tcf(tmp3(i)), i = 1, n+1 )/)
            case("coolant pressure, MPa")
                call linterp(var, this % dfcon % deltaz(1:n), tmp3, n)
                this % dfcon % p2(it) = var(1) * MPatoPSI
                this % dfcon % coolantpressure(it,1:n+1) = tmp3(:) * MPatoPSI
                this % dfcon % pcoolant(1:n+1) = tmp3(:) * MPatoPSI
            case("input fuel burnup")
                this % dfcon % buin(:)      = var(:) * MWskgUtoMWdMTU
            case("PuO2 weight percent if MOX fuel, wt%")
                this % dfcon % comp(:)      = var(:)
            case("Heat flux, W|m^2")
                this % dfcon % qc(:)        = var(:) / Bhft2toWm2
            case("gadolinia weight, wt%")
                this % dfcon % gadoln(:)    = var(:)
            case("cladding surface temperature, K")
                this % dfcon % cladt(:)     = (/( tkf(var(i)), i = 1, n )/)
            case("axial crud thickness multiplier")
                this % dfcon % crudmult(:)  = var(:)
            case("neutron flux, 1|(cm^2*s)")
                this % dfcon % flux(:)  = var(:)
            case("fuel enrichment by u-235, %")
                this % dfcon % enrch(1:n) = var(:)
            case default
                call error_message(key, 'real rank 1 in the frapcon set-list')
            end select

        case ('fraptran')
            select case (key)
            case("scd")
                this % dftran % scd(:) = var(:)
            case("azpang")
                this % dftran % azpang(:) = var(:)
            case("fmesh")
                this % dftran % fmesh(:) = var(:)
            case("htclev")
                this % dftran % htclev(:) = var(:)
            case("ExtentOfBow")
                this % dftran % ExtentOfBow(:) = var(:)
            case("vplen")
                this % dftran % vplen(:) = var(:)
            case("gadoln")
                this % dftran % gadoln(:) = var(:)
            case("gfrac")
                this % dftran % gfrac(:) = var(:)
            case("gbse")
                this % dftran % gbse(:) = var(:)
            case("fluxz")
                this % dftran % fluxz(:) = var(:)
            case("nodchf")
                this % dftran % nodchf(:) = var(:)
            case("swd")
                this % dftran % swd(:) = var(:)
            case("oxideod")
                this % dftran % oxideod(:) = var(:)
            case("cexh2a")
                this % dftran % cexh2a(:) = var(:)
            case("radpel")
                this % dftran % radpel(:) = var(:)
            case("cmesh")
                this % dftran % cmesh(:) = var(:)
            case("gappr0")
                this % dftran % gappr0(:) = var(:)
            case("butemp")
                this % dftran % butemp(:) = var(:)
            case("oxideid")
                this % dftran % oxideid(:) = var(:)
            case("spl")
                this % dftran % spl(:) = var(:)
            case("eppinp")
                this % dftran % eppinp(:) = var(:)
            case("techf")
                this % dftran % techf(:) = var(:)
            case("tschf")
                this % dftran % tschf(:) = var(:)
            case("zelev")
                this % dftran % zelev(:) = var(:)
            case("htca")
                it = if_a_else_b(this % is_initdone, three, one)
                k = this % dftran % zone
                this % dftran % htca(it,1:k) = var(:)
            case("tblka")
                it = if_a_else_b(this % is_initdone, three, one)
                k = this % dftran % zone
                this % dftran % tblka(it,1:k) = var(:)
            case("gasths")
                it = if_a_else_b(this % is_initdone, three, one)
                k = this % dftran % zone
                this % dftran % gasths(it,1:k) = var(:)
            case("radtemp")
                it = if_a_else_b(this % is_initdone, two, one)
                this % dftran % radtemp(:,it) = var(:)
            case("fuelrad")
                it = if_a_else_b(this % is_initdone, two, one)
                this % dftran % fuelrad(:,it) = var(:)
            case("axpowprofile")
                it = if_a_else_b(this % is_initdone, two, one)
                this % dftran % axpowprofile(:,it) = var(:)
            case default
                call error_message(key, 'real rank 1 in the fraptran set-list')
            end select
        end select

    end subroutine frod_set_r8_1


    subroutine frod_set_r8_2(this, key, var)

        class (t_fuelrod), intent(inout) :: this

        character(*) :: key
        integer      :: it
        real(8)      :: var(:,:)

        select case (frapmode_)
        case ('frapcon')
            call error_message(key, 'real rank 2 in the frapcon set-list')
        case ('fraptran')
            select case (key)
            case("pazp")
                this % dftran % pazp(:,:) = var(:,:)
            case default
                call error_message(key, 'real rank 2 in the fraptran set-list')
            end select
        end select

    end subroutine frod_set_r8_2


    subroutine frod_get_i4_0(this, key, var)

        class (t_fuelrod), intent(in) :: this

        character(*) :: key
        integer      :: var

        select case (frapmode_)
        case ('frapcon')
            select case (key)
            case('program terminate')
                var = this % dfcon % iquit
            case default
                call error_message(key, 'integer rank 0 in the frapcon get-list')
            end select
        case ('fraptran')
            select case (key)
            case('dimension of radial node vectors')
                var = this % dftran % n1
            case('dimension of axial node vectors')
                var = this % dftran % n2
            case('number of nodes in mesh')
                var = this % dftran % nmesh
            case('number of nodes to gas gap / clad boundary')
                var = this % dftran % ncladi
            case('node number at surface of fuel pellet stack')
                var = this % dftran % igpnod
            case('deformation model indicator')
                var = this % dftran % modfd
            case('number of axial nodes')
                var = this % dftran % naxn
            case('iteration count')
                var = this % dftran % iterationcount
            case('total number of half meshes')
                var = this % dftran % n3
            case('balon2 predicts failure')
                var = this % dftran % ifbaln
            case('balon2 radial contact node')
                var = this % dftran % jmnbal
            case('balon2 predicts pellet-clad contact')
                var = this % dftran % kntbal
            case('balon2 has been called once')
                var = this % dftran % nbncal
            case('number flow area reduction subnodes')
                var = this % dftran % nodprm
            case('mode of cladding failure')
                var = this % dftran % modfal(1)
            case default
                call error_message(key, 'integer rank 0 in the fraptran get-list')
            end select
        end select

    end subroutine frod_get_i4_0

    subroutine frod_get_i4_1(this, key, var)

        class (t_fuelrod), intent(in) :: this

        character(*) :: key
        integer      :: var(:)

        select case (frapmode_)
        case ('frapcon')
            select case (key)
            case default
                call error_message(key, 'integer rank 1 in the frapcon get-list')
            end select
        case ('fraptran')
            select case(key)
            case('heat transfer mode')
                var(:) = this % dftran % ih (1:n)
            case('rupture indicator')
                var(:) = this % dftran % ruptfailindex (1:n)
            case('buckled cladding indicator')
                var(:) = this % dftran % cladcollapseindex (1:n)
            case default
                call error_message(key, 'integer rank 1 in the fraptran get-list')
            end select
        end select

    end subroutine frod_get_i4_1


    subroutine frod_get_r8_0(this, key, var)

        class (t_fuelrod), intent(in) :: this

        character(*) :: key
        integer      :: it
        real(8)      :: var

        select case (frapmode_)
        case ('frapcon')

            it = this % dfcon % it

            select case(key)
            case('average linear power, W|cm')
                var = this % dfcon % qmpy(it) * BTUhtokW * &
                     (this % dfcon % dcoBOL * intoft * pi) / this % dfcon % fa * &
                      1.D+3 * cmtoft
            case('outlet coolant mass flux, kg|(s*m^2)')
                var = this % dfcon % go(it) * lbhrft2toksm2
            case('plenum gas temperature, C')
                var = tfc(this % dfcon % tplen)
            case('plenum gas pressure, MPa')
                var = this % dfcon % press * PSItoMPa
            case('fission gas release, %')
                if(this % dfcon % ngasmod == 4) then
                    var = sum(this % dfcon % rb_rod(:,it)) * 100.d0
                else
                    var = this % dfcon % tfgfr * 100.d0
                endif
            case('time, day')
                var = this % dfcon % ProblemTime(it) * sectoday
            case('average fuel burnup, MW*d|kg')
                var = this % dfcon % bu * 1.D-3
            case default
                call error_message(key, 'real rank 0 in the frapcon get-list')
            end select
        case ('fraptran')
            select case (key)
            case('fuel stack elongation, mm')
                var = this % dftran % delth * fttomm
            case('cladding axial elongation, mm')
                var = this % dftran % dcldh * fttomm
            case('fuel average burnup, MWd|MTU')
                var = this % dftran % bup
            case('plutonium weight fraction')
                var = this % dftran % frpo2
            case('total void volume, mm^3')
                var = this % dftran % totalvoidvol * fttomm ** 3
            case('maximum hoop stress in balloon region, MPa')
                var = this % dftran % chstrs * PSItoMPa
            case('balon2 circular/radial model switch')
                var = this % dftran % frbal
            case('balon2 maximum gap pressure, MPa')
                var = this % dftran % pmxbal * PSItoMPa
            case('balon2 average radius at balon2 axial node 8, m')
                var = this % dftran % r8bal
            case('maximum circumferential strain in balloon region, %')
                var = this % dftran % tcebal
            case('bundle pitch to rod diameter ratio')
                var = this % dftran % pdrato
            case('ratio of balloonable cells to total cells')
                var = this % dftran % rnbnt
            case('total number of cells in a bundle')
                var = this % dftran % totnb
            case('average fuel rod power, kW|m')
                var = this % dftran % powave (1) / fttom
            case('flow blockage, %')
                var = this % dftran % flwblk (1)
            case('plenum gas temperature, K')
                var = tfk(this % dftran % tp (1))
            case('gas flow rate, g*moles/sec')
                var = this % dftran % flowg (1)
            case('fuel melt temperature, K')
                var = tfk(this % dftran % tmelt (1))
            case('plenum gas pressure, MPa')
                var = this % dftran % gaspress(n+1) * PSItoMPa
            case('total water metal reaction energy, kW|m')
                var = sum(this % dftran % watrmetlenrgy(1:n)) / fttom
            case default
                call error_message(key, 'real rank 0 in the fraptran get-list')
            end select
        end select

    end subroutine frod_get_r8_0

    subroutine frod_get_r8_1(this, key, var)

        class (t_fuelrod), intent(in) :: this

        character(*) :: key
        integer      :: it
        real(8)      :: var(:) ! array (n,)
!        real(8)      :: ra, rb, ya, yb, h, temper, volume
!        real(8)      :: linteg ! integral of linear function

        select case (frapmode_)
        case ('frapcon')
            it = this % dfcon % it

            select case(key)
    !        case('axial fuel temperature, C')
    !            do i = 1, n
    !                volume = 0
    !                temper = 0
    !                do j = 1, m
    !                    ya = 1.d0
    !                    yb = 1.d0
    !                    ra = this % dfcon % hrad(j+1,i)
    !                    rb = this % dfcon % hrad(j,i)
    !                    h = this % dfcon % x(i+1) - this % dfcon % x(i)
    !                    volume = volume + linteg(ya,yb,ra,rb,h)
    !                    ya = this % dfcon % tmpfuel(j+1,i)
    !                    yb = this % dfcon % tmpfuel(j,i)
    !                    temper = temper + linteg(ya,yb,ra,rb,h)
    !                enddo
    !                var(i) = tfc(temper / volume)
    !            enddo
            case('fuel volume average temperature, C')
                var(:) = (/( tfc(this % dfcon % PelAveTemp(i)), i = 1, n )/)
            case('gap average temperature, C')
                var(:) = (/( tfc(this % dfcon % GapAveTemp(i)), i = 1, n )/)
            case('cladding average temperature, C')
                var(:) = (/( tfc(this % dfcon % CladAveTemp(i)), i = 1, n )/)
            case('bulk coolant temperature, C')
                var(:) = 0.5d0 * ( this % dfcon % BulkCoolantTemp(1:n) + this % dfcon % BulkCoolantTemp(2:n+1) )
                var(:) = (/( tfc(var(i)), i = 1, n )/)
            case('total gap conductance, W|(m^2*K)')
                var(:) = this % dfcon % TotalHgap(1:n) * Bhft2FtoWm2K
            case('oxide thickness, um')
                var(:) = this % dfcon % EOSZrO2Thk(1:n) * fttomil * miltoum
            case('thermal gap thickness, um')
                var(:) = this % dfcon % gapplot(1:n) * miltoum
            case('mechanical gap thickness, um')
                var(:) = this % dfcon % FuelCladGap(1:n) * 1.D+3 * miltoum
            case('gap pressure, MPa')
                var(:) = this % dfcon % GapPress(1:n) * PSItoMPa
            case('cladding total hoop strain, %')
                var(:) = this % dfcon  % eps(1:n,1) * 100
            case('cladding total axial strain, %')
                var(:) = this % dfcon  % eps(1:n,2) * 100
            case('cladding total radial strain, %')
                var(:) = this % dfcon  % eps(1:n,3) * 100
            case('cladding permanent hoop strain, %')
                var(:) = this % dfcon  % epp(1:n,1) * 100
            case('cladding permanent axial strain, %')
                var(:) = this % dfcon  % epp(1:n,2) * 100
            case('cladding permanent radial strain, %')
                var(:) = this % dfcon  % epp(1:n,3) * 100
            case('cladding termal hoop strain, %')
                var(:) = this % dfcon % ThermalStrain(1:n,1) * 100
            case('cladding termal axial strain, %')
                var(:) = this % dfcon % ThermalStrain(1:n,2) * 100
            case('cladding termal radial strain, %')
                var(:) = this % dfcon % ThermalStrain(1:n,3) * 100
            case('cladding hoop stress, MPa')
                var(:) = this % dfcon  % sig(1:n,1) * PSItoMPa
            case('cladding axial stress, MPa')
                var(:) = this % dfcon  % sig(1:n,2) * PSItoMPa
            case('cladding radial stress, MPa')
                var(:) = this % dfcon  % sig(1:n,3) * PSItoMPa
            case('cladding inner radius displacement, mm')
                var(:) = this % dfcon % totinner(1:n) * intomm
            case('cladding outer radius displacement, mm')
                var(:) = this % dfcon % totcrl(1:n) * intomm
            case('cladding creep rate')
                var(:) = this % dfcon % creapratearray(1:n)
            case('fuel surface outward displacement, mm')
                var(:) = this % dfcon % totdef(1:n) * intomm
            case('fuel thermal expansion, mm')
                var(:) = this % dfcon % fuelexptot(1:n) * intomm
            case('fuel swelling, um')
                var(:) = this % dfcon % fuelswltot(1:n) * intoum
            case('fuel creep, mm')
                var(:) = this % dfcon % fuelcreeptot(1:n) * intomm
            case('fuel densification, mm')
                var(:) = this % dfcon % fueldentot(1:n) * intomm
            case('fuel relocation, mm')
                var(:) = this % dfcon % relocation(1:n) * intomm
            case('cladding hydrogen concentration, ppm')
                var(:) = this % dfcon % CladH2Concen(1:n)
            case('coolant density, kg|m^3')
                var(:) = 0.5d0*(this % dfcon % rhof(1:n) + this % dfcon % rhof(2:n+1)) * lbft3tokgm3 
            case('coolant pressure, MPa')
                var(:) = this % dfcon % coolantpressure(it,1:n) * PSItoMPa
            case('axial mesh, cm')
                var(:) = 0.5d0 * (this % dfcon % x(1:n) + this % dfcon % x(2:n+1)) / cmtoft
            case('gas release fractions')
                var(:) = this % dfcon % RB_rod(1:11,it)
            case('centerline temperature, C')
                var(:) = (/( tfc(this % dfcon % tmpfuel(m+1,i)), i = 1, n )/)
            case('fuel stored energy, J|kg')
                var(:) = this % dfcon % StoredEnergy(1:n) * BTUlbtoJkg
            case('fuel burnup, MW*d|kg')
                var(:) = this % dfcon % EOSNodeburnup(1:n) * 1.D-3 ! / MWskgUtoMWdMTU
            case('cladding inner temperature, C')
                var(:) = (/(tfc(this % dfcon % CladInSurfTemp(i)), i = 1, n )/) 
            case('cladding outer temperature, C')
                var(:) = (/(tfc(this % dfcon % CladOutSurfTemp(i)), i = 1, n )/)  
            case('cladding middle temperature, C')
                var(:) = (/(tfc(this % dfcon % CladOutSurfTemp(i) + this % dfcon % CladOutSurfTemp(i))*0.5d0, i = 1, n )/)  
            case('radial meshes, cm')
                var(:) = (/(this % dfcon % hrad(m - i + 1, 1), i = 0, m )/) 
                var(:) = var(:) * intocm
            case('fuel surface temperature, C')
                var(:) = (/( tfc(this % dfcon % tmpfuel(1,i)), i = 1, n )/)
            case default
                call error_message(key, 'real rank 1 in the frapcon get-list')
            end select
        case('fraptran')
            select case (key)
            case('cladding total hoop strain, %')
                var(:) = this % dftran % CldStrn(1:n,1)
            case('cladding total axial strain, %')
                var(:) = this % dftran % CldStrn(1:n,2)
            case('cladding total radial strain, %')
                var(:) = this % dftran % CldStrn(1:n,3)
            case('cladding plastic hoop strain, %')
                var(:) = this % dftran % CldPlasStrn(1:n,1)
            case('cladding plastic axial strain, %')
                var(:) = this % dftran % CldPlasStrn(1:n,2)
            case('cladding plastic radial strain, %')
                var(:) = this % dftran % CldPlasStrn(1:n,3)
            case('cladding elastic hoop strain, %')
                var(:) = this % dftran % CldElStrn(1:n,1)
            case('cladding elastic axial strain, %')
                var(:) = this % dftran % CldElStrn(1:n,2)
            case('cladding elastic radial strain, %')
                var(:) = this % dftran % CldElStrn(1:n,3)
            case('cladding thermal hoop strain, %')
                var(:) = this % dftran % CldThermStrn(1:n,1)
            case('cladding thermal axial strain, %')
                var(:) = this % dftran % CldThermStrn(1:n,2)
            case('cladding thermal radial strain, %')
                var(:) = this % dftran % CldThermStrn(1:n,3)
            case('cladding hoop stress, MPa')
                var(:) = this % dftran % CldStress(1:n,1) * PSItoMPa
            case('cladding axial stress, MPa')
                var(:) = this % dftran % CldStress(1:n,2) * PSItoMPa
            case('cladding radial stress, MPa')
                var(:) = this % dftran % CldStress(1:n,3) * PSItoMPa
            case('average cladding temperature, K')
                var(:) = (/( tfk(this % dftran % CladAveTemp(i)), i = 1, n)/)
            case('cold state radius, mm')
                var(:) = this % dftran % radialbound (1:n)
            case('cldpermaxstrn')
                var(:) = this % dftran % cldpermaxstrn (1:n)
            case('cldpermhoopstrn')
                var(:) = this % dftran % cldpermhoopstrn (1:n)
            case('gap pressure, MPa')
                var(:) = this % dftran % gaspress (1:n) * PSItoMPa
            case('axial power, kW|m')
                var(:) = this % dftran % axialpowr (1:n) / fttom
            case('surface heat flux, W|m^2')
                var(:) = this % dftran % heatflux (1:n) * Bhft2toWm2 * 3600.D+0
            case('axial node elevation, mm')
                var(:) = this % dftran % axnodelevat (1:n) * fttomm
            case('critical heat flux, W|m2')
                var(:) = this % dftran % crithtflux (1:n) * Bhft2toWm2 * 3600.D+0
            case('coolant pressure, MPa')
                var(:) = this % dftran % coolpress(1:n) * PSItoMPa
            case('surface heat transfer coefficient, W|m^2K')
                var(:) = this % dftran % filmcoeffav(1:n) * Bhft2FtoWm2K
            case('heat transfer coefficient, W|m^2K')
                var(:) = this % dftran % hgapav(1:n) * Bhft2FtoWm2K
            case('outer oxide thickness, mm')
                var(:) = this % dftran % eosoxidethick(1:n) * fttomm
            case('inner oxide thickness, mm')
                var(:) = this % dftran % oxithk2(1:n) * fttomm
            case('water metal reaction energy, kW|m')
                var(:) = this % dftran % watrmetlenrgy(1:n) / fttom
            case('axial node length, m')
                var(:) = this % dftran % axialnodlen(1:n) * fttom
            case('cladding permanent radial strain, %')
                var(:) = this % dftran % cldpermstrn(1:n)
            case('maximum energy half mesh can absorb in melting')
                var(:) = this % dftran % qmaxmelt(1:n)
            case('structural radial gap, mm')
                var(:) = this % dftran % rinterfacgap(1:n) * 1.2D+4 * miltomm
            case('interface pressure between fuel and cladding, MPa')
                var(:) = this % dftran % rinterfacprs(1:n) * PSItoMPa
            case('cladding effective stress, MPa')
                var(:) = this % dftran % cladeffstress(1:n) * PSItoMPa
            case('effective cladding strain, %')
                var(:) = this % dftran % effstrain(1:n)
            case('cladding instability strain, %')
                var(:) = this % dftran % einstabilstrain(1:n)
            case('stress at instability strain, MPa')
                var(:) = this % dftran % stressatinststrain(1:n)
            case('work-hardened yield stress, MPa')
                var(:) = this % dftran % cladyieldstress(1:n) * PSItoMPa
            case('flow area reduction')
                var(:) = this % dftran % farbal(1:n)
            case('standard deviation of flow area reduction')
                var(:) = this % dftran % sdfar(1:n)
            case('axial location flow area reduction subnodes, m')
                var(:) = this % dftran % zfarbl(1:n)
            case("sigmah")
                var(:) = this % dftran % CldStress(:,1)
            case("sigmaz")
                var(:) = this % dftran % CldStress(:,2)
            case('thermal radial gap, mm')
                var(:) = this % dftran % gapthick (1:n) * 1.2D+4 * miltomm
            case('cladding effective elastic-plastic strain, %')
                var(:) = this % dftran % EffStrainPNNL(1:n)
            case('coolant mass flux, kg|sm2')
                var(:) = this % dftran % rmassflux(1:n) * lbhrft2toksm2
            case('pellet surface displacement, mm')
                var(:) = this % dftran % PelSrfDispl(1:n) * fttomm
            case('structural gap interface pressure, MPa')
                var(:) = this % dftran % TerfacePres(1:n) * PSItoMPa
            case('coolant density, kg|m^3')
                var(:) = this % dftran % CoolDensity(1:n) * lbft3tokgm3
            case('pellet surface hoop strain, %')
                var(:) = this % dftran % PelSrfStrn(1:n,1)
            case('pellet surface axial strain, %')
                var(:) = this % dftran % PelSrfStrn(1:n,2)
            case('cladding hoop strain rate')
                var(:) = this % dftran % CldStrnRat(1:n,1)
            case('CladEnrgPerL')
                var(:) = this % dftran % CladEnrgPerL(1:n) / fttom
            case('EnergyPerL')
                var(:) = this % dftran % EnergyPerL(1:n) / fttom
            case('HFXSum')
                var(:) = this % dftran % HFXSum(1:n) / fttom
            case('k coefficient')
                var(:) = this % dftran % coefk(1:n)
            case('n coefficient')
                var(:) = this % dftran % coefn(1:n)
            case('m coefficient')
                var(:) = this % dftran % coefm(1:n)
            case('elastic modulus, MPa')
                var(:) = this % dftran % emodulus(1:n)
            case('strain rate coefficient')
                var(:) = this % dftran % strainrateterm(1:n)
            case('sed based on elastic-plastic effective strain')
                var(:) = this % dftran % sedpnnl(1:n)
            case("sed based on epri's formulation")
                var(:) = this % dftran % sedepri(1:n)
            case("coolant quality")
                var(:) = this % dftran % coolqual(1:n)
            case("c-p or b-j od oxygen uptake")
                var(:) = this % dftran % oxygenuptake(1:n)
            case("c-p or b-j id oxygen uptake")
                var(:) = this % dftran % oxuptakeid2(1:n)
            case("c-p or b-j cladding ecr")
                var(:) = this % dftran % ecr(1:n)
            case('centerline temperature, K')
                var(:) = (/( tfk(this % dftran % eostemp(1,i)), i = 1, n )/)
            case('fuel pellet surface temperature, K')
                var(:) = (/( tfk(this % dftran % eostemp(this % dftran % igpnod,i)), i = 1, n )/)
            case('cladding inner temperature, K')
                var(:) = (/( tfk(this % dftran % eostemp(this % dftran % ncladi,i)), i = 1, n )/)
            case("cladding outer temperature, K")
                var(:) = (/( tfk(this % dftran % eostemp(this % dftran % nmesh, i)), i = 1, n )/)
            case("bulk coolant temperature, K")
                var(:) = (/( tfk(this % dftran % BulkCoolTemp(i)), i = 1, n )/)
            case default
                call error_message(key, 'real rank 1 in the fraptran get-list')
            end select
        end select

    end subroutine frod_get_r8_1


    subroutine frod_get_r8_2(this, key, var)

        class (t_fuelrod), intent(in) :: this

        character(*) :: key
        integer :: na, nr
        real(8)      :: var(:,:) ! array (n,)

        select case (frapmode_)
        case ('frapcon')
            select case(key)
            case('fuel temperature distribution, C') ! YU JIANKAI
                !tfc = (tf - 32.0_r8k) / 1.8_r8k
                do i = 1, n 
                    do j = 1, m + 1
                        var(j,i) = tfc(this % dfcon % tmpfuel(m + 2 - j, i))
                    enddo
                enddo 
            case default
                call error_message(key, 'real rank 2 in frapcon get-list')
            end select
        case ('fraptran')
            nr = this % dftran % nradialnodes
            na = this % dftran % naxn
            select case (key)
            case('eos temperature, K')
                var(:,:) = (this % dftran % eostemp (1:nr, 1:na) + 4.5967D+2) / 1.8D+0
            case('eos radius, mm')
                var(:,:) = this % dftran % eosrad (1:nr, 1:na) * fttomm
            case('energy absorbed in melting')
                var(:,:) = this % dftran % enrgymeltz (1:nr,1:na)
            case('DeformedRadiusOfMesh')
                var(:,:) = this % dftran % DeformedRadiusOfMesh (1:m,1:n) * fttomm
            case default
                call error_message(key, 'real rank 2 in fraptran get-list')
            end select
        end select

    end subroutine frod_get_r8_2

    subroutine frod_destroy(this)

        class (t_fuelrod), intent(inout) :: this

        select case (frapmode_)
        case ('frapcon')
            call this % dfcon % destroy()
        case ('fraptran')
            call this % dftran % destroy()
        end select

    end subroutine frod_destroy

    subroutine error_message (vname, vtype)
        implicit none
        character(*) :: vname, vtype
        write(*,*) "ERROR: Could not find variable '", trim(vname), "' of the type ", vtype
        !call backtrace
        call exit(1) 
    end subroutine error_message

end module frapi



